/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: BindEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __BINDENTRYNUMS_H__	// Avoid multiple inclusion
#define __BINDENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum bindEntryNumTag {
	bindEntryNum__h_errnoEnum = 0,
	bindEntryNumhstrerrorEnum,
	bindEntryNumgethostentEnum,
	bindEntryNumgethostbyaddrEnum,
	bindEntryNumgethostbynameEnum,
	bindEntryNumgethostbyname2Enum,
	bindEntryNumsethostentEnum,
	bindEntryNumendhostentEnum,
	bindEntryNumgetnetentEnum,
	bindEntryNumgetnetbyaddrEnum,
	bindEntryNumgetnetbynameEnum,
	bindEntryNumsetnetentEnum,
	bindEntryNumendnetentEnum,
	bindEntryNumgetprotoentEnum,
	bindEntryNumgetprotobynameEnum,
	bindEntryNumgetprotobynumberEnum,
	bindEntryNumsetprotoentEnum,
	bindEntryNumendprotoentEnum,
	bindEntryNumgetserventEnum,
	bindEntryNumgetservbynameEnum,
	bindEntryNumgetservbyportEnum,
	bindEntryNumsetserventEnum,
	bindEntryNumendserventEnum,
	bindEntryNumgetaddrinfoEnum,
	bindEntryNumgetnameinfoEnum,
	bindEntryNumfreeaddrinfoEnum,
	bindEntryNumgai_strerrorEnum,
	bindEntryNumgetipnodebynameEnum,
	bindEntryNumgetipnodebyaddrEnum,
	bindEntryNumfreehostentEnum,
	bindEntryNuminet_addrEnum,
	bindEntryNuminet_ntoaEnum,
	bindEntryNuminet_ntopEnum,
	bindEntryNuminet_ptonEnum,
	bindEntryNuminet_atonEnum,
	bindEntryNuminet_lnaofEnum,
	bindEntryNuminet_makeaddrEnum,
	bindEntryNuminet_netofEnum,
	bindEntryNuminet_networkEnum,
	bindEntryNumdas_context_initEnum,
	bindEntryNumdas_context_freeEnum,
	bindEntryNumdas_getaddrinfoEnum,
	bindEntryNumdas_freeaddrinfoEnum,
	bindEntryNumdas_interface_flag_getEnum,
	bindEntryNumdas_route_get_outgoingEnum,
};

#define bindEntryNum__h_errno              	((uint32_t)bindEntryNum__h_errnoEnum)
#define bindEntryNumhstrerror              	((uint32_t)bindEntryNumhstrerrorEnum)
#define bindEntryNumgethostent             	((uint32_t)bindEntryNumgethostentEnum)
#define bindEntryNumgethostbyaddr          	((uint32_t)bindEntryNumgethostbyaddrEnum)
#define bindEntryNumgethostbyname          	((uint32_t)bindEntryNumgethostbynameEnum)
#define bindEntryNumgethostbyname2         	((uint32_t)bindEntryNumgethostbyname2Enum)
#define bindEntryNumsethostent             	((uint32_t)bindEntryNumsethostentEnum)
#define bindEntryNumendhostent             	((uint32_t)bindEntryNumendhostentEnum)
#define bindEntryNumgetnetent              	((uint32_t)bindEntryNumgetnetentEnum)
#define bindEntryNumgetnetbyaddr           	((uint32_t)bindEntryNumgetnetbyaddrEnum)
#define bindEntryNumgetnetbyname           	((uint32_t)bindEntryNumgetnetbynameEnum)
#define bindEntryNumsetnetent              	((uint32_t)bindEntryNumsetnetentEnum)
#define bindEntryNumendnetent              	((uint32_t)bindEntryNumendnetentEnum)
#define bindEntryNumgetprotoent            	((uint32_t)bindEntryNumgetprotoentEnum)
#define bindEntryNumgetprotobyname         	((uint32_t)bindEntryNumgetprotobynameEnum)
#define bindEntryNumgetprotobynumber       	((uint32_t)bindEntryNumgetprotobynumberEnum)
#define bindEntryNumsetprotoent            	((uint32_t)bindEntryNumsetprotoentEnum)
#define bindEntryNumendprotoent            	((uint32_t)bindEntryNumendprotoentEnum)
#define bindEntryNumgetservent             	((uint32_t)bindEntryNumgetserventEnum)
#define bindEntryNumgetservbyname          	((uint32_t)bindEntryNumgetservbynameEnum)
#define bindEntryNumgetservbyport          	((uint32_t)bindEntryNumgetservbyportEnum)
#define bindEntryNumsetservent             	((uint32_t)bindEntryNumsetserventEnum)
#define bindEntryNumendservent             	((uint32_t)bindEntryNumendserventEnum)
#define bindEntryNumgetaddrinfo            	((uint32_t)bindEntryNumgetaddrinfoEnum)
#define bindEntryNumgetnameinfo            	((uint32_t)bindEntryNumgetnameinfoEnum)
#define bindEntryNumfreeaddrinfo           	((uint32_t)bindEntryNumfreeaddrinfoEnum)
#define bindEntryNumgai_strerror           	((uint32_t)bindEntryNumgai_strerrorEnum)
#define bindEntryNumgetipnodebyname        	((uint32_t)bindEntryNumgetipnodebynameEnum)
#define bindEntryNumgetipnodebyaddr        	((uint32_t)bindEntryNumgetipnodebyaddrEnum)
#define bindEntryNumfreehostent            	((uint32_t)bindEntryNumfreehostentEnum)
#define bindEntryNuminet_addr              	((uint32_t)bindEntryNuminet_addrEnum)
#define bindEntryNuminet_ntoa              	((uint32_t)bindEntryNuminet_ntoaEnum)
#define bindEntryNuminet_ntop              	((uint32_t)bindEntryNuminet_ntopEnum)
#define bindEntryNuminet_pton              	((uint32_t)bindEntryNuminet_ptonEnum)
#define bindEntryNuminet_aton              	((uint32_t)bindEntryNuminet_atonEnum)
#define bindEntryNuminet_lnaof             	((uint32_t)bindEntryNuminet_lnaofEnum)
#define bindEntryNuminet_makeaddr          	((uint32_t)bindEntryNuminet_makeaddrEnum)
#define bindEntryNuminet_netof             	((uint32_t)bindEntryNuminet_netofEnum)
#define bindEntryNuminet_network           	((uint32_t)bindEntryNuminet_networkEnum)
#define bindEntryNumdas_context_init       	((uint32_t)bindEntryNumdas_context_initEnum)
#define bindEntryNumdas_context_free       	((uint32_t)bindEntryNumdas_context_freeEnum)
#define bindEntryNumdas_getaddrinfo        	((uint32_t)bindEntryNumdas_getaddrinfoEnum)
#define bindEntryNumdas_freeaddrinfo       	((uint32_t)bindEntryNumdas_freeaddrinfoEnum)
#define bindEntryNumdas_interface_flag_get 	((uint32_t)bindEntryNumdas_interface_flag_getEnum)
#define bindEntryNumdas_route_get_outgoing 	((uint32_t)bindEntryNumdas_route_get_outgoingEnum)
#endif // __BINDENTRYNUMS_H__
