/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: BitmapLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:54 2004
 *****************************************************************************/
#ifndef __BITMAPLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __BITMAPLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum bitmaplibEntryNumTag {
	bitmaplibEntryNumBmpCreateEnum = 0,
	bitmaplibEntryNumBmpCreateBitmapV3Enum,
	bitmaplibEntryNumBmpCreateVersion3Enum,
	bitmaplibEntryNumBmpDeleteEnum,
	bitmaplibEntryNumBmpColortableSizeEnum,
	bitmaplibEntryNumBmpCompressEnum,
	bitmaplibEntryNumBmpGetBitDepthEnum,
	bitmaplibEntryNumBmpGetBitsEnum,
	bitmaplibEntryNumBmpGetColortableEnum,
	bitmaplibEntryNumBmpGetCompressionTypeEnum,
	bitmaplibEntryNumBmpGetDensityEnum,
	bitmaplibEntryNumBmpGetDimensionsEnum,
	bitmaplibEntryNumBmpGetNextBitmapEnum,
	bitmaplibEntryNumBmpGetNextBitmapAnyDensityEnum,
	bitmaplibEntryNumBmpGetSizesEnum,
	bitmaplibEntryNumBmpGetTransparentValueEnum,
	bitmaplibEntryNumBmpGetVersionEnum,
	bitmaplibEntryNumBmpGetPixelFormatEnum,
	bitmaplibEntryNumBmpSetDensityEnum,
	bitmaplibEntryNumBmpSetTransparentValueEnum,
	bitmaplibEntryNumBmpSizeEnum,
	bitmaplibEntryNumBmpGetBestBitmapDepthEnum,
	bitmaplibEntryNumBmpSelectBitmapFromFamilyEnum,
	bitmaplibEntryNumBmpDumpBitmapEnum,
	bitmaplibEntryNumBmpDumpColortableEnum,
	bitmaplibEntryNumBmpPrvConvertBitmapEnum,
};

#define bitmaplibEntryNumBmpCreate                  	((uint32_t)bitmaplibEntryNumBmpCreateEnum)
#define bitmaplibEntryNumBmpCreateBitmapV3          	((uint32_t)bitmaplibEntryNumBmpCreateBitmapV3Enum)
#define bitmaplibEntryNumBmpCreateVersion3          	((uint32_t)bitmaplibEntryNumBmpCreateVersion3Enum)
#define bitmaplibEntryNumBmpDelete                  	((uint32_t)bitmaplibEntryNumBmpDeleteEnum)
#define bitmaplibEntryNumBmpColortableSize          	((uint32_t)bitmaplibEntryNumBmpColortableSizeEnum)
#define bitmaplibEntryNumBmpCompress                	((uint32_t)bitmaplibEntryNumBmpCompressEnum)
#define bitmaplibEntryNumBmpGetBitDepth             	((uint32_t)bitmaplibEntryNumBmpGetBitDepthEnum)
#define bitmaplibEntryNumBmpGetBits                 	((uint32_t)bitmaplibEntryNumBmpGetBitsEnum)
#define bitmaplibEntryNumBmpGetColortable           	((uint32_t)bitmaplibEntryNumBmpGetColortableEnum)
#define bitmaplibEntryNumBmpGetCompressionType      	((uint32_t)bitmaplibEntryNumBmpGetCompressionTypeEnum)
#define bitmaplibEntryNumBmpGetDensity              	((uint32_t)bitmaplibEntryNumBmpGetDensityEnum)
#define bitmaplibEntryNumBmpGetDimensions           	((uint32_t)bitmaplibEntryNumBmpGetDimensionsEnum)
#define bitmaplibEntryNumBmpGetNextBitmap           	((uint32_t)bitmaplibEntryNumBmpGetNextBitmapEnum)
#define bitmaplibEntryNumBmpGetNextBitmapAnyDensity 	((uint32_t)bitmaplibEntryNumBmpGetNextBitmapAnyDensityEnum)
#define bitmaplibEntryNumBmpGetSizes                	((uint32_t)bitmaplibEntryNumBmpGetSizesEnum)
#define bitmaplibEntryNumBmpGetTransparentValue     	((uint32_t)bitmaplibEntryNumBmpGetTransparentValueEnum)
#define bitmaplibEntryNumBmpGetVersion              	((uint32_t)bitmaplibEntryNumBmpGetVersionEnum)
#define bitmaplibEntryNumBmpGetPixelFormat          	((uint32_t)bitmaplibEntryNumBmpGetPixelFormatEnum)
#define bitmaplibEntryNumBmpSetDensity              	((uint32_t)bitmaplibEntryNumBmpSetDensityEnum)
#define bitmaplibEntryNumBmpSetTransparentValue     	((uint32_t)bitmaplibEntryNumBmpSetTransparentValueEnum)
#define bitmaplibEntryNumBmpSize                    	((uint32_t)bitmaplibEntryNumBmpSizeEnum)
#define bitmaplibEntryNumBmpGetBestBitmapDepth      	((uint32_t)bitmaplibEntryNumBmpGetBestBitmapDepthEnum)
#define bitmaplibEntryNumBmpSelectBitmapFromFamily  	((uint32_t)bitmaplibEntryNumBmpSelectBitmapFromFamilyEnum)
#define bitmaplibEntryNumBmpDumpBitmap              	((uint32_t)bitmaplibEntryNumBmpDumpBitmapEnum)
#define bitmaplibEntryNumBmpDumpColortable          	((uint32_t)bitmaplibEntryNumBmpDumpColortableEnum)
#define bitmaplibEntryNumBmpPrvConvertBitmap        	((uint32_t)bitmaplibEntryNumBmpPrvConvertBitmapEnum)
#endif // __BITMAPLIBENTRYNUMS_H__
