/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: BtLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __BTLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __BTLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum btlibEntryNumTag {
	btlibEntryNumBtLibOpenEnum = 0,
	btlibEntryNumBtLibCloseEnum,
	btlibEntryNumBtLibAddrBtdToAEnum,
	btlibEntryNumBtLibAddrAToBtdEnum,
	btlibEntryNumBtLibStartInquiryEnum,
	btlibEntryNumBtLibCancelInquiryEnum,
	btlibEntryNumBtLibGetRemoteDeviceNameEnum,
	btlibEntryNumBtLibLinkConnectEnum,
	btlibEntryNumBtLibLinkDisconnectEnum,
	btlibEntryNumBtLibPiconetCreateEnum,
	btlibEntryNumBtLibPiconetDestroyEnum,
	btlibEntryNumBtLibPiconetUnlockInboundEnum,
	btlibEntryNumBtLibPiconetLockInboundEnum,
	btlibEntryNumBtLibLinkSetStateEnum,
	btlibEntryNumBtLibLinkGetStateEnum,
	btlibEntryNumBtLibSetGeneralPreferenceEnum,
	btlibEntryNumBtLibGetGeneralPreferenceEnum,
	btlibEntryNumBtLibSocketCreateEnum,
	btlibEntryNumBtLibSocketCloseEnum,
	btlibEntryNumBtLibSocketListenEnum,
	btlibEntryNumBtLibSocketConnectEnum,
	btlibEntryNumBtLibSocketRespondToConnectionEnum,
	btlibEntryNumBtLibSocketSendEnum,
	btlibEntryNumBtLibSocketAdvanceCreditEnum,
	btlibEntryNumBtLibSocketGetInfoEnum,
	btlibEntryNumBtLibSdpGetServerChannelByUuidEnum,
	btlibEntryNumBtLibSdpGetPsmByUuidEnum,
	btlibEntryNumBtLibSdpServiceRecordCreateEnum,
	btlibEntryNumBtLibSdpServiceRecordDestroyEnum,
	btlibEntryNumBtLibSdpServiceRecordStartAdvertisingEnum,
	btlibEntryNumBtLibSdpServiceRecordStopAdvertisingEnum,
	btlibEntryNumBtLibSdpServiceRecordSetAttributesForSocketEnum,
	btlibEntryNumBtLibSdpServiceRecordsGetByServiceClassEnum,
	btlibEntryNumBtLibSdpServiceRecordMapRemoteEnum,
	btlibEntryNumBtLibSdpServiceRecordSetAttributeEnum,
	btlibEntryNumBtLibSdpServiceRecordGetAttributeEnum,
	btlibEntryNumBtLibSdpServiceRecordGetStringOrUrlLengthEnum,
	btlibEntryNumBtLibSdpServiceRecordGetNumListEntriesEnum,
	btlibEntryNumBtLibSdpServiceRecordGetNumListsEnum,
	btlibEntryNumBtLibSdpServiceRecordSetRawAttributeEnum,
	btlibEntryNumBtLibSdpServiceRecordGetRawAttributeEnum,
	btlibEntryNumBtLibSdpServiceRecordGetSizeOfRawAttributeEnum,
	btlibEntryNumBtLibSdpCompareUuidsEnum,
	btlibEntryNumBtLibSdpParseRawDataElementEnum,
	btlibEntryNumBtLibSdpVerifyRawDataElementEnum,
	btlibEntryNumBtLibSecurityFindTrustedDeviceRecordEnum,
	btlibEntryNumBtLibSecurityRemoveTrustedDeviceRecordEnum,
	btlibEntryNumBtLibSecurityGetTrustedDeviceRecordInfoEnum,
	btlibEntryNumBtLibSecurityNumTrustedDeviceRecordsEnum,
	btlibEntryNumBtLibMEEventNameEnum,
	btlibEntryNumBtLibSocketEventNameEnum,
	btlibEntryNumBtLibDiscoverDevicesEnum,
	btlibEntryNumBtLibSecurityFindCachedDeviceRecordEnum,
	btlibEntryNumBtLibSecurityGetCachedDeviceRecordInfoEnum,
	btlibEntryNumBtLibSecurityNumCachedDeviceRecordsEnum,
	btlibEntryNumBtLibMakeConnectedSocketEnum,
	btlibEntryNumBtLibRegisterServiceEnum,
	btlibEntryNumBtLibGetRemoteDeviceNameSynchronousEnum,
	btlibEntryNumBtLibFavoritesGetCountEnum,
	btlibEntryNumBtLibFavoritesGetAddressesEnum,
	btlibEntryNumBtLibFavoritesGetDeviceInfoEnum,
	btlibEntryNumBtLibFavoritesAddDeviceEnum,
	btlibEntryNumBtLibFavoritesRemoveDeviceEnum,
	btlibEntryNumBtLibGetMEEventMaskEnum,
	btlibEntryNumBtLibSetMEEventMaskEnum,
	btlibEntryNumBtLibGetCacheNameFromStrAddrEnum,
	btlibEntryNumBtLibGetServiceCountEnum,
	btlibEntryNumBtLibGetServiceInfoTableEnum,
	btlibEntryNumBtLibGetServiceDescriptionEnum,
	btlibEntryNumBtLibEnableServiceEnum,
	btlibEntryNumBtLibGetMainPrefsEnum,
	btlibEntryNumBtLibSetMainPrefsEnum,
	btlibEntryNumBtLibSublaunchAppEnum,
	btlibEntryNumBtLibMakeBNEPConnectedSocketEnum,
	btlibEntryNumBtLibDrawCODIconAtEnum,
	btlibEntryNumBtLibLinkGetSignalStrengthEnum,
	btlibEntryNumBtLibObtainRadioEnum,
};

#define btlibEntryNumBtLibOpen                                   	((uint32_t)btlibEntryNumBtLibOpenEnum)
#define btlibEntryNumBtLibClose                                  	((uint32_t)btlibEntryNumBtLibCloseEnum)
#define btlibEntryNumBtLibAddrBtdToA                             	((uint32_t)btlibEntryNumBtLibAddrBtdToAEnum)
#define btlibEntryNumBtLibAddrAToBtd                             	((uint32_t)btlibEntryNumBtLibAddrAToBtdEnum)
#define btlibEntryNumBtLibStartInquiry                           	((uint32_t)btlibEntryNumBtLibStartInquiryEnum)
#define btlibEntryNumBtLibCancelInquiry                          	((uint32_t)btlibEntryNumBtLibCancelInquiryEnum)
#define btlibEntryNumBtLibGetRemoteDeviceName                    	((uint32_t)btlibEntryNumBtLibGetRemoteDeviceNameEnum)
#define btlibEntryNumBtLibLinkConnect                            	((uint32_t)btlibEntryNumBtLibLinkConnectEnum)
#define btlibEntryNumBtLibLinkDisconnect                         	((uint32_t)btlibEntryNumBtLibLinkDisconnectEnum)
#define btlibEntryNumBtLibPiconetCreate                          	((uint32_t)btlibEntryNumBtLibPiconetCreateEnum)
#define btlibEntryNumBtLibPiconetDestroy                         	((uint32_t)btlibEntryNumBtLibPiconetDestroyEnum)
#define btlibEntryNumBtLibPiconetUnlockInbound                   	((uint32_t)btlibEntryNumBtLibPiconetUnlockInboundEnum)
#define btlibEntryNumBtLibPiconetLockInbound                     	((uint32_t)btlibEntryNumBtLibPiconetLockInboundEnum)
#define btlibEntryNumBtLibLinkSetState                           	((uint32_t)btlibEntryNumBtLibLinkSetStateEnum)
#define btlibEntryNumBtLibLinkGetState                           	((uint32_t)btlibEntryNumBtLibLinkGetStateEnum)
#define btlibEntryNumBtLibSetGeneralPreference                   	((uint32_t)btlibEntryNumBtLibSetGeneralPreferenceEnum)
#define btlibEntryNumBtLibGetGeneralPreference                   	((uint32_t)btlibEntryNumBtLibGetGeneralPreferenceEnum)
#define btlibEntryNumBtLibSocketCreate                           	((uint32_t)btlibEntryNumBtLibSocketCreateEnum)
#define btlibEntryNumBtLibSocketClose                            	((uint32_t)btlibEntryNumBtLibSocketCloseEnum)
#define btlibEntryNumBtLibSocketListen                           	((uint32_t)btlibEntryNumBtLibSocketListenEnum)
#define btlibEntryNumBtLibSocketConnect                          	((uint32_t)btlibEntryNumBtLibSocketConnectEnum)
#define btlibEntryNumBtLibSocketRespondToConnection              	((uint32_t)btlibEntryNumBtLibSocketRespondToConnectionEnum)
#define btlibEntryNumBtLibSocketSend                             	((uint32_t)btlibEntryNumBtLibSocketSendEnum)
#define btlibEntryNumBtLibSocketAdvanceCredit                    	((uint32_t)btlibEntryNumBtLibSocketAdvanceCreditEnum)
#define btlibEntryNumBtLibSocketGetInfo                          	((uint32_t)btlibEntryNumBtLibSocketGetInfoEnum)
#define btlibEntryNumBtLibSdpGetServerChannelByUuid              	((uint32_t)btlibEntryNumBtLibSdpGetServerChannelByUuidEnum)
#define btlibEntryNumBtLibSdpGetPsmByUuid                        	((uint32_t)btlibEntryNumBtLibSdpGetPsmByUuidEnum)
#define btlibEntryNumBtLibSdpServiceRecordCreate                 	((uint32_t)btlibEntryNumBtLibSdpServiceRecordCreateEnum)
#define btlibEntryNumBtLibSdpServiceRecordDestroy                	((uint32_t)btlibEntryNumBtLibSdpServiceRecordDestroyEnum)
#define btlibEntryNumBtLibSdpServiceRecordStartAdvertising       	((uint32_t)btlibEntryNumBtLibSdpServiceRecordStartAdvertisingEnum)
#define btlibEntryNumBtLibSdpServiceRecordStopAdvertising        	((uint32_t)btlibEntryNumBtLibSdpServiceRecordStopAdvertisingEnum)
#define btlibEntryNumBtLibSdpServiceRecordSetAttributesForSocket 	((uint32_t)btlibEntryNumBtLibSdpServiceRecordSetAttributesForSocketEnum)
#define btlibEntryNumBtLibSdpServiceRecordsGetByServiceClass     	((uint32_t)btlibEntryNumBtLibSdpServiceRecordsGetByServiceClassEnum)
#define btlibEntryNumBtLibSdpServiceRecordMapRemote              	((uint32_t)btlibEntryNumBtLibSdpServiceRecordMapRemoteEnum)
#define btlibEntryNumBtLibSdpServiceRecordSetAttribute           	((uint32_t)btlibEntryNumBtLibSdpServiceRecordSetAttributeEnum)
#define btlibEntryNumBtLibSdpServiceRecordGetAttribute           	((uint32_t)btlibEntryNumBtLibSdpServiceRecordGetAttributeEnum)
#define btlibEntryNumBtLibSdpServiceRecordGetStringOrUrlLength   	((uint32_t)btlibEntryNumBtLibSdpServiceRecordGetStringOrUrlLengthEnum)
#define btlibEntryNumBtLibSdpServiceRecordGetNumListEntries      	((uint32_t)btlibEntryNumBtLibSdpServiceRecordGetNumListEntriesEnum)
#define btlibEntryNumBtLibSdpServiceRecordGetNumLists            	((uint32_t)btlibEntryNumBtLibSdpServiceRecordGetNumListsEnum)
#define btlibEntryNumBtLibSdpServiceRecordSetRawAttribute        	((uint32_t)btlibEntryNumBtLibSdpServiceRecordSetRawAttributeEnum)
#define btlibEntryNumBtLibSdpServiceRecordGetRawAttribute        	((uint32_t)btlibEntryNumBtLibSdpServiceRecordGetRawAttributeEnum)
#define btlibEntryNumBtLibSdpServiceRecordGetSizeOfRawAttribute  	((uint32_t)btlibEntryNumBtLibSdpServiceRecordGetSizeOfRawAttributeEnum)
#define btlibEntryNumBtLibSdpCompareUuids                        	((uint32_t)btlibEntryNumBtLibSdpCompareUuidsEnum)
#define btlibEntryNumBtLibSdpParseRawDataElement                 	((uint32_t)btlibEntryNumBtLibSdpParseRawDataElementEnum)
#define btlibEntryNumBtLibSdpVerifyRawDataElement                	((uint32_t)btlibEntryNumBtLibSdpVerifyRawDataElementEnum)
#define btlibEntryNumBtLibSecurityFindTrustedDeviceRecord        	((uint32_t)btlibEntryNumBtLibSecurityFindTrustedDeviceRecordEnum)
#define btlibEntryNumBtLibSecurityRemoveTrustedDeviceRecord      	((uint32_t)btlibEntryNumBtLibSecurityRemoveTrustedDeviceRecordEnum)
#define btlibEntryNumBtLibSecurityGetTrustedDeviceRecordInfo     	((uint32_t)btlibEntryNumBtLibSecurityGetTrustedDeviceRecordInfoEnum)
#define btlibEntryNumBtLibSecurityNumTrustedDeviceRecords        	((uint32_t)btlibEntryNumBtLibSecurityNumTrustedDeviceRecordsEnum)
#define btlibEntryNumBtLibMEEventName                            	((uint32_t)btlibEntryNumBtLibMEEventNameEnum)
#define btlibEntryNumBtLibSocketEventName                        	((uint32_t)btlibEntryNumBtLibSocketEventNameEnum)
#define btlibEntryNumBtLibDiscoverDevices                        	((uint32_t)btlibEntryNumBtLibDiscoverDevicesEnum)
#define btlibEntryNumBtLibSecurityFindCachedDeviceRecord         	((uint32_t)btlibEntryNumBtLibSecurityFindCachedDeviceRecordEnum)
#define btlibEntryNumBtLibSecurityGetCachedDeviceRecordInfo      	((uint32_t)btlibEntryNumBtLibSecurityGetCachedDeviceRecordInfoEnum)
#define btlibEntryNumBtLibSecurityNumCachedDeviceRecords         	((uint32_t)btlibEntryNumBtLibSecurityNumCachedDeviceRecordsEnum)
#define btlibEntryNumBtLibMakeConnectedSocket                    	((uint32_t)btlibEntryNumBtLibMakeConnectedSocketEnum)
#define btlibEntryNumBtLibRegisterService                        	((uint32_t)btlibEntryNumBtLibRegisterServiceEnum)
#define btlibEntryNumBtLibGetRemoteDeviceNameSynchronous         	((uint32_t)btlibEntryNumBtLibGetRemoteDeviceNameSynchronousEnum)
#define btlibEntryNumBtLibFavoritesGetCount                      	((uint32_t)btlibEntryNumBtLibFavoritesGetCountEnum)
#define btlibEntryNumBtLibFavoritesGetAddresses                  	((uint32_t)btlibEntryNumBtLibFavoritesGetAddressesEnum)
#define btlibEntryNumBtLibFavoritesGetDeviceInfo                 	((uint32_t)btlibEntryNumBtLibFavoritesGetDeviceInfoEnum)
#define btlibEntryNumBtLibFavoritesAddDevice                     	((uint32_t)btlibEntryNumBtLibFavoritesAddDeviceEnum)
#define btlibEntryNumBtLibFavoritesRemoveDevice                  	((uint32_t)btlibEntryNumBtLibFavoritesRemoveDeviceEnum)
#define btlibEntryNumBtLibGetMEEventMask                         	((uint32_t)btlibEntryNumBtLibGetMEEventMaskEnum)
#define btlibEntryNumBtLibSetMEEventMask                         	((uint32_t)btlibEntryNumBtLibSetMEEventMaskEnum)
#define btlibEntryNumBtLibGetCacheNameFromStrAddr                	((uint32_t)btlibEntryNumBtLibGetCacheNameFromStrAddrEnum)
#define btlibEntryNumBtLibGetServiceCount                        	((uint32_t)btlibEntryNumBtLibGetServiceCountEnum)
#define btlibEntryNumBtLibGetServiceInfoTable                    	((uint32_t)btlibEntryNumBtLibGetServiceInfoTableEnum)
#define btlibEntryNumBtLibGetServiceDescription                  	((uint32_t)btlibEntryNumBtLibGetServiceDescriptionEnum)
#define btlibEntryNumBtLibEnableService                          	((uint32_t)btlibEntryNumBtLibEnableServiceEnum)
#define btlibEntryNumBtLibGetMainPrefs                           	((uint32_t)btlibEntryNumBtLibGetMainPrefsEnum)
#define btlibEntryNumBtLibSetMainPrefs                           	((uint32_t)btlibEntryNumBtLibSetMainPrefsEnum)
#define btlibEntryNumBtLibSublaunchApp                           	((uint32_t)btlibEntryNumBtLibSublaunchAppEnum)
#define btlibEntryNumBtLibMakeBNEPConnectedSocket                	((uint32_t)btlibEntryNumBtLibMakeBNEPConnectedSocketEnum)
#define btlibEntryNumBtLibDrawCODIconAt                          	((uint32_t)btlibEntryNumBtLibDrawCODIconAtEnum)
#define btlibEntryNumBtLibLinkGetSignalStrength                  	((uint32_t)btlibEntryNumBtLibLinkGetSignalStrengthEnum)
#define btlibEntryNumBtLibObtainRadio                            	((uint32_t)btlibEntryNumBtLibObtainRadioEnum)
#endif // __BTLIBENTRYNUMS_H__
