/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: CatMgrLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __CATMGRLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __CATMGRLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum catmgrlibEntryNumTag {
	catmgrlibEntryNumCategoryFindEnum = 0,
	catmgrlibEntryNumCategoryGetNameEnum,
	catmgrlibEntryNumCategoryGetNextEnum,
	catmgrlibEntryNumCategoryInitializeEnum,
	catmgrlibEntryNumCategorySetNameEnum,
	catmgrlibEntryNumCategoryCreateListEnum,
	catmgrlibEntryNumCategoryFreeListEnum,
	catmgrlibEntryNumCategoryEditEnum,
	catmgrlibEntryNumCategorySelectEnum,
	catmgrlibEntryNumCategorySetTriggerLabelEnum,
	catmgrlibEntryNumCategoryTruncateNameEnum,
	catmgrlibEntryNumCategoryCreateListV50Enum,
	catmgrlibEntryNumCategoryEditV50Enum,
	catmgrlibEntryNumCategorySelectV50Enum,
	catmgrlibEntryNumCategoryInitializeV50Enum,
	catmgrlibEntryNumCatMgrAddEnum,
	catmgrlibEntryNumCatMgrRemoveEnum,
	catmgrlibEntryNumCatMgrFindEnum,
	catmgrlibEntryNumCatMgrNumCategoriesEnum,
	catmgrlibEntryNumCatMgrGetEditableEnum,
	catmgrlibEntryNumCatMgrSetEditableEnum,
	catmgrlibEntryNumCatMgrGetNameEnum,
	catmgrlibEntryNumCatMgrGetUnfiledItemLabelEnum,
	catmgrlibEntryNumCatMgrGetAllItemLabelEnum,
	catmgrlibEntryNumCatMgrSetNameEnum,
	catmgrlibEntryNumCatMgrGetIDEnum,
	catmgrlibEntryNumCatMgrGetNextEnum,
	catmgrlibEntryNumCatMgrSyncGetModifiedCategoriesEnum,
	catmgrlibEntryNumCatMgrSyncGetPurgeCounterEnum,
	catmgrlibEntryNumCatMgrSyncReleaseStorageEnum,
	catmgrlibEntryNumCatMgrInitializeEnum,
	catmgrlibEntryNumCatMgrSelectFilterEnum,
	catmgrlibEntryNumCatMgrSelectEditEnum,
	catmgrlibEntryNumCatMgrCreateListEnum,
	catmgrlibEntryNumCatMgrEditEnum,
	catmgrlibEntryNumCatMgrFreeListEnum,
	catmgrlibEntryNumCatMgrTruncateNameEnum,
	catmgrlibEntryNumCatMgrSetTriggerLabelEnum,
	catmgrlibEntryNumCatMgrFreeSelectedCategoriesEnum,
};

#define catmgrlibEntryNumCategoryFind                    	((uint32_t)catmgrlibEntryNumCategoryFindEnum)
#define catmgrlibEntryNumCategoryGetName                 	((uint32_t)catmgrlibEntryNumCategoryGetNameEnum)
#define catmgrlibEntryNumCategoryGetNext                 	((uint32_t)catmgrlibEntryNumCategoryGetNextEnum)
#define catmgrlibEntryNumCategoryInitialize              	((uint32_t)catmgrlibEntryNumCategoryInitializeEnum)
#define catmgrlibEntryNumCategorySetName                 	((uint32_t)catmgrlibEntryNumCategorySetNameEnum)
#define catmgrlibEntryNumCategoryCreateList              	((uint32_t)catmgrlibEntryNumCategoryCreateListEnum)
#define catmgrlibEntryNumCategoryFreeList                	((uint32_t)catmgrlibEntryNumCategoryFreeListEnum)
#define catmgrlibEntryNumCategoryEdit                    	((uint32_t)catmgrlibEntryNumCategoryEditEnum)
#define catmgrlibEntryNumCategorySelect                  	((uint32_t)catmgrlibEntryNumCategorySelectEnum)
#define catmgrlibEntryNumCategorySetTriggerLabel         	((uint32_t)catmgrlibEntryNumCategorySetTriggerLabelEnum)
#define catmgrlibEntryNumCategoryTruncateName            	((uint32_t)catmgrlibEntryNumCategoryTruncateNameEnum)
#define catmgrlibEntryNumCategoryCreateListV50           	((uint32_t)catmgrlibEntryNumCategoryCreateListV50Enum)
#define catmgrlibEntryNumCategoryEditV50                 	((uint32_t)catmgrlibEntryNumCategoryEditV50Enum)
#define catmgrlibEntryNumCategorySelectV50               	((uint32_t)catmgrlibEntryNumCategorySelectV50Enum)
#define catmgrlibEntryNumCategoryInitializeV50           	((uint32_t)catmgrlibEntryNumCategoryInitializeV50Enum)
#define catmgrlibEntryNumCatMgrAdd                       	((uint32_t)catmgrlibEntryNumCatMgrAddEnum)
#define catmgrlibEntryNumCatMgrRemove                    	((uint32_t)catmgrlibEntryNumCatMgrRemoveEnum)
#define catmgrlibEntryNumCatMgrFind                      	((uint32_t)catmgrlibEntryNumCatMgrFindEnum)
#define catmgrlibEntryNumCatMgrNumCategories             	((uint32_t)catmgrlibEntryNumCatMgrNumCategoriesEnum)
#define catmgrlibEntryNumCatMgrGetEditable               	((uint32_t)catmgrlibEntryNumCatMgrGetEditableEnum)
#define catmgrlibEntryNumCatMgrSetEditable               	((uint32_t)catmgrlibEntryNumCatMgrSetEditableEnum)
#define catmgrlibEntryNumCatMgrGetName                   	((uint32_t)catmgrlibEntryNumCatMgrGetNameEnum)
#define catmgrlibEntryNumCatMgrGetUnfiledItemLabel       	((uint32_t)catmgrlibEntryNumCatMgrGetUnfiledItemLabelEnum)
#define catmgrlibEntryNumCatMgrGetAllItemLabel           	((uint32_t)catmgrlibEntryNumCatMgrGetAllItemLabelEnum)
#define catmgrlibEntryNumCatMgrSetName                   	((uint32_t)catmgrlibEntryNumCatMgrSetNameEnum)
#define catmgrlibEntryNumCatMgrGetID                     	((uint32_t)catmgrlibEntryNumCatMgrGetIDEnum)
#define catmgrlibEntryNumCatMgrGetNext                   	((uint32_t)catmgrlibEntryNumCatMgrGetNextEnum)
#define catmgrlibEntryNumCatMgrSyncGetModifiedCategories 	((uint32_t)catmgrlibEntryNumCatMgrSyncGetModifiedCategoriesEnum)
#define catmgrlibEntryNumCatMgrSyncGetPurgeCounter       	((uint32_t)catmgrlibEntryNumCatMgrSyncGetPurgeCounterEnum)
#define catmgrlibEntryNumCatMgrSyncReleaseStorage        	((uint32_t)catmgrlibEntryNumCatMgrSyncReleaseStorageEnum)
#define catmgrlibEntryNumCatMgrInitialize                	((uint32_t)catmgrlibEntryNumCatMgrInitializeEnum)
#define catmgrlibEntryNumCatMgrSelectFilter              	((uint32_t)catmgrlibEntryNumCatMgrSelectFilterEnum)
#define catmgrlibEntryNumCatMgrSelectEdit                	((uint32_t)catmgrlibEntryNumCatMgrSelectEditEnum)
#define catmgrlibEntryNumCatMgrCreateList                	((uint32_t)catmgrlibEntryNumCatMgrCreateListEnum)
#define catmgrlibEntryNumCatMgrEdit                      	((uint32_t)catmgrlibEntryNumCatMgrEditEnum)
#define catmgrlibEntryNumCatMgrFreeList                  	((uint32_t)catmgrlibEntryNumCatMgrFreeListEnum)
#define catmgrlibEntryNumCatMgrTruncateName              	((uint32_t)catmgrlibEntryNumCatMgrTruncateNameEnum)
#define catmgrlibEntryNumCatMgrSetTriggerLabel           	((uint32_t)catmgrlibEntryNumCatMgrSetTriggerLabelEnum)
#define catmgrlibEntryNumCatMgrFreeSelectedCategories    	((uint32_t)catmgrlibEntryNumCatMgrFreeSelectedCategoriesEnum)
#endif // __CATMGRLIBENTRYNUMS_H__
