/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: CertMgrEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __CERTMGRENTRYNUMS_H__	// Avoid multiple inclusion
#define __CERTMGRENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum certmgrEntryNumTag {
	certmgrEntryNumCertMgrImportCertEnum = 0,
	certmgrEntryNumCertMgrExportCertEnum,
	certmgrEntryNumCertMgrReleaseCertInfoEnum,
	certmgrEntryNumCertMgrGetFieldEnum,
	certmgrEntryNumCertMgrVerifyCertEnum,
	certmgrEntryNumCertMgrAddCertEnum,
	certmgrEntryNumCertMgrRemoveCertEnum,
	certmgrEntryNumCertMgrFindCertEnum,
	certmgrEntryNumCertMgrSameProcEnum,
};

#define certmgrEntryNumCertMgrImportCert     	((uint32_t)certmgrEntryNumCertMgrImportCertEnum)
#define certmgrEntryNumCertMgrExportCert     	((uint32_t)certmgrEntryNumCertMgrExportCertEnum)
#define certmgrEntryNumCertMgrReleaseCertInfo	((uint32_t)certmgrEntryNumCertMgrReleaseCertInfoEnum)
#define certmgrEntryNumCertMgrGetField       	((uint32_t)certmgrEntryNumCertMgrGetFieldEnum)
#define certmgrEntryNumCertMgrVerifyCert     	((uint32_t)certmgrEntryNumCertMgrVerifyCertEnum)
#define certmgrEntryNumCertMgrAddCert        	((uint32_t)certmgrEntryNumCertMgrAddCertEnum)
#define certmgrEntryNumCertMgrRemoveCert     	((uint32_t)certmgrEntryNumCertMgrRemoveCertEnum)
#define certmgrEntryNumCertMgrFindCert       	((uint32_t)certmgrEntryNumCertMgrFindCertEnum)
#define certmgrEntryNumCertMgrSameProc       	((uint32_t)certmgrEntryNumCertMgrSameProcEnum)
#endif // __CERTMGRENTRYNUMS_H__
