/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: CncClientLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __CNCCLIENTLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __CNCCLIENTLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum cncclientlibEntryNumTag {
	cncclientlibEntryNumCncGetOrOpenSessionEnum = 0,
	cncclientlibEntryNumCncGetSessionEnum,
	cncclientlibEntryNumCncCloseSessionEnum,
	cncclientlibEntryNumCncRegisterNotifyEnum,
	cncclientlibEntryNumCncRegisterPluginModuleEnum,
	cncclientlibEntryNumCncInterfaceNewEnum,
	cncclientlibEntryNumCncEdgeNewEnum,
	cncclientlibEntryNumCncEdgeDeleteEnum,
	cncclientlibEntryNumCncObjectDeleteEnum,
	cncclientlibEntryNumCncObjectGetIndexEnum,
	cncclientlibEntryNumCncProfileConnectEnum,
	cncclientlibEntryNumCncConnectReceiveStateEnum,
	cncclientlibEntryNumCncProfileDisconnectEnum,
	cncclientlibEntryNumCncProfileDeleteItemEnum,
	cncclientlibEntryNumCncProfileGetParametersEnum,
	cncclientlibEntryNumCncProfileSetParametersEnum,
	cncclientlibEntryNumCncProfileInsertItemEnum,
	cncclientlibEntryNumCncProfileGetLengthEnum,
	cncclientlibEntryNumCncProfileGetItemIndexEnum,
	cncclientlibEntryNumCncProfileGetItemIdEnum,
	cncclientlibEntryNumCncProfileLockEnum,
	cncclientlibEntryNumCncProfileUnlockEnum,
	cncclientlibEntryNumCncProfileSubmitEnum,
	cncclientlibEntryNumCncProfileNewEnum,
	cncclientlibEntryNumCncObjectGetInfoEnum,
	cncclientlibEntryNumCncObjectSetInfoEnum,
	cncclientlibEntryNumCncProfileDecodeEnum,
	cncclientlibEntryNumCncProfileEncodeEnum,
	cncclientlibEntryNumCncProfileFindNextEnum,
	cncclientlibEntryNumCncProfileFindFirstEnum,
	cncclientlibEntryNumCncProfileFindCloseEnum,
	cncclientlibEntryNumCncProfileEditEnum,
	cncclientlibEntryNumCncProfileFindConnectEnum,
	cncclientlibEntryNumCncProfileAttachEnum,
	cncclientlibEntryNumCncParametersInitEnum,
	cncclientlibEntryNumCncParametersFreeEnum,
	cncclientlibEntryNumCncProfileCopyEnum,
	cncclientlibEntryNumCncProfileUngroupEnum,
	cncclientlibEntryNumCncProfileRegroupSubmitEnum,
	cncclientlibEntryNumCncObjectMoveItemEnum,
	cncclientlibEntryNumCncSubProfileAssignEnum,
	cncclientlibEntryNumCncObjectFindAllEnum,
	cncclientlibEntryNumCncObjectControlEnum,
	cncclientlibEntryNumCncObjectGetDependenciesEnum,
	cncclientlibEntryNumCncDoUniqueNameEnum,
	cncclientlibEntryNumCncPluginRunFormEnum,
	cncclientlibEntryNumCncPluginLoadFormEnum,
	cncclientlibEntryNumCncPluginRegisterFormEnum,
	cncclientlibEntryNumCncPluginHandleEventEnum,
	cncclientlibEntryNumCncPluginUnloadAllFormsEnum,
	cncclientlibEntryNumPrvServerRPCEnum,
	cncclientlibEntryNumCncProfileSettingGetV50Enum,
	cncclientlibEntryNumCncProfileSettingSetV50Enum,
	cncclientlibEntryNumCncProfileSetCurrentV50Enum,
	cncclientlibEntryNumCncProfileGetCurrentV50Enum,
	cncclientlibEntryNumCncProfileGetIDFromNameV50Enum,
	cncclientlibEntryNumCncProfileCreateV50Enum,
	cncclientlibEntryNumCncProfileDeleteV50Enum,
	cncclientlibEntryNumCncProfileGetIDFromIndexV50Enum,
	cncclientlibEntryNumCncProfileGetIndexV50Enum,
	cncclientlibEntryNumCncProfileCountV50Enum,
	cncclientlibEntryNumCncProfileOpenDBV50Enum,
	cncclientlibEntryNumCncProfileCloseDBV50Enum,
	cncclientlibEntryNumCncGetProfileListV50Enum,
	cncclientlibEntryNumCncGetProfileInfoV50Enum,
	cncclientlibEntryNumCncAddProfileV50Enum,
	cncclientlibEntryNumCncDeleteProfileV50Enum,
};

#define cncclientlibEntryNumCncGetOrOpenSession         	((uint32_t)cncclientlibEntryNumCncGetOrOpenSessionEnum)
#define cncclientlibEntryNumCncGetSession               	((uint32_t)cncclientlibEntryNumCncGetSessionEnum)
#define cncclientlibEntryNumCncCloseSession             	((uint32_t)cncclientlibEntryNumCncCloseSessionEnum)
#define cncclientlibEntryNumCncRegisterNotify           	((uint32_t)cncclientlibEntryNumCncRegisterNotifyEnum)
#define cncclientlibEntryNumCncRegisterPluginModule     	((uint32_t)cncclientlibEntryNumCncRegisterPluginModuleEnum)
#define cncclientlibEntryNumCncInterfaceNew             	((uint32_t)cncclientlibEntryNumCncInterfaceNewEnum)
#define cncclientlibEntryNumCncEdgeNew                  	((uint32_t)cncclientlibEntryNumCncEdgeNewEnum)
#define cncclientlibEntryNumCncEdgeDelete               	((uint32_t)cncclientlibEntryNumCncEdgeDeleteEnum)
#define cncclientlibEntryNumCncObjectDelete             	((uint32_t)cncclientlibEntryNumCncObjectDeleteEnum)
#define cncclientlibEntryNumCncObjectGetIndex           	((uint32_t)cncclientlibEntryNumCncObjectGetIndexEnum)
#define cncclientlibEntryNumCncProfileConnect           	((uint32_t)cncclientlibEntryNumCncProfileConnectEnum)
#define cncclientlibEntryNumCncConnectReceiveState      	((uint32_t)cncclientlibEntryNumCncConnectReceiveStateEnum)
#define cncclientlibEntryNumCncProfileDisconnect        	((uint32_t)cncclientlibEntryNumCncProfileDisconnectEnum)
#define cncclientlibEntryNumCncProfileDeleteItem        	((uint32_t)cncclientlibEntryNumCncProfileDeleteItemEnum)
#define cncclientlibEntryNumCncProfileGetParameters     	((uint32_t)cncclientlibEntryNumCncProfileGetParametersEnum)
#define cncclientlibEntryNumCncProfileSetParameters     	((uint32_t)cncclientlibEntryNumCncProfileSetParametersEnum)
#define cncclientlibEntryNumCncProfileInsertItem        	((uint32_t)cncclientlibEntryNumCncProfileInsertItemEnum)
#define cncclientlibEntryNumCncProfileGetLength         	((uint32_t)cncclientlibEntryNumCncProfileGetLengthEnum)
#define cncclientlibEntryNumCncProfileGetItemIndex      	((uint32_t)cncclientlibEntryNumCncProfileGetItemIndexEnum)
#define cncclientlibEntryNumCncProfileGetItemId         	((uint32_t)cncclientlibEntryNumCncProfileGetItemIdEnum)
#define cncclientlibEntryNumCncProfileLock              	((uint32_t)cncclientlibEntryNumCncProfileLockEnum)
#define cncclientlibEntryNumCncProfileUnlock            	((uint32_t)cncclientlibEntryNumCncProfileUnlockEnum)
#define cncclientlibEntryNumCncProfileSubmit            	((uint32_t)cncclientlibEntryNumCncProfileSubmitEnum)
#define cncclientlibEntryNumCncProfileNew               	((uint32_t)cncclientlibEntryNumCncProfileNewEnum)
#define cncclientlibEntryNumCncObjectGetInfo            	((uint32_t)cncclientlibEntryNumCncObjectGetInfoEnum)
#define cncclientlibEntryNumCncObjectSetInfo            	((uint32_t)cncclientlibEntryNumCncObjectSetInfoEnum)
#define cncclientlibEntryNumCncProfileDecode            	((uint32_t)cncclientlibEntryNumCncProfileDecodeEnum)
#define cncclientlibEntryNumCncProfileEncode            	((uint32_t)cncclientlibEntryNumCncProfileEncodeEnum)
#define cncclientlibEntryNumCncProfileFindNext          	((uint32_t)cncclientlibEntryNumCncProfileFindNextEnum)
#define cncclientlibEntryNumCncProfileFindFirst         	((uint32_t)cncclientlibEntryNumCncProfileFindFirstEnum)
#define cncclientlibEntryNumCncProfileFindClose         	((uint32_t)cncclientlibEntryNumCncProfileFindCloseEnum)
#define cncclientlibEntryNumCncProfileEdit              	((uint32_t)cncclientlibEntryNumCncProfileEditEnum)
#define cncclientlibEntryNumCncProfileFindConnect       	((uint32_t)cncclientlibEntryNumCncProfileFindConnectEnum)
#define cncclientlibEntryNumCncProfileAttach            	((uint32_t)cncclientlibEntryNumCncProfileAttachEnum)
#define cncclientlibEntryNumCncParametersInit           	((uint32_t)cncclientlibEntryNumCncParametersInitEnum)
#define cncclientlibEntryNumCncParametersFree           	((uint32_t)cncclientlibEntryNumCncParametersFreeEnum)
#define cncclientlibEntryNumCncProfileCopy              	((uint32_t)cncclientlibEntryNumCncProfileCopyEnum)
#define cncclientlibEntryNumCncProfileUngroup           	((uint32_t)cncclientlibEntryNumCncProfileUngroupEnum)
#define cncclientlibEntryNumCncProfileRegroupSubmit     	((uint32_t)cncclientlibEntryNumCncProfileRegroupSubmitEnum)
#define cncclientlibEntryNumCncObjectMoveItem           	((uint32_t)cncclientlibEntryNumCncObjectMoveItemEnum)
#define cncclientlibEntryNumCncSubProfileAssign         	((uint32_t)cncclientlibEntryNumCncSubProfileAssignEnum)
#define cncclientlibEntryNumCncObjectFindAll            	((uint32_t)cncclientlibEntryNumCncObjectFindAllEnum)
#define cncclientlibEntryNumCncObjectControl            	((uint32_t)cncclientlibEntryNumCncObjectControlEnum)
#define cncclientlibEntryNumCncObjectGetDependencies    	((uint32_t)cncclientlibEntryNumCncObjectGetDependenciesEnum)
#define cncclientlibEntryNumCncDoUniqueName             	((uint32_t)cncclientlibEntryNumCncDoUniqueNameEnum)
#define cncclientlibEntryNumCncPluginRunForm            	((uint32_t)cncclientlibEntryNumCncPluginRunFormEnum)
#define cncclientlibEntryNumCncPluginLoadForm           	((uint32_t)cncclientlibEntryNumCncPluginLoadFormEnum)
#define cncclientlibEntryNumCncPluginRegisterForm       	((uint32_t)cncclientlibEntryNumCncPluginRegisterFormEnum)
#define cncclientlibEntryNumCncPluginHandleEvent        	((uint32_t)cncclientlibEntryNumCncPluginHandleEventEnum)
#define cncclientlibEntryNumCncPluginUnloadAllForms     	((uint32_t)cncclientlibEntryNumCncPluginUnloadAllFormsEnum)
#define cncclientlibEntryNumPrvServerRPC                	((uint32_t)cncclientlibEntryNumPrvServerRPCEnum)
#define cncclientlibEntryNumCncProfileSettingGetV50     	((uint32_t)cncclientlibEntryNumCncProfileSettingGetV50Enum)
#define cncclientlibEntryNumCncProfileSettingSetV50     	((uint32_t)cncclientlibEntryNumCncProfileSettingSetV50Enum)
#define cncclientlibEntryNumCncProfileSetCurrentV50     	((uint32_t)cncclientlibEntryNumCncProfileSetCurrentV50Enum)
#define cncclientlibEntryNumCncProfileGetCurrentV50     	((uint32_t)cncclientlibEntryNumCncProfileGetCurrentV50Enum)
#define cncclientlibEntryNumCncProfileGetIDFromNameV50  	((uint32_t)cncclientlibEntryNumCncProfileGetIDFromNameV50Enum)
#define cncclientlibEntryNumCncProfileCreateV50         	((uint32_t)cncclientlibEntryNumCncProfileCreateV50Enum)
#define cncclientlibEntryNumCncProfileDeleteV50         	((uint32_t)cncclientlibEntryNumCncProfileDeleteV50Enum)
#define cncclientlibEntryNumCncProfileGetIDFromIndexV50 	((uint32_t)cncclientlibEntryNumCncProfileGetIDFromIndexV50Enum)
#define cncclientlibEntryNumCncProfileGetIndexV50       	((uint32_t)cncclientlibEntryNumCncProfileGetIndexV50Enum)
#define cncclientlibEntryNumCncProfileCountV50          	((uint32_t)cncclientlibEntryNumCncProfileCountV50Enum)
#define cncclientlibEntryNumCncProfileOpenDBV50         	((uint32_t)cncclientlibEntryNumCncProfileOpenDBV50Enum)
#define cncclientlibEntryNumCncProfileCloseDBV50        	((uint32_t)cncclientlibEntryNumCncProfileCloseDBV50Enum)
#define cncclientlibEntryNumCncGetProfileListV50        	((uint32_t)cncclientlibEntryNumCncGetProfileListV50Enum)
#define cncclientlibEntryNumCncGetProfileInfoV50        	((uint32_t)cncclientlibEntryNumCncGetProfileInfoV50Enum)
#define cncclientlibEntryNumCncAddProfileV50            	((uint32_t)cncclientlibEntryNumCncAddProfileV50Enum)
#define cncclientlibEntryNumCncDeleteProfileV50         	((uint32_t)cncclientlibEntryNumCncDeleteProfileV50Enum)
#endif // __CNCCLIENTLIBENTRYNUMS_H__
