/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: CPMLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __CPMLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __CPMLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum cpmlibEntryNumTag {
	cpmlibEntryNumCPMLibOpenEnum = 0,
	cpmlibEntryNumCPMLibCloseEnum,
	cpmlibEntryNumCPMLibSleepEnum,
	cpmlibEntryNumCPMLibWakeEnum,
	cpmlibEntryNumCPMLibGetInfoEnum,
	cpmlibEntryNumCPMLibSetDebugLevelEnum,
	cpmlibEntryNumCPMLibEnumerateProvidersEnum,
	cpmlibEntryNumCPMLibGetProviderInfoEnum,
	cpmlibEntryNumCPMLibSetDefaultProviderEnum,
	cpmlibEntryNumCPMLibGenerateRandomBytesEnum,
	cpmlibEntryNumCPMLibAddRandomSeedEnum,
	cpmlibEntryNumCPMLibGenerateKeyEnum,
	cpmlibEntryNumCPMLibImportKeyInfoEnum,
	cpmlibEntryNumCPMLibExportKeyInfoEnum,
	cpmlibEntryNumCPMLibReleaseKeyInfoEnum,
	cpmlibEntryNumCPMLibGenerateKeyPairEnum,
	cpmlibEntryNumCPMLibImportKeyPairInfoEnum,
	cpmlibEntryNumCPMLibExportKeyPairInfoEnum,
	cpmlibEntryNumCPMLibDeriveKeyDataEnum,
	cpmlibEntryNumCPMLibHashInitEnum,
	cpmlibEntryNumCPMLibHashUpdateEnum,
	cpmlibEntryNumCPMLibHashFinalEnum,
	cpmlibEntryNumCPMLibHashEnum,
	cpmlibEntryNumCPMLibImportHashInfoEnum,
	cpmlibEntryNumCPMLibExportHashInfoEnum,
	cpmlibEntryNumCPMLibReleaseHashInfoEnum,
	cpmlibEntryNumCPMLibMACInitEnum,
	cpmlibEntryNumCPMLibMACUpdateEnum,
	cpmlibEntryNumCPMLibMACFinalEnum,
	cpmlibEntryNumCPMLibMACEnum,
	cpmlibEntryNumCPMLibImportMACInfoEnum,
	cpmlibEntryNumCPMLibExportMACInfoEnum,
	cpmlibEntryNumCPMLibReleaseMACInfoEnum,
	cpmlibEntryNumCPMLibEncryptInitEnum,
	cpmlibEntryNumCPMLibEncryptUpdateEnum,
	cpmlibEntryNumCPMLibEncryptFinalEnum,
	cpmlibEntryNumCPMLibEncryptEnum,
	cpmlibEntryNumCPMLibDecryptInitEnum,
	cpmlibEntryNumCPMLibDecryptUpdateEnum,
	cpmlibEntryNumCPMLibDecryptFinalEnum,
	cpmlibEntryNumCPMLibDecryptEnum,
	cpmlibEntryNumCPMLibImportCipherInfoEnum,
	cpmlibEntryNumCPMLibExportCipherInfoEnum,
	cpmlibEntryNumCPMLibReleaseCipherInfoEnum,
	cpmlibEntryNumCPMLibSignInitEnum,
	cpmlibEntryNumCPMLibSignUpdateEnum,
	cpmlibEntryNumCPMLibSignFinalEnum,
	cpmlibEntryNumCPMLibSignEnum,
	cpmlibEntryNumCPMLibImportSignInfoEnum,
	cpmlibEntryNumCPMLibExportSignInfoEnum,
	cpmlibEntryNumCPMLibReleaseSignInfoEnum,
	cpmlibEntryNumCPMLibVerifyInitEnum,
	cpmlibEntryNumCPMLibVerifyUpdateEnum,
	cpmlibEntryNumCPMLibVerifyFinalEnum,
	cpmlibEntryNumCPMLibVerifyEnum,
	cpmlibEntryNumCPMLibImportVerifyInfoEnum,
	cpmlibEntryNumCPMLibExportVerifyInfoEnum,
	cpmlibEntryNumCPMLibReleaseVerifyInfoEnum,
};

#define cpmlibEntryNumCPMLibOpen                	((uint32_t)cpmlibEntryNumCPMLibOpenEnum)
#define cpmlibEntryNumCPMLibClose               	((uint32_t)cpmlibEntryNumCPMLibCloseEnum)
#define cpmlibEntryNumCPMLibSleep               	((uint32_t)cpmlibEntryNumCPMLibSleepEnum)
#define cpmlibEntryNumCPMLibWake                	((uint32_t)cpmlibEntryNumCPMLibWakeEnum)
#define cpmlibEntryNumCPMLibGetInfo             	((uint32_t)cpmlibEntryNumCPMLibGetInfoEnum)
#define cpmlibEntryNumCPMLibSetDebugLevel       	((uint32_t)cpmlibEntryNumCPMLibSetDebugLevelEnum)
#define cpmlibEntryNumCPMLibEnumerateProviders  	((uint32_t)cpmlibEntryNumCPMLibEnumerateProvidersEnum)
#define cpmlibEntryNumCPMLibGetProviderInfo     	((uint32_t)cpmlibEntryNumCPMLibGetProviderInfoEnum)
#define cpmlibEntryNumCPMLibSetDefaultProvider  	((uint32_t)cpmlibEntryNumCPMLibSetDefaultProviderEnum)
#define cpmlibEntryNumCPMLibGenerateRandomBytes 	((uint32_t)cpmlibEntryNumCPMLibGenerateRandomBytesEnum)
#define cpmlibEntryNumCPMLibAddRandomSeed       	((uint32_t)cpmlibEntryNumCPMLibAddRandomSeedEnum)
#define cpmlibEntryNumCPMLibGenerateKey         	((uint32_t)cpmlibEntryNumCPMLibGenerateKeyEnum)
#define cpmlibEntryNumCPMLibImportKeyInfo       	((uint32_t)cpmlibEntryNumCPMLibImportKeyInfoEnum)
#define cpmlibEntryNumCPMLibExportKeyInfo       	((uint32_t)cpmlibEntryNumCPMLibExportKeyInfoEnum)
#define cpmlibEntryNumCPMLibReleaseKeyInfo      	((uint32_t)cpmlibEntryNumCPMLibReleaseKeyInfoEnum)
#define cpmlibEntryNumCPMLibGenerateKeyPair     	((uint32_t)cpmlibEntryNumCPMLibGenerateKeyPairEnum)
#define cpmlibEntryNumCPMLibImportKeyPairInfo   	((uint32_t)cpmlibEntryNumCPMLibImportKeyPairInfoEnum)
#define cpmlibEntryNumCPMLibExportKeyPairInfo   	((uint32_t)cpmlibEntryNumCPMLibExportKeyPairInfoEnum)
#define cpmlibEntryNumCPMLibDeriveKeyData       	((uint32_t)cpmlibEntryNumCPMLibDeriveKeyDataEnum)
#define cpmlibEntryNumCPMLibHashInit            	((uint32_t)cpmlibEntryNumCPMLibHashInitEnum)
#define cpmlibEntryNumCPMLibHashUpdate          	((uint32_t)cpmlibEntryNumCPMLibHashUpdateEnum)
#define cpmlibEntryNumCPMLibHashFinal           	((uint32_t)cpmlibEntryNumCPMLibHashFinalEnum)
#define cpmlibEntryNumCPMLibHash                	((uint32_t)cpmlibEntryNumCPMLibHashEnum)
#define cpmlibEntryNumCPMLibImportHashInfo      	((uint32_t)cpmlibEntryNumCPMLibImportHashInfoEnum)
#define cpmlibEntryNumCPMLibExportHashInfo      	((uint32_t)cpmlibEntryNumCPMLibExportHashInfoEnum)
#define cpmlibEntryNumCPMLibReleaseHashInfo     	((uint32_t)cpmlibEntryNumCPMLibReleaseHashInfoEnum)
#define cpmlibEntryNumCPMLibMACInit             	((uint32_t)cpmlibEntryNumCPMLibMACInitEnum)
#define cpmlibEntryNumCPMLibMACUpdate           	((uint32_t)cpmlibEntryNumCPMLibMACUpdateEnum)
#define cpmlibEntryNumCPMLibMACFinal            	((uint32_t)cpmlibEntryNumCPMLibMACFinalEnum)
#define cpmlibEntryNumCPMLibMAC                 	((uint32_t)cpmlibEntryNumCPMLibMACEnum)
#define cpmlibEntryNumCPMLibImportMACInfo       	((uint32_t)cpmlibEntryNumCPMLibImportMACInfoEnum)
#define cpmlibEntryNumCPMLibExportMACInfo       	((uint32_t)cpmlibEntryNumCPMLibExportMACInfoEnum)
#define cpmlibEntryNumCPMLibReleaseMACInfo      	((uint32_t)cpmlibEntryNumCPMLibReleaseMACInfoEnum)
#define cpmlibEntryNumCPMLibEncryptInit         	((uint32_t)cpmlibEntryNumCPMLibEncryptInitEnum)
#define cpmlibEntryNumCPMLibEncryptUpdate       	((uint32_t)cpmlibEntryNumCPMLibEncryptUpdateEnum)
#define cpmlibEntryNumCPMLibEncryptFinal        	((uint32_t)cpmlibEntryNumCPMLibEncryptFinalEnum)
#define cpmlibEntryNumCPMLibEncrypt             	((uint32_t)cpmlibEntryNumCPMLibEncryptEnum)
#define cpmlibEntryNumCPMLibDecryptInit         	((uint32_t)cpmlibEntryNumCPMLibDecryptInitEnum)
#define cpmlibEntryNumCPMLibDecryptUpdate       	((uint32_t)cpmlibEntryNumCPMLibDecryptUpdateEnum)
#define cpmlibEntryNumCPMLibDecryptFinal        	((uint32_t)cpmlibEntryNumCPMLibDecryptFinalEnum)
#define cpmlibEntryNumCPMLibDecrypt             	((uint32_t)cpmlibEntryNumCPMLibDecryptEnum)
#define cpmlibEntryNumCPMLibImportCipherInfo    	((uint32_t)cpmlibEntryNumCPMLibImportCipherInfoEnum)
#define cpmlibEntryNumCPMLibExportCipherInfo    	((uint32_t)cpmlibEntryNumCPMLibExportCipherInfoEnum)
#define cpmlibEntryNumCPMLibReleaseCipherInfo   	((uint32_t)cpmlibEntryNumCPMLibReleaseCipherInfoEnum)
#define cpmlibEntryNumCPMLibSignInit            	((uint32_t)cpmlibEntryNumCPMLibSignInitEnum)
#define cpmlibEntryNumCPMLibSignUpdate          	((uint32_t)cpmlibEntryNumCPMLibSignUpdateEnum)
#define cpmlibEntryNumCPMLibSignFinal           	((uint32_t)cpmlibEntryNumCPMLibSignFinalEnum)
#define cpmlibEntryNumCPMLibSign                	((uint32_t)cpmlibEntryNumCPMLibSignEnum)
#define cpmlibEntryNumCPMLibImportSignInfo      	((uint32_t)cpmlibEntryNumCPMLibImportSignInfoEnum)
#define cpmlibEntryNumCPMLibExportSignInfo      	((uint32_t)cpmlibEntryNumCPMLibExportSignInfoEnum)
#define cpmlibEntryNumCPMLibReleaseSignInfo     	((uint32_t)cpmlibEntryNumCPMLibReleaseSignInfoEnum)
#define cpmlibEntryNumCPMLibVerifyInit          	((uint32_t)cpmlibEntryNumCPMLibVerifyInitEnum)
#define cpmlibEntryNumCPMLibVerifyUpdate        	((uint32_t)cpmlibEntryNumCPMLibVerifyUpdateEnum)
#define cpmlibEntryNumCPMLibVerifyFinal         	((uint32_t)cpmlibEntryNumCPMLibVerifyFinalEnum)
#define cpmlibEntryNumCPMLibVerify              	((uint32_t)cpmlibEntryNumCPMLibVerifyEnum)
#define cpmlibEntryNumCPMLibImportVerifyInfo    	((uint32_t)cpmlibEntryNumCPMLibImportVerifyInfoEnum)
#define cpmlibEntryNumCPMLibExportVerifyInfo    	((uint32_t)cpmlibEntryNumCPMLibExportVerifyInfoEnum)
#define cpmlibEntryNumCPMLibReleaseVerifyInfo   	((uint32_t)cpmlibEntryNumCPMLibReleaseVerifyInfoEnum)
#endif // __CPMLIBENTRYNUMS_H__
