/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: DLServerEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __DLSERVERENTRYNUMS_H__	// Avoid multiple inclusion
#define __DLSERVERENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum dlserverEntryNumTag {
	dlserverEntryNumDlkStartServerEnum = 0,
	dlserverEntryNumDlkGetSyncInfoEnum,
	dlserverEntryNumDlkSetLogEntryEnum,
	dlserverEntryNumDlkDispatchRequestEnum,
	dlserverEntryNumDlkControlEnum,
	dlserverEntryNumHSUtilReverseWordEnum,
	dlserverEntryNumHSUtilReverseDWordEnum,
	dlserverEntryNumDlkTrustDoQueryEnum,
	dlserverEntryNumDlkTrustQueryResponseEnum,
	dlserverEntryNumDtInfoOpenEnum,
	dlserverEntryNumDtInfoCloseEnum,
	dlserverEntryNumDtInfoAddEntryEnum,
	dlserverEntryNumDtInfoDeleteEntryEnum,
	dlserverEntryNumDtInfoGetInfoEnum,
	dlserverEntryNumDtInfoSetInfoEnum,
	dlserverEntryNumDtInfoSetLastSyncTimeEnum,
	dlserverEntryNumDtInfoGetDisplayNameEnum,
	dlserverEntryNumDtInfoSetDisplayNameEnum,
	dlserverEntryNumDtInfoRenameDisplayNameEnum,
	dlserverEntryNumDtInfoSetTrustStatusEnum,
	dlserverEntryNumDtInfoGetFirstEntryEnum,
	dlserverEntryNumDtInfoGetNextEntryEnum,
};

#define dlserverEntryNumDlkStartServer          	((uint32_t)dlserverEntryNumDlkStartServerEnum)
#define dlserverEntryNumDlkGetSyncInfo          	((uint32_t)dlserverEntryNumDlkGetSyncInfoEnum)
#define dlserverEntryNumDlkSetLogEntry          	((uint32_t)dlserverEntryNumDlkSetLogEntryEnum)
#define dlserverEntryNumDlkDispatchRequest      	((uint32_t)dlserverEntryNumDlkDispatchRequestEnum)
#define dlserverEntryNumDlkControl              	((uint32_t)dlserverEntryNumDlkControlEnum)
#define dlserverEntryNumHSUtilReverseWord       	((uint32_t)dlserverEntryNumHSUtilReverseWordEnum)
#define dlserverEntryNumHSUtilReverseDWord      	((uint32_t)dlserverEntryNumHSUtilReverseDWordEnum)
#define dlserverEntryNumDlkTrustDoQuery         	((uint32_t)dlserverEntryNumDlkTrustDoQueryEnum)
#define dlserverEntryNumDlkTrustQueryResponse   	((uint32_t)dlserverEntryNumDlkTrustQueryResponseEnum)
#define dlserverEntryNumDtInfoOpen              	((uint32_t)dlserverEntryNumDtInfoOpenEnum)
#define dlserverEntryNumDtInfoClose             	((uint32_t)dlserverEntryNumDtInfoCloseEnum)
#define dlserverEntryNumDtInfoAddEntry          	((uint32_t)dlserverEntryNumDtInfoAddEntryEnum)
#define dlserverEntryNumDtInfoDeleteEntry       	((uint32_t)dlserverEntryNumDtInfoDeleteEntryEnum)
#define dlserverEntryNumDtInfoGetInfo           	((uint32_t)dlserverEntryNumDtInfoGetInfoEnum)
#define dlserverEntryNumDtInfoSetInfo           	((uint32_t)dlserverEntryNumDtInfoSetInfoEnum)
#define dlserverEntryNumDtInfoSetLastSyncTime   	((uint32_t)dlserverEntryNumDtInfoSetLastSyncTimeEnum)
#define dlserverEntryNumDtInfoGetDisplayName    	((uint32_t)dlserverEntryNumDtInfoGetDisplayNameEnum)
#define dlserverEntryNumDtInfoSetDisplayName    	((uint32_t)dlserverEntryNumDtInfoSetDisplayNameEnum)
#define dlserverEntryNumDtInfoRenameDisplayName 	((uint32_t)dlserverEntryNumDtInfoRenameDisplayNameEnum)
#define dlserverEntryNumDtInfoSetTrustStatus    	((uint32_t)dlserverEntryNumDtInfoSetTrustStatusEnum)
#define dlserverEntryNumDtInfoGetFirstEntry     	((uint32_t)dlserverEntryNumDtInfoGetFirstEntryEnum)
#define dlserverEntryNumDtInfoGetNextEntry      	((uint32_t)dlserverEntryNumDtInfoGetNextEntryEnum)
#endif // __DLSERVERENTRYNUMS_H__
