/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: ExgMgrEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __EXGMGRENTRYNUMS_H__	// Avoid multiple inclusion
#define __EXGMGRENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum exgmgrEntryNumTag {
	exgmgrEntryNumExgInitEnum = 0,
	exgmgrEntryNumExgRegisterDataEnum,
	exgmgrEntryNumExgRegisterDatatypeEnum,
	exgmgrEntryNumExgSetDefaultApplicationEnum,
	exgmgrEntryNumExgGetDefaultApplicationEnum,
	exgmgrEntryNumExgGetTargetApplicationEnum,
	exgmgrEntryNumExgGetRegisteredApplicationsEnum,
	exgmgrEntryNumExgGetRegisteredTypesEnum,
	exgmgrEntryNumExgConnectEnum,
	exgmgrEntryNumExgPutEnum,
	exgmgrEntryNumExgGetEnum,
	exgmgrEntryNumExgRequestEnum,
	exgmgrEntryNumExgAcceptEnum,
	exgmgrEntryNumExgDisconnectEnum,
	exgmgrEntryNumExgSendEnum,
	exgmgrEntryNumExgReceiveEnum,
	exgmgrEntryNumExgControlEnum,
	exgmgrEntryNumExgNotifyReceiveV35Enum,
	exgmgrEntryNumExgNotifyReceiveEnum,
	exgmgrEntryNumExgNotifyGotoEnum,
	exgmgrEntryNumExgNotifyPreviewEnum,
	exgmgrEntryNumExgDBReadV40Enum,
	exgmgrEntryNumExgDBWriteV40Enum,
	exgmgrEntryNumExgDBReadEnum,
	exgmgrEntryNumExgDBWriteEnum,
	exgmgrEntryNumExgDoDialogEnum,
	exgmgrEntryNumExgAddStringParamEnum,
	exgmgrEntryNumExgGetStringParamEnum,
	exgmgrEntryNumExgAddBlockParamEnum,
	exgmgrEntryNumExgGetBlockParamEnum,
	exgmgrEntryNumExgAddIntegerParamEnum,
	exgmgrEntryNumExgGetIntegerParamEnum,
	exgmgrEntryNumExgExecuteCommandEnum,
	exgmgrEntryNumExgLibGetLibraryRefEnum,
	exgmgrEntryNumExgDispatchIncomingSocketEnum,
	exgmgrEntryNumExgPrvFlattenSocketEnum,
	exgmgrEntryNumExgPrvInflateSocketEnum,
};

#define exgmgrEntryNumExgInit                      	((uint32_t)exgmgrEntryNumExgInitEnum)
#define exgmgrEntryNumExgRegisterData              	((uint32_t)exgmgrEntryNumExgRegisterDataEnum)
#define exgmgrEntryNumExgRegisterDatatype          	((uint32_t)exgmgrEntryNumExgRegisterDatatypeEnum)
#define exgmgrEntryNumExgSetDefaultApplication     	((uint32_t)exgmgrEntryNumExgSetDefaultApplicationEnum)
#define exgmgrEntryNumExgGetDefaultApplication     	((uint32_t)exgmgrEntryNumExgGetDefaultApplicationEnum)
#define exgmgrEntryNumExgGetTargetApplication      	((uint32_t)exgmgrEntryNumExgGetTargetApplicationEnum)
#define exgmgrEntryNumExgGetRegisteredApplications 	((uint32_t)exgmgrEntryNumExgGetRegisteredApplicationsEnum)
#define exgmgrEntryNumExgGetRegisteredTypes        	((uint32_t)exgmgrEntryNumExgGetRegisteredTypesEnum)
#define exgmgrEntryNumExgConnect                   	((uint32_t)exgmgrEntryNumExgConnectEnum)
#define exgmgrEntryNumExgPut                       	((uint32_t)exgmgrEntryNumExgPutEnum)
#define exgmgrEntryNumExgGet                       	((uint32_t)exgmgrEntryNumExgGetEnum)
#define exgmgrEntryNumExgRequest                   	((uint32_t)exgmgrEntryNumExgRequestEnum)
#define exgmgrEntryNumExgAccept                    	((uint32_t)exgmgrEntryNumExgAcceptEnum)
#define exgmgrEntryNumExgDisconnect                	((uint32_t)exgmgrEntryNumExgDisconnectEnum)
#define exgmgrEntryNumExgSend                      	((uint32_t)exgmgrEntryNumExgSendEnum)
#define exgmgrEntryNumExgReceive                   	((uint32_t)exgmgrEntryNumExgReceiveEnum)
#define exgmgrEntryNumExgControl                   	((uint32_t)exgmgrEntryNumExgControlEnum)
#define exgmgrEntryNumExgNotifyReceiveV35          	((uint32_t)exgmgrEntryNumExgNotifyReceiveV35Enum)
#define exgmgrEntryNumExgNotifyReceive             	((uint32_t)exgmgrEntryNumExgNotifyReceiveEnum)
#define exgmgrEntryNumExgNotifyGoto                	((uint32_t)exgmgrEntryNumExgNotifyGotoEnum)
#define exgmgrEntryNumExgNotifyPreview             	((uint32_t)exgmgrEntryNumExgNotifyPreviewEnum)
#define exgmgrEntryNumExgDBReadV40                 	((uint32_t)exgmgrEntryNumExgDBReadV40Enum)
#define exgmgrEntryNumExgDBWriteV40                	((uint32_t)exgmgrEntryNumExgDBWriteV40Enum)
#define exgmgrEntryNumExgDBRead                    	((uint32_t)exgmgrEntryNumExgDBReadEnum)
#define exgmgrEntryNumExgDBWrite                   	((uint32_t)exgmgrEntryNumExgDBWriteEnum)
#define exgmgrEntryNumExgDoDialog                  	((uint32_t)exgmgrEntryNumExgDoDialogEnum)
#define exgmgrEntryNumExgAddStringParam            	((uint32_t)exgmgrEntryNumExgAddStringParamEnum)
#define exgmgrEntryNumExgGetStringParam            	((uint32_t)exgmgrEntryNumExgGetStringParamEnum)
#define exgmgrEntryNumExgAddBlockParam             	((uint32_t)exgmgrEntryNumExgAddBlockParamEnum)
#define exgmgrEntryNumExgGetBlockParam             	((uint32_t)exgmgrEntryNumExgGetBlockParamEnum)
#define exgmgrEntryNumExgAddIntegerParam           	((uint32_t)exgmgrEntryNumExgAddIntegerParamEnum)
#define exgmgrEntryNumExgGetIntegerParam           	((uint32_t)exgmgrEntryNumExgGetIntegerParamEnum)
#define exgmgrEntryNumExgExecuteCommand            	((uint32_t)exgmgrEntryNumExgExecuteCommandEnum)
#define exgmgrEntryNumExgLibGetLibraryRef          	((uint32_t)exgmgrEntryNumExgLibGetLibraryRefEnum)
#define exgmgrEntryNumExgDispatchIncomingSocket    	((uint32_t)exgmgrEntryNumExgDispatchIncomingSocketEnum)
#define exgmgrEntryNumExgPrvFlattenSocket          	((uint32_t)exgmgrEntryNumExgPrvFlattenSocketEnum)
#define exgmgrEntryNumExgPrvInflateSocket          	((uint32_t)exgmgrEntryNumExgPrvInflateSocketEnum)
#endif // __EXGMGRENTRYNUMS_H__
