/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: ExpansionVFSLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __EXPANSIONVFSLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __EXPANSIONVFSLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum expansionvfslibEntryNumTag {
	expansionvfslibEntryNumExpCardPresentEnum = 0,
	expansionvfslibEntryNumExpCardInfoEnum,
	expansionvfslibEntryNumExpSlotEnumerateEnum,
	expansionvfslibEntryNumExpCardSectorReadEnum,
	expansionvfslibEntryNumExpCardSectorWriteEnum,
	expansionvfslibEntryNumExpSlotCustomControlEnum,
	expansionvfslibEntryNumExpCardMediaTypeEnum,
	expansionvfslibEntryNumExpSlotMediaTypeEnum,
	expansionvfslibEntryNumExpCardIsFilesystemSupportedEnum,
	expansionvfslibEntryNumExpCardMetricsEnum,
	expansionvfslibEntryNumExpSlotPowerCheckEnum,
	expansionvfslibEntryNumVFSCustomControlEnum,
	expansionvfslibEntryNumVFSDirCreateEnum,
	expansionvfslibEntryNumVFSDirEntryEnumerateEnum,
	expansionvfslibEntryNumVFSExportDatabaseToFileEnum,
	expansionvfslibEntryNumVFSExportDatabaseToFileV40Enum,
	expansionvfslibEntryNumVFSExportDatabaseToFileCustomEnum,
	expansionvfslibEntryNumVFSExportDatabaseToFileCustomV40Enum,
	expansionvfslibEntryNumVFSFileCloseEnum,
	expansionvfslibEntryNumVFSFileCreateEnum,
	expansionvfslibEntryNumVFSFileDBGetRecordEnum,
	expansionvfslibEntryNumVFSFileDBGetResourceEnum,
	expansionvfslibEntryNumVFSFileDBInfoEnum,
	expansionvfslibEntryNumVFSFileDeleteEnum,
	expansionvfslibEntryNumVFSFileEOFEnum,
	expansionvfslibEntryNumVFSFileGetAttributesEnum,
	expansionvfslibEntryNumVFSFileGetDateEnum,
	expansionvfslibEntryNumVFSFileOpenEnum,
	expansionvfslibEntryNumVFSFileOpenFromURLEnum,
	expansionvfslibEntryNumVFSFileReadEnum,
	expansionvfslibEntryNumVFSFileReadDataEnum,
	expansionvfslibEntryNumVFSFileRenameEnum,
	expansionvfslibEntryNumVFSFileResizeEnum,
	expansionvfslibEntryNumVFSFileSeekEnum,
	expansionvfslibEntryNumVFSFileSetAttributesEnum,
	expansionvfslibEntryNumVFSFileSetDateEnum,
	expansionvfslibEntryNumVFSFileSizeEnum,
	expansionvfslibEntryNumVFSFileTellEnum,
	expansionvfslibEntryNumVFSFileWriteEnum,
	expansionvfslibEntryNumVFSGetDefaultDirectoryEnum,
	expansionvfslibEntryNumVFSImportDatabaseFromFileEnum,
	expansionvfslibEntryNumVFSImportDatabaseFromFileV40Enum,
	expansionvfslibEntryNumVFSImportDatabaseFromFileCustomEnum,
	expansionvfslibEntryNumVFSImportDatabaseFromFileCustomV40Enum,
	expansionvfslibEntryNumVFSRegisterDefaultDirectoryEnum,
	expansionvfslibEntryNumVFSUnregisterDefaultDirectoryEnum,
	expansionvfslibEntryNumVFSVolumeEnumerateV60Enum,
	expansionvfslibEntryNumVFSVolumeFormatEnum,
	expansionvfslibEntryNumVFSVolumeGetLabelEnum,
	expansionvfslibEntryNumVFSVolumeInfoEnum,
	expansionvfslibEntryNumVFSVolumeMountEnum,
	expansionvfslibEntryNumVFSVolumeSetLabelEnum,
	expansionvfslibEntryNumVFSVolumeSizeV60Enum,
	expansionvfslibEntryNumVFSVolumeUnmountEnum,
	expansionvfslibEntryNumVFSVolumeSizeEnum,
	expansionvfslibEntryNumVFSVolumeEnumerateEnum,
};

#define expansionvfslibEntryNumExpCardPresent                     	((uint32_t)expansionvfslibEntryNumExpCardPresentEnum)
#define expansionvfslibEntryNumExpCardInfo                        	((uint32_t)expansionvfslibEntryNumExpCardInfoEnum)
#define expansionvfslibEntryNumExpSlotEnumerate                   	((uint32_t)expansionvfslibEntryNumExpSlotEnumerateEnum)
#define expansionvfslibEntryNumExpCardSectorRead                  	((uint32_t)expansionvfslibEntryNumExpCardSectorReadEnum)
#define expansionvfslibEntryNumExpCardSectorWrite                 	((uint32_t)expansionvfslibEntryNumExpCardSectorWriteEnum)
#define expansionvfslibEntryNumExpSlotCustomControl               	((uint32_t)expansionvfslibEntryNumExpSlotCustomControlEnum)
#define expansionvfslibEntryNumExpCardMediaType                   	((uint32_t)expansionvfslibEntryNumExpCardMediaTypeEnum)
#define expansionvfslibEntryNumExpSlotMediaType                   	((uint32_t)expansionvfslibEntryNumExpSlotMediaTypeEnum)
#define expansionvfslibEntryNumExpCardIsFilesystemSupported       	((uint32_t)expansionvfslibEntryNumExpCardIsFilesystemSupportedEnum)
#define expansionvfslibEntryNumExpCardMetrics                     	((uint32_t)expansionvfslibEntryNumExpCardMetricsEnum)
#define expansionvfslibEntryNumExpSlotPowerCheck                  	((uint32_t)expansionvfslibEntryNumExpSlotPowerCheckEnum)
#define expansionvfslibEntryNumVFSCustomControl                   	((uint32_t)expansionvfslibEntryNumVFSCustomControlEnum)
#define expansionvfslibEntryNumVFSDirCreate                       	((uint32_t)expansionvfslibEntryNumVFSDirCreateEnum)
#define expansionvfslibEntryNumVFSDirEntryEnumerate               	((uint32_t)expansionvfslibEntryNumVFSDirEntryEnumerateEnum)
#define expansionvfslibEntryNumVFSExportDatabaseToFile            	((uint32_t)expansionvfslibEntryNumVFSExportDatabaseToFileEnum)
#define expansionvfslibEntryNumVFSExportDatabaseToFileV40         	((uint32_t)expansionvfslibEntryNumVFSExportDatabaseToFileV40Enum)
#define expansionvfslibEntryNumVFSExportDatabaseToFileCustom      	((uint32_t)expansionvfslibEntryNumVFSExportDatabaseToFileCustomEnum)
#define expansionvfslibEntryNumVFSExportDatabaseToFileCustomV40   	((uint32_t)expansionvfslibEntryNumVFSExportDatabaseToFileCustomV40Enum)
#define expansionvfslibEntryNumVFSFileClose                       	((uint32_t)expansionvfslibEntryNumVFSFileCloseEnum)
#define expansionvfslibEntryNumVFSFileCreate                      	((uint32_t)expansionvfslibEntryNumVFSFileCreateEnum)
#define expansionvfslibEntryNumVFSFileDBGetRecord                 	((uint32_t)expansionvfslibEntryNumVFSFileDBGetRecordEnum)
#define expansionvfslibEntryNumVFSFileDBGetResource               	((uint32_t)expansionvfslibEntryNumVFSFileDBGetResourceEnum)
#define expansionvfslibEntryNumVFSFileDBInfo                      	((uint32_t)expansionvfslibEntryNumVFSFileDBInfoEnum)
#define expansionvfslibEntryNumVFSFileDelete                      	((uint32_t)expansionvfslibEntryNumVFSFileDeleteEnum)
#define expansionvfslibEntryNumVFSFileEOF                         	((uint32_t)expansionvfslibEntryNumVFSFileEOFEnum)
#define expansionvfslibEntryNumVFSFileGetAttributes               	((uint32_t)expansionvfslibEntryNumVFSFileGetAttributesEnum)
#define expansionvfslibEntryNumVFSFileGetDate                     	((uint32_t)expansionvfslibEntryNumVFSFileGetDateEnum)
#define expansionvfslibEntryNumVFSFileOpen                        	((uint32_t)expansionvfslibEntryNumVFSFileOpenEnum)
#define expansionvfslibEntryNumVFSFileOpenFromURL                 	((uint32_t)expansionvfslibEntryNumVFSFileOpenFromURLEnum)
#define expansionvfslibEntryNumVFSFileRead                        	((uint32_t)expansionvfslibEntryNumVFSFileReadEnum)
#define expansionvfslibEntryNumVFSFileReadData                    	((uint32_t)expansionvfslibEntryNumVFSFileReadDataEnum)
#define expansionvfslibEntryNumVFSFileRename                      	((uint32_t)expansionvfslibEntryNumVFSFileRenameEnum)
#define expansionvfslibEntryNumVFSFileResize                      	((uint32_t)expansionvfslibEntryNumVFSFileResizeEnum)
#define expansionvfslibEntryNumVFSFileSeek                        	((uint32_t)expansionvfslibEntryNumVFSFileSeekEnum)
#define expansionvfslibEntryNumVFSFileSetAttributes               	((uint32_t)expansionvfslibEntryNumVFSFileSetAttributesEnum)
#define expansionvfslibEntryNumVFSFileSetDate                     	((uint32_t)expansionvfslibEntryNumVFSFileSetDateEnum)
#define expansionvfslibEntryNumVFSFileSize                        	((uint32_t)expansionvfslibEntryNumVFSFileSizeEnum)
#define expansionvfslibEntryNumVFSFileTell                        	((uint32_t)expansionvfslibEntryNumVFSFileTellEnum)
#define expansionvfslibEntryNumVFSFileWrite                       	((uint32_t)expansionvfslibEntryNumVFSFileWriteEnum)
#define expansionvfslibEntryNumVFSGetDefaultDirectory             	((uint32_t)expansionvfslibEntryNumVFSGetDefaultDirectoryEnum)
#define expansionvfslibEntryNumVFSImportDatabaseFromFile          	((uint32_t)expansionvfslibEntryNumVFSImportDatabaseFromFileEnum)
#define expansionvfslibEntryNumVFSImportDatabaseFromFileV40       	((uint32_t)expansionvfslibEntryNumVFSImportDatabaseFromFileV40Enum)
#define expansionvfslibEntryNumVFSImportDatabaseFromFileCustom    	((uint32_t)expansionvfslibEntryNumVFSImportDatabaseFromFileCustomEnum)
#define expansionvfslibEntryNumVFSImportDatabaseFromFileCustomV40 	((uint32_t)expansionvfslibEntryNumVFSImportDatabaseFromFileCustomV40Enum)
#define expansionvfslibEntryNumVFSRegisterDefaultDirectory        	((uint32_t)expansionvfslibEntryNumVFSRegisterDefaultDirectoryEnum)
#define expansionvfslibEntryNumVFSUnregisterDefaultDirectory      	((uint32_t)expansionvfslibEntryNumVFSUnregisterDefaultDirectoryEnum)
#define expansionvfslibEntryNumVFSVolumeEnumerateV60              	((uint32_t)expansionvfslibEntryNumVFSVolumeEnumerateV60Enum)
#define expansionvfslibEntryNumVFSVolumeFormat                    	((uint32_t)expansionvfslibEntryNumVFSVolumeFormatEnum)
#define expansionvfslibEntryNumVFSVolumeGetLabel                  	((uint32_t)expansionvfslibEntryNumVFSVolumeGetLabelEnum)
#define expansionvfslibEntryNumVFSVolumeInfo                      	((uint32_t)expansionvfslibEntryNumVFSVolumeInfoEnum)
#define expansionvfslibEntryNumVFSVolumeMount                     	((uint32_t)expansionvfslibEntryNumVFSVolumeMountEnum)
#define expansionvfslibEntryNumVFSVolumeSetLabel                  	((uint32_t)expansionvfslibEntryNumVFSVolumeSetLabelEnum)
#define expansionvfslibEntryNumVFSVolumeSizeV60                   	((uint32_t)expansionvfslibEntryNumVFSVolumeSizeV60Enum)
#define expansionvfslibEntryNumVFSVolumeUnmount                   	((uint32_t)expansionvfslibEntryNumVFSVolumeUnmountEnum)
#define expansionvfslibEntryNumVFSVolumeSize                      	((uint32_t)expansionvfslibEntryNumVFSVolumeSizeEnum)
#define expansionvfslibEntryNumVFSVolumeEnumerate                 	((uint32_t)expansionvfslibEntryNumVFSVolumeEnumerateEnum)
#endif // __EXPANSIONVFSLIBENTRYNUMS_H__
