/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: FileStreamEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __FILESTREAMENTRYNUMS_H__	// Avoid multiple inclusion
#define __FILESTREAMENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum filestreamEntryNumTag {
	filestreamEntryNumFileOpenEnum = 0,
	filestreamEntryNumFileCloseEnum,
	filestreamEntryNumFileDeleteEnum,
	filestreamEntryNumFileReadLowEnum,
	filestreamEntryNumFileWriteEnum,
	filestreamEntryNumFileSeekEnum,
	filestreamEntryNumFileTellEnum,
	filestreamEntryNumFileTruncateEnum,
	filestreamEntryNumFileControlEnum,
	filestreamEntryNumFileOpenV50Enum,
	filestreamEntryNumFileDeleteV50Enum,
};

#define filestreamEntryNumFileOpen         	((uint32_t)filestreamEntryNumFileOpenEnum)
#define filestreamEntryNumFileClose        	((uint32_t)filestreamEntryNumFileCloseEnum)
#define filestreamEntryNumFileDelete       	((uint32_t)filestreamEntryNumFileDeleteEnum)
#define filestreamEntryNumFileReadLow      	((uint32_t)filestreamEntryNumFileReadLowEnum)
#define filestreamEntryNumFileWrite        	((uint32_t)filestreamEntryNumFileWriteEnum)
#define filestreamEntryNumFileSeek         	((uint32_t)filestreamEntryNumFileSeekEnum)
#define filestreamEntryNumFileTell         	((uint32_t)filestreamEntryNumFileTellEnum)
#define filestreamEntryNumFileTruncate     	((uint32_t)filestreamEntryNumFileTruncateEnum)
#define filestreamEntryNumFileControl      	((uint32_t)filestreamEntryNumFileControlEnum)
#define filestreamEntryNumFileOpenV50      	((uint32_t)filestreamEntryNumFileOpenV50Enum)
#define filestreamEntryNumFileDeleteV50    	((uint32_t)filestreamEntryNumFileDeleteV50Enum)
#endif // __FILESTREAMENTRYNUMS_H__
