/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: FloatMgrEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __FLOATMGRENTRYNUMS_H__	// Avoid multiple inclusion
#define __FLOATMGRENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum floatmgrEntryNumTag {
	floatmgrEntryNumFlpFToAEnum = 0,
	floatmgrEntryNumFlpUInt32ToFloatEnum,
	floatmgrEntryNumFlpInt32ToFloatEnum,
	floatmgrEntryNumFlpULongLongToFloatEnum,
	floatmgrEntryNumFlpLongLongToFloatEnum,
	floatmgrEntryNumFlpUInt32ToDoubleEnum,
	floatmgrEntryNumFlpInt32ToDoubleEnum,
	floatmgrEntryNumFlpULongLongToDoubleEnum,
	floatmgrEntryNumFlpLongLongToDoubleEnum,
	floatmgrEntryNumFlpFloatToDoubleEnum,
	floatmgrEntryNumFlpDoubleToFloatEnum,
	floatmgrEntryNumFlpFloatToLongDoubleEnum,
	floatmgrEntryNumFlpLongDoubleToFloatEnum,
	floatmgrEntryNumFlpDoubleToLongDoubleEnum,
	floatmgrEntryNumFlpLongDoubleToDoubleEnum,
	floatmgrEntryNumFlpFloatToUInt32Enum,
	floatmgrEntryNumFlpFloatToInt32Enum,
	floatmgrEntryNumFlpFloatToULongLongEnum,
	floatmgrEntryNumFlpFloatToLongLongEnum,
	floatmgrEntryNumFlpDoubleToUInt32Enum,
	floatmgrEntryNumFlpDoubleToInt32Enum,
	floatmgrEntryNumFlpDoubleToULongLongEnum,
	floatmgrEntryNumFlpDoubleToLongLongEnum,
	floatmgrEntryNumFlpNegFloatEnum,
	floatmgrEntryNumFlpAddFloatEnum,
	floatmgrEntryNumFlpMulFloatEnum,
	floatmgrEntryNumFlpSubFloatEnum,
	floatmgrEntryNumFlpDivFloatEnum,
	floatmgrEntryNumFlpNegDoubleEnum,
	floatmgrEntryNumFlpAddDoubleEnum,
	floatmgrEntryNumFlpMulDoubleEnum,
	floatmgrEntryNumFlpSubDoubleEnum,
	floatmgrEntryNumFlpDivDoubleEnum,
	floatmgrEntryNumFlpCompareFloatEqualEnum,
	floatmgrEntryNumFlpCompareFloatLessThanEnum,
	floatmgrEntryNumFlpCompareFloatLessThanOrEqualEnum,
	floatmgrEntryNumFlpCompareDoubleEqualEnum,
	floatmgrEntryNumFlpCompareDoubleLessThanEnum,
	floatmgrEntryNumFlpCompareDoubleLessThanOrEqualEnum,
	floatmgrEntryNumFlpCorrectedSubEnum,
	floatmgrEntryNumFlpCorrectedAddEnum,
	floatmgrEntryNumFlpBase10InfoEnum,
};

#define floatmgrEntryNumFlpFToA                         	((uint32_t)floatmgrEntryNumFlpFToAEnum)
#define floatmgrEntryNumFlpUInt32ToFloat                	((uint32_t)floatmgrEntryNumFlpUInt32ToFloatEnum)
#define floatmgrEntryNumFlpInt32ToFloat                 	((uint32_t)floatmgrEntryNumFlpInt32ToFloatEnum)
#define floatmgrEntryNumFlpULongLongToFloat             	((uint32_t)floatmgrEntryNumFlpULongLongToFloatEnum)
#define floatmgrEntryNumFlpLongLongToFloat              	((uint32_t)floatmgrEntryNumFlpLongLongToFloatEnum)
#define floatmgrEntryNumFlpUInt32ToDouble               	((uint32_t)floatmgrEntryNumFlpUInt32ToDoubleEnum)
#define floatmgrEntryNumFlpInt32ToDouble                	((uint32_t)floatmgrEntryNumFlpInt32ToDoubleEnum)
#define floatmgrEntryNumFlpULongLongToDouble            	((uint32_t)floatmgrEntryNumFlpULongLongToDoubleEnum)
#define floatmgrEntryNumFlpLongLongToDouble             	((uint32_t)floatmgrEntryNumFlpLongLongToDoubleEnum)
#define floatmgrEntryNumFlpFloatToDouble                	((uint32_t)floatmgrEntryNumFlpFloatToDoubleEnum)
#define floatmgrEntryNumFlpDoubleToFloat                	((uint32_t)floatmgrEntryNumFlpDoubleToFloatEnum)
#define floatmgrEntryNumFlpFloatToLongDouble            	((uint32_t)floatmgrEntryNumFlpFloatToLongDoubleEnum)
#define floatmgrEntryNumFlpLongDoubleToFloat            	((uint32_t)floatmgrEntryNumFlpLongDoubleToFloatEnum)
#define floatmgrEntryNumFlpDoubleToLongDouble           	((uint32_t)floatmgrEntryNumFlpDoubleToLongDoubleEnum)
#define floatmgrEntryNumFlpLongDoubleToDouble           	((uint32_t)floatmgrEntryNumFlpLongDoubleToDoubleEnum)
#define floatmgrEntryNumFlpFloatToUInt32                	((uint32_t)floatmgrEntryNumFlpFloatToUInt32Enum)
#define floatmgrEntryNumFlpFloatToInt32                 	((uint32_t)floatmgrEntryNumFlpFloatToInt32Enum)
#define floatmgrEntryNumFlpFloatToULongLong             	((uint32_t)floatmgrEntryNumFlpFloatToULongLongEnum)
#define floatmgrEntryNumFlpFloatToLongLong              	((uint32_t)floatmgrEntryNumFlpFloatToLongLongEnum)
#define floatmgrEntryNumFlpDoubleToUInt32               	((uint32_t)floatmgrEntryNumFlpDoubleToUInt32Enum)
#define floatmgrEntryNumFlpDoubleToInt32                	((uint32_t)floatmgrEntryNumFlpDoubleToInt32Enum)
#define floatmgrEntryNumFlpDoubleToULongLong            	((uint32_t)floatmgrEntryNumFlpDoubleToULongLongEnum)
#define floatmgrEntryNumFlpDoubleToLongLong             	((uint32_t)floatmgrEntryNumFlpDoubleToLongLongEnum)
#define floatmgrEntryNumFlpNegFloat                     	((uint32_t)floatmgrEntryNumFlpNegFloatEnum)
#define floatmgrEntryNumFlpAddFloat                     	((uint32_t)floatmgrEntryNumFlpAddFloatEnum)
#define floatmgrEntryNumFlpMulFloat                     	((uint32_t)floatmgrEntryNumFlpMulFloatEnum)
#define floatmgrEntryNumFlpSubFloat                     	((uint32_t)floatmgrEntryNumFlpSubFloatEnum)
#define floatmgrEntryNumFlpDivFloat                     	((uint32_t)floatmgrEntryNumFlpDivFloatEnum)
#define floatmgrEntryNumFlpNegDouble                    	((uint32_t)floatmgrEntryNumFlpNegDoubleEnum)
#define floatmgrEntryNumFlpAddDouble                    	((uint32_t)floatmgrEntryNumFlpAddDoubleEnum)
#define floatmgrEntryNumFlpMulDouble                    	((uint32_t)floatmgrEntryNumFlpMulDoubleEnum)
#define floatmgrEntryNumFlpSubDouble                    	((uint32_t)floatmgrEntryNumFlpSubDoubleEnum)
#define floatmgrEntryNumFlpDivDouble                    	((uint32_t)floatmgrEntryNumFlpDivDoubleEnum)
#define floatmgrEntryNumFlpCompareFloatEqual            	((uint32_t)floatmgrEntryNumFlpCompareFloatEqualEnum)
#define floatmgrEntryNumFlpCompareFloatLessThan         	((uint32_t)floatmgrEntryNumFlpCompareFloatLessThanEnum)
#define floatmgrEntryNumFlpCompareFloatLessThanOrEqual  	((uint32_t)floatmgrEntryNumFlpCompareFloatLessThanOrEqualEnum)
#define floatmgrEntryNumFlpCompareDoubleEqual           	((uint32_t)floatmgrEntryNumFlpCompareDoubleEqualEnum)
#define floatmgrEntryNumFlpCompareDoubleLessThan        	((uint32_t)floatmgrEntryNumFlpCompareDoubleLessThanEnum)
#define floatmgrEntryNumFlpCompareDoubleLessThanOrEqual 	((uint32_t)floatmgrEntryNumFlpCompareDoubleLessThanOrEqualEnum)
#define floatmgrEntryNumFlpCorrectedSub                 	((uint32_t)floatmgrEntryNumFlpCorrectedSubEnum)
#define floatmgrEntryNumFlpCorrectedAdd                 	((uint32_t)floatmgrEntryNumFlpCorrectedAddEnum)
#define floatmgrEntryNumFlpBase10Info                   	((uint32_t)floatmgrEntryNumFlpBase10InfoEnum)
#endif // __FLOATMGRENTRYNUMS_H__
