/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: IOSLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __IOSLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __IOSLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum ioslibEntryNumTag {
	ioslibEntryNumIOSOpenEnum = 0,
	ioslibEntryNumIOSCloseEnum,
	ioslibEntryNumIOSIoctlEnum,
	ioslibEntryNumIOSFastIoctlEnum,
	ioslibEntryNumIOSReadEnum,
	ioslibEntryNumIOSWriteEnum,
	ioslibEntryNumIOSReadvEnum,
	ioslibEntryNumIOSWritevEnum,
	ioslibEntryNumIOSPutmsgEnum,
	ioslibEntryNumIOSGetmsgEnum,
	ioslibEntryNumIOSPutpmsgEnum,
	ioslibEntryNumIOSGetpmsgEnum,
	ioslibEntryNumIOSFattachEnum,
	ioslibEntryNumIOSFdetachEnum,
	ioslibEntryNumIOSPipeEnum,
	ioslibEntryNumIOSPollEnum,
	ioslibEntryNumIOSFcntlEnum,
	ioslibEntryNumIOSInstallDriverEnum,
	ioslibEntryNumIOSRemoveDriverEnum,
	ioslibEntryNumIOSGetNumDriversEnum,
	ioslibEntryNumIOSGetDriverAttributesByIndexEnum,
	ioslibEntryNumIOSGetDriverAttributesByNameEnum,
	ioslibEntryNumIOSGetDriverDescriptionByIndexEnum,
	ioslibEntryNumIOSGetDriverDescriptionByNameEnum,
	ioslibEntryNumIOSGetDriverNameByIndexEnum,
	ioslibEntryNumIOSSetStdIOEventDescriptorEnum,
	ioslibEntryNumPbxCreateEnum,
	ioslibEntryNumPbxDestroyEnum,
	ioslibEntryNumPbxAddFdEnum,
	ioslibEntryNumPbxRemoveFdEnum,
	ioslibEntryNumPbxPollEnum,
	ioslibEntryNumPbxRunEnum,
};

#define ioslibEntryNumIOSOpen                        	((uint32_t)ioslibEntryNumIOSOpenEnum)
#define ioslibEntryNumIOSClose                       	((uint32_t)ioslibEntryNumIOSCloseEnum)
#define ioslibEntryNumIOSIoctl                       	((uint32_t)ioslibEntryNumIOSIoctlEnum)
#define ioslibEntryNumIOSFastIoctl                   	((uint32_t)ioslibEntryNumIOSFastIoctlEnum)
#define ioslibEntryNumIOSRead                        	((uint32_t)ioslibEntryNumIOSReadEnum)
#define ioslibEntryNumIOSWrite                       	((uint32_t)ioslibEntryNumIOSWriteEnum)
#define ioslibEntryNumIOSReadv                       	((uint32_t)ioslibEntryNumIOSReadvEnum)
#define ioslibEntryNumIOSWritev                      	((uint32_t)ioslibEntryNumIOSWritevEnum)
#define ioslibEntryNumIOSPutmsg                      	((uint32_t)ioslibEntryNumIOSPutmsgEnum)
#define ioslibEntryNumIOSGetmsg                      	((uint32_t)ioslibEntryNumIOSGetmsgEnum)
#define ioslibEntryNumIOSPutpmsg                     	((uint32_t)ioslibEntryNumIOSPutpmsgEnum)
#define ioslibEntryNumIOSGetpmsg                     	((uint32_t)ioslibEntryNumIOSGetpmsgEnum)
#define ioslibEntryNumIOSFattach                     	((uint32_t)ioslibEntryNumIOSFattachEnum)
#define ioslibEntryNumIOSFdetach                     	((uint32_t)ioslibEntryNumIOSFdetachEnum)
#define ioslibEntryNumIOSPipe                        	((uint32_t)ioslibEntryNumIOSPipeEnum)
#define ioslibEntryNumIOSPoll                        	((uint32_t)ioslibEntryNumIOSPollEnum)
#define ioslibEntryNumIOSFcntl                       	((uint32_t)ioslibEntryNumIOSFcntlEnum)
#define ioslibEntryNumIOSInstallDriver               	((uint32_t)ioslibEntryNumIOSInstallDriverEnum)
#define ioslibEntryNumIOSRemoveDriver                	((uint32_t)ioslibEntryNumIOSRemoveDriverEnum)
#define ioslibEntryNumIOSGetNumDrivers               	((uint32_t)ioslibEntryNumIOSGetNumDriversEnum)
#define ioslibEntryNumIOSGetDriverAttributesByIndex  	((uint32_t)ioslibEntryNumIOSGetDriverAttributesByIndexEnum)
#define ioslibEntryNumIOSGetDriverAttributesByName   	((uint32_t)ioslibEntryNumIOSGetDriverAttributesByNameEnum)
#define ioslibEntryNumIOSGetDriverDescriptionByIndex 	((uint32_t)ioslibEntryNumIOSGetDriverDescriptionByIndexEnum)
#define ioslibEntryNumIOSGetDriverDescriptionByName  	((uint32_t)ioslibEntryNumIOSGetDriverDescriptionByNameEnum)
#define ioslibEntryNumIOSGetDriverNameByIndex        	((uint32_t)ioslibEntryNumIOSGetDriverNameByIndexEnum)
#define ioslibEntryNumIOSSetStdIOEventDescriptor     	((uint32_t)ioslibEntryNumIOSSetStdIOEventDescriptorEnum)
#define ioslibEntryNumPbxCreate                      	((uint32_t)ioslibEntryNumPbxCreateEnum)
#define ioslibEntryNumPbxDestroy                     	((uint32_t)ioslibEntryNumPbxDestroyEnum)
#define ioslibEntryNumPbxAddFd                       	((uint32_t)ioslibEntryNumPbxAddFdEnum)
#define ioslibEntryNumPbxRemoveFd                    	((uint32_t)ioslibEntryNumPbxRemoveFdEnum)
#define ioslibEntryNumPbxPoll                        	((uint32_t)ioslibEntryNumPbxPollEnum)
#define ioslibEntryNumPbxRun                         	((uint32_t)ioslibEntryNumPbxRunEnum)
#endif // __IOSLIBENTRYNUMS_H__
