/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: IrDALibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:55 2004
 *****************************************************************************/
#ifndef __IRDALIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __IRDALIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum irdalibEntryNumTag {
	irdalibEntryNumIrDADiscoverDevicesEnum = 0,
	irdalibEntryNumIrDARegisterServiceEnum,
	irdalibEntryNumIrDAUnregisterServiceEnum,
	irdalibEntryNumIASGetValueByClassEnum,
	irdalibEntryNumIASRegisterObjectEnum,
	irdalibEntryNumIASRegisterServiceEnum,
	irdalibEntryNumIASUnregisterObjectEnum,
	irdalibEntryNumIASFlattenObjectEnum,
	irdalibEntryNumIrLibRunCallbacksEnum,
	irdalibEntryNumIrOpenV50Enum,
	irdalibEntryNumIrCloseV50Enum,
	irdalibEntryNumIrBindV50Enum,
	irdalibEntryNumIrUnbindV50Enum,
	irdalibEntryNumIrDiscoverReqV50Enum,
	irdalibEntryNumIrConnectIrLapV50Enum,
	irdalibEntryNumIrDisconnectIrLapV50Enum,
	irdalibEntryNumIrConnectReqV50Enum,
	irdalibEntryNumIrConnectRspV50Enum,
	irdalibEntryNumIrDataReqV50Enum,
	irdalibEntryNumIrAdvanceCreditV50Enum,
	irdalibEntryNumIrLocalBusyV50Enum,
	irdalibEntryNumIrSetConTypeTTPV50Enum,
	irdalibEntryNumIrSetConTypeLMPV50Enum,
	irdalibEntryNumIrMaxTxSizeV50Enum,
	irdalibEntryNumIrMaxRxSizeV50Enum,
	irdalibEntryNumIrIsNoProgressV50Enum,
	irdalibEntryNumIrIsRemoteBusyV50Enum,
	irdalibEntryNumIrIsMediaBusyV50Enum,
	irdalibEntryNumIrIsIrLapConnectedV50Enum,
	irdalibEntryNumIrTestReqV50Enum,
	irdalibEntryNumIrIAS_AddV50Enum,
	irdalibEntryNumIrIAS_RemoveV50Enum,
	irdalibEntryNumIrIAS_QueryV50Enum,
	irdalibEntryNumIrIAS_NextV50Enum,
};

#define irdalibEntryNumIrDADiscoverDevices   	((uint32_t)irdalibEntryNumIrDADiscoverDevicesEnum)
#define irdalibEntryNumIrDARegisterService   	((uint32_t)irdalibEntryNumIrDARegisterServiceEnum)
#define irdalibEntryNumIrDAUnregisterService 	((uint32_t)irdalibEntryNumIrDAUnregisterServiceEnum)
#define irdalibEntryNumIASGetValueByClass    	((uint32_t)irdalibEntryNumIASGetValueByClassEnum)
#define irdalibEntryNumIASRegisterObject     	((uint32_t)irdalibEntryNumIASRegisterObjectEnum)
#define irdalibEntryNumIASRegisterService    	((uint32_t)irdalibEntryNumIASRegisterServiceEnum)
#define irdalibEntryNumIASUnregisterObject   	((uint32_t)irdalibEntryNumIASUnregisterObjectEnum)
#define irdalibEntryNumIASFlattenObject      	((uint32_t)irdalibEntryNumIASFlattenObjectEnum)
#define irdalibEntryNumIrLibRunCallbacks     	((uint32_t)irdalibEntryNumIrLibRunCallbacksEnum)
#define irdalibEntryNumIrOpenV50             	((uint32_t)irdalibEntryNumIrOpenV50Enum)
#define irdalibEntryNumIrCloseV50            	((uint32_t)irdalibEntryNumIrCloseV50Enum)
#define irdalibEntryNumIrBindV50             	((uint32_t)irdalibEntryNumIrBindV50Enum)
#define irdalibEntryNumIrUnbindV50           	((uint32_t)irdalibEntryNumIrUnbindV50Enum)
#define irdalibEntryNumIrDiscoverReqV50      	((uint32_t)irdalibEntryNumIrDiscoverReqV50Enum)
#define irdalibEntryNumIrConnectIrLapV50     	((uint32_t)irdalibEntryNumIrConnectIrLapV50Enum)
#define irdalibEntryNumIrDisconnectIrLapV50  	((uint32_t)irdalibEntryNumIrDisconnectIrLapV50Enum)
#define irdalibEntryNumIrConnectReqV50       	((uint32_t)irdalibEntryNumIrConnectReqV50Enum)
#define irdalibEntryNumIrConnectRspV50       	((uint32_t)irdalibEntryNumIrConnectRspV50Enum)
#define irdalibEntryNumIrDataReqV50          	((uint32_t)irdalibEntryNumIrDataReqV50Enum)
#define irdalibEntryNumIrAdvanceCreditV50    	((uint32_t)irdalibEntryNumIrAdvanceCreditV50Enum)
#define irdalibEntryNumIrLocalBusyV50        	((uint32_t)irdalibEntryNumIrLocalBusyV50Enum)
#define irdalibEntryNumIrSetConTypeTTPV50    	((uint32_t)irdalibEntryNumIrSetConTypeTTPV50Enum)
#define irdalibEntryNumIrSetConTypeLMPV50    	((uint32_t)irdalibEntryNumIrSetConTypeLMPV50Enum)
#define irdalibEntryNumIrMaxTxSizeV50        	((uint32_t)irdalibEntryNumIrMaxTxSizeV50Enum)
#define irdalibEntryNumIrMaxRxSizeV50        	((uint32_t)irdalibEntryNumIrMaxRxSizeV50Enum)
#define irdalibEntryNumIrIsNoProgressV50     	((uint32_t)irdalibEntryNumIrIsNoProgressV50Enum)
#define irdalibEntryNumIrIsRemoteBusyV50     	((uint32_t)irdalibEntryNumIrIsRemoteBusyV50Enum)
#define irdalibEntryNumIrIsMediaBusyV50      	((uint32_t)irdalibEntryNumIrIsMediaBusyV50Enum)
#define irdalibEntryNumIrIsIrLapConnectedV50 	((uint32_t)irdalibEntryNumIrIsIrLapConnectedV50Enum)
#define irdalibEntryNumIrTestReqV50          	((uint32_t)irdalibEntryNumIrTestReqV50Enum)
#define irdalibEntryNumIrIAS_AddV50          	((uint32_t)irdalibEntryNumIrIAS_AddV50Enum)
#define irdalibEntryNumIrIAS_RemoveV50       	((uint32_t)irdalibEntryNumIrIAS_RemoveV50Enum)
#define irdalibEntryNumIrIAS_QueryV50        	((uint32_t)irdalibEntryNumIrIAS_QueryV50Enum)
#define irdalibEntryNumIrIAS_NextV50         	((uint32_t)irdalibEntryNumIrIAS_NextV50Enum)
#endif // __IRDALIBENTRYNUMS_H__
