/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: libpngEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __LIBPNGENTRYNUMS_H__	// Avoid multiple inclusion
#define __LIBPNGENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum libpngEntryNumTag {
	libpngEntryNumpng_access_version_numberEnum = 0,
	libpngEntryNumpng_set_sig_bytesEnum,
	libpngEntryNumpng_sig_cmpEnum,
	libpngEntryNumpng_check_sigEnum,
	libpngEntryNumpng_create_read_structEnum,
	libpngEntryNumpng_create_write_structEnum,
	libpngEntryNumpng_get_compression_buffer_sizeEnum,
	libpngEntryNumpng_set_compression_buffer_sizeEnum,
	libpngEntryNumpng_reset_zstreamEnum,
	libpngEntryNumpng_write_chunkEnum,
	libpngEntryNumpng_write_chunk_startEnum,
	libpngEntryNumpng_write_chunk_dataEnum,
	libpngEntryNumpng_write_chunk_endEnum,
	libpngEntryNumpng_create_info_structEnum,
	libpngEntryNumpng_info_initEnum,
	libpngEntryNumpng_info_init_3Enum,
	libpngEntryNumpng_write_info_before_PLTEEnum,
	libpngEntryNumpng_write_infoEnum,
	libpngEntryNumpng_read_infoEnum,
	libpngEntryNumpng_convert_from_struct_tmEnum,
	libpngEntryNumpng_convert_from_time_tEnum,
	libpngEntryNumpng_set_expandEnum,
	libpngEntryNumpng_set_gray_1_2_4_to_8Enum,
	libpngEntryNumpng_set_palette_to_rgbEnum,
	libpngEntryNumpng_set_tRNS_to_alphaEnum,
	libpngEntryNumpng_set_bgrEnum,
	libpngEntryNumpng_set_gray_to_rgbEnum,
	libpngEntryNumpng_set_rgb_to_grayEnum,
	libpngEntryNumpng_set_rgb_to_gray_fixedEnum,
	libpngEntryNumpng_get_rgb_to_gray_statusEnum,
	libpngEntryNumpng_build_grayscale_paletteEnum,
	libpngEntryNumpng_set_strip_alphaEnum,
	libpngEntryNumpng_set_swap_alphaEnum,
	libpngEntryNumpng_set_invert_alphaEnum,
	libpngEntryNumpng_set_fillerEnum,
	libpngEntryNumpng_set_swapEnum,
	libpngEntryNumpng_set_packingEnum,
	libpngEntryNumpng_set_packswapEnum,
	libpngEntryNumpng_set_shiftEnum,
	libpngEntryNumpng_set_interlace_handlingEnum,
	libpngEntryNumpng_set_invert_monoEnum,
	libpngEntryNumpng_set_backgroundEnum,
	libpngEntryNumpng_set_strip_16Enum,
	libpngEntryNumpng_set_ditherEnum,
	libpngEntryNumpng_set_gammaEnum,
	libpngEntryNumpng_permit_empty_plteEnum,
	libpngEntryNumpng_set_flushEnum,
	libpngEntryNumpng_write_flushEnum,
	libpngEntryNumpng_start_read_imageEnum,
	libpngEntryNumpng_read_update_infoEnum,
	libpngEntryNumpng_read_rowsEnum,
	libpngEntryNumpng_read_rowEnum,
	libpngEntryNumpng_read_imageEnum,
	libpngEntryNumpng_write_rowEnum,
	libpngEntryNumpng_write_rowsEnum,
	libpngEntryNumpng_write_imageEnum,
	libpngEntryNumpng_write_endEnum,
	libpngEntryNumpng_read_endEnum,
	libpngEntryNumpng_destroy_info_structEnum,
	libpngEntryNumpng_destroy_read_structEnum,
	libpngEntryNumpng_destroy_write_structEnum,
	libpngEntryNumpng_set_crc_actionEnum,
	libpngEntryNumpng_set_filterEnum,
	libpngEntryNumpng_set_filter_heuristicsEnum,
	libpngEntryNumpng_set_compression_levelEnum,
	libpngEntryNumpng_set_compression_mem_levelEnum,
	libpngEntryNumpng_set_compression_strategyEnum,
	libpngEntryNumpng_set_compression_window_bitsEnum,
	libpngEntryNumpng_set_compression_methodEnum,
	libpngEntryNumpng_set_error_fnEnum,
	libpngEntryNumpng_get_error_ptrEnum,
	libpngEntryNumpng_set_write_fnEnum,
	libpngEntryNumpng_set_read_fnEnum,
	libpngEntryNumpng_get_io_ptrEnum,
	libpngEntryNumpng_set_read_status_fnEnum,
	libpngEntryNumpng_set_write_status_fnEnum,
	libpngEntryNumpng_set_read_user_transform_fnEnum,
	libpngEntryNumpng_set_write_user_transform_fnEnum,
	libpngEntryNumpng_set_user_transform_infoEnum,
	libpngEntryNumpng_get_user_transform_ptrEnum,
	libpngEntryNumpng_set_read_user_chunk_fnEnum,
	libpngEntryNumpng_get_user_chunk_ptrEnum,
	libpngEntryNumpng_set_progressive_read_fnEnum,
	libpngEntryNumpng_get_progressive_ptrEnum,
	libpngEntryNumpng_process_dataEnum,
	libpngEntryNumpng_progressive_combine_rowEnum,
	libpngEntryNumpng_mallocEnum,
	libpngEntryNumpng_freeEnum,
	libpngEntryNumpng_free_dataEnum,
	libpngEntryNumpng_data_freerEnum,
	libpngEntryNumpng_memcpy_checkEnum,
	libpngEntryNumpng_memset_checkEnum,
	libpngEntryNumpng_errorEnum,
	libpngEntryNumpng_chunk_errorEnum,
	libpngEntryNumpng_warningEnum,
	libpngEntryNumpng_chunk_warningEnum,
	libpngEntryNumpng_get_validEnum,
	libpngEntryNumpng_get_rowbytesEnum,
	libpngEntryNumpng_get_rowsEnum,
	libpngEntryNumpng_set_rowsEnum,
	libpngEntryNumpng_get_channelsEnum,
	libpngEntryNumpng_get_image_widthEnum,
	libpngEntryNumpng_get_image_heightEnum,
	libpngEntryNumpng_get_bit_depthEnum,
	libpngEntryNumpng_get_color_typeEnum,
	libpngEntryNumpng_get_filter_typeEnum,
	libpngEntryNumpng_get_interlace_typeEnum,
	libpngEntryNumpng_get_compression_typeEnum,
	libpngEntryNumpng_get_pixels_per_meterEnum,
	libpngEntryNumpng_get_x_pixels_per_meterEnum,
	libpngEntryNumpng_get_y_pixels_per_meterEnum,
	libpngEntryNumpng_get_pixel_aspect_ratioEnum,
	libpngEntryNumpng_get_x_offset_pixelsEnum,
	libpngEntryNumpng_get_y_offset_pixelsEnum,
	libpngEntryNumpng_get_x_offset_micronsEnum,
	libpngEntryNumpng_get_y_offset_micronsEnum,
	libpngEntryNumpng_get_signatureEnum,
	libpngEntryNumpng_get_bKGDEnum,
	libpngEntryNumpng_set_bKGDEnum,
	libpngEntryNumpng_get_cHRMEnum,
	libpngEntryNumpng_get_cHRM_fixedEnum,
	libpngEntryNumpng_set_cHRMEnum,
	libpngEntryNumpng_set_cHRM_fixedEnum,
	libpngEntryNumpng_get_gAMAEnum,
	libpngEntryNumpng_get_gAMA_fixedEnum,
	libpngEntryNumpng_set_gAMAEnum,
	libpngEntryNumpng_set_gAMA_fixedEnum,
	libpngEntryNumpng_get_hISTEnum,
	libpngEntryNumpng_set_hISTEnum,
	libpngEntryNumpng_get_IHDREnum,
	libpngEntryNumpng_set_IHDREnum,
	libpngEntryNumpng_get_oFFsEnum,
	libpngEntryNumpng_set_oFFsEnum,
	libpngEntryNumpng_get_pCALEnum,
	libpngEntryNumpng_set_pCALEnum,
	libpngEntryNumpng_get_pHYsEnum,
	libpngEntryNumpng_set_pHYsEnum,
	libpngEntryNumpng_get_PLTEEnum,
	libpngEntryNumpng_set_PLTEEnum,
	libpngEntryNumpng_get_sBITEnum,
	libpngEntryNumpng_set_sBITEnum,
	libpngEntryNumpng_get_sRGBEnum,
	libpngEntryNumpng_set_sRGBEnum,
	libpngEntryNumpng_set_sRGB_gAMA_and_cHRMEnum,
	libpngEntryNumpng_get_iCCPEnum,
	libpngEntryNumpng_set_iCCPEnum,
	libpngEntryNumpng_get_sPLTEnum,
	libpngEntryNumpng_set_sPLTEnum,
	libpngEntryNumpng_get_textEnum,
	libpngEntryNumpng_set_textEnum,
	libpngEntryNumpng_get_tIMEEnum,
	libpngEntryNumpng_set_tIMEEnum,
	libpngEntryNumpng_get_tRNSEnum,
	libpngEntryNumpng_set_tRNSEnum,
	libpngEntryNumpng_get_sCALEnum,
	libpngEntryNumpng_set_sCALEnum,
	libpngEntryNumpng_set_keep_unknown_chunksEnum,
	libpngEntryNumpng_set_unknown_chunksEnum,
	libpngEntryNumpng_set_unknown_chunk_locationEnum,
	libpngEntryNumpng_get_unknown_chunksEnum,
	libpngEntryNumpng_set_invalidEnum,
	libpngEntryNumpng_read_pngEnum,
	libpngEntryNumpng_write_pngEnum,
	libpngEntryNumpng_get_copyrightEnum,
	libpngEntryNumpng_get_header_verEnum,
	libpngEntryNumpng_get_header_versionEnum,
	libpngEntryNumpng_get_libpng_verEnum,
	libpngEntryNumpng_mmx_supportEnum,
	libpngEntryNumpng_read_initEnum,
	libpngEntryNumpng_read_init_3Enum,
	libpngEntryNumpng_read_init_2Enum,
	libpngEntryNumpng_write_initEnum,
	libpngEntryNumpng_write_init_3Enum,
	libpngEntryNumpng_write_init_2Enum,
};

#define libpngEntryNumpng_access_version_number        	((uint32_t)libpngEntryNumpng_access_version_numberEnum)
#define libpngEntryNumpng_set_sig_bytes                	((uint32_t)libpngEntryNumpng_set_sig_bytesEnum)
#define libpngEntryNumpng_sig_cmp                      	((uint32_t)libpngEntryNumpng_sig_cmpEnum)
#define libpngEntryNumpng_check_sig                    	((uint32_t)libpngEntryNumpng_check_sigEnum)
#define libpngEntryNumpng_create_read_struct           	((uint32_t)libpngEntryNumpng_create_read_structEnum)
#define libpngEntryNumpng_create_write_struct          	((uint32_t)libpngEntryNumpng_create_write_structEnum)
#define libpngEntryNumpng_get_compression_buffer_size  	((uint32_t)libpngEntryNumpng_get_compression_buffer_sizeEnum)
#define libpngEntryNumpng_set_compression_buffer_size  	((uint32_t)libpngEntryNumpng_set_compression_buffer_sizeEnum)
#define libpngEntryNumpng_reset_zstream                	((uint32_t)libpngEntryNumpng_reset_zstreamEnum)
#define libpngEntryNumpng_write_chunk                  	((uint32_t)libpngEntryNumpng_write_chunkEnum)
#define libpngEntryNumpng_write_chunk_start            	((uint32_t)libpngEntryNumpng_write_chunk_startEnum)
#define libpngEntryNumpng_write_chunk_data             	((uint32_t)libpngEntryNumpng_write_chunk_dataEnum)
#define libpngEntryNumpng_write_chunk_end              	((uint32_t)libpngEntryNumpng_write_chunk_endEnum)
#define libpngEntryNumpng_create_info_struct           	((uint32_t)libpngEntryNumpng_create_info_structEnum)
#define libpngEntryNumpng_info_init                    	((uint32_t)libpngEntryNumpng_info_initEnum)
#define libpngEntryNumpng_info_init_3                  	((uint32_t)libpngEntryNumpng_info_init_3Enum)
#define libpngEntryNumpng_write_info_before_PLTE       	((uint32_t)libpngEntryNumpng_write_info_before_PLTEEnum)
#define libpngEntryNumpng_write_info                   	((uint32_t)libpngEntryNumpng_write_infoEnum)
#define libpngEntryNumpng_read_info                    	((uint32_t)libpngEntryNumpng_read_infoEnum)
#define libpngEntryNumpng_convert_from_struct_tm       	((uint32_t)libpngEntryNumpng_convert_from_struct_tmEnum)
#define libpngEntryNumpng_convert_from_time_t          	((uint32_t)libpngEntryNumpng_convert_from_time_tEnum)
#define libpngEntryNumpng_set_expand                   	((uint32_t)libpngEntryNumpng_set_expandEnum)
#define libpngEntryNumpng_set_gray_1_2_4_to_8          	((uint32_t)libpngEntryNumpng_set_gray_1_2_4_to_8Enum)
#define libpngEntryNumpng_set_palette_to_rgb           	((uint32_t)libpngEntryNumpng_set_palette_to_rgbEnum)
#define libpngEntryNumpng_set_tRNS_to_alpha            	((uint32_t)libpngEntryNumpng_set_tRNS_to_alphaEnum)
#define libpngEntryNumpng_set_bgr                      	((uint32_t)libpngEntryNumpng_set_bgrEnum)
#define libpngEntryNumpng_set_gray_to_rgb              	((uint32_t)libpngEntryNumpng_set_gray_to_rgbEnum)
#define libpngEntryNumpng_set_rgb_to_gray              	((uint32_t)libpngEntryNumpng_set_rgb_to_grayEnum)
#define libpngEntryNumpng_set_rgb_to_gray_fixed        	((uint32_t)libpngEntryNumpng_set_rgb_to_gray_fixedEnum)
#define libpngEntryNumpng_get_rgb_to_gray_status       	((uint32_t)libpngEntryNumpng_get_rgb_to_gray_statusEnum)
#define libpngEntryNumpng_build_grayscale_palette      	((uint32_t)libpngEntryNumpng_build_grayscale_paletteEnum)
#define libpngEntryNumpng_set_strip_alpha              	((uint32_t)libpngEntryNumpng_set_strip_alphaEnum)
#define libpngEntryNumpng_set_swap_alpha               	((uint32_t)libpngEntryNumpng_set_swap_alphaEnum)
#define libpngEntryNumpng_set_invert_alpha             	((uint32_t)libpngEntryNumpng_set_invert_alphaEnum)
#define libpngEntryNumpng_set_filler                   	((uint32_t)libpngEntryNumpng_set_fillerEnum)
#define libpngEntryNumpng_set_swap                     	((uint32_t)libpngEntryNumpng_set_swapEnum)
#define libpngEntryNumpng_set_packing                  	((uint32_t)libpngEntryNumpng_set_packingEnum)
#define libpngEntryNumpng_set_packswap                 	((uint32_t)libpngEntryNumpng_set_packswapEnum)
#define libpngEntryNumpng_set_shift                    	((uint32_t)libpngEntryNumpng_set_shiftEnum)
#define libpngEntryNumpng_set_interlace_handling       	((uint32_t)libpngEntryNumpng_set_interlace_handlingEnum)
#define libpngEntryNumpng_set_invert_mono              	((uint32_t)libpngEntryNumpng_set_invert_monoEnum)
#define libpngEntryNumpng_set_background               	((uint32_t)libpngEntryNumpng_set_backgroundEnum)
#define libpngEntryNumpng_set_strip_16                 	((uint32_t)libpngEntryNumpng_set_strip_16Enum)
#define libpngEntryNumpng_set_dither                   	((uint32_t)libpngEntryNumpng_set_ditherEnum)
#define libpngEntryNumpng_set_gamma                    	((uint32_t)libpngEntryNumpng_set_gammaEnum)
#define libpngEntryNumpng_permit_empty_plte            	((uint32_t)libpngEntryNumpng_permit_empty_plteEnum)
#define libpngEntryNumpng_set_flush                    	((uint32_t)libpngEntryNumpng_set_flushEnum)
#define libpngEntryNumpng_write_flush                  	((uint32_t)libpngEntryNumpng_write_flushEnum)
#define libpngEntryNumpng_start_read_image             	((uint32_t)libpngEntryNumpng_start_read_imageEnum)
#define libpngEntryNumpng_read_update_info             	((uint32_t)libpngEntryNumpng_read_update_infoEnum)
#define libpngEntryNumpng_read_rows                    	((uint32_t)libpngEntryNumpng_read_rowsEnum)
#define libpngEntryNumpng_read_row                     	((uint32_t)libpngEntryNumpng_read_rowEnum)
#define libpngEntryNumpng_read_image                   	((uint32_t)libpngEntryNumpng_read_imageEnum)
#define libpngEntryNumpng_write_row                    	((uint32_t)libpngEntryNumpng_write_rowEnum)
#define libpngEntryNumpng_write_rows                   	((uint32_t)libpngEntryNumpng_write_rowsEnum)
#define libpngEntryNumpng_write_image                  	((uint32_t)libpngEntryNumpng_write_imageEnum)
#define libpngEntryNumpng_write_end                    	((uint32_t)libpngEntryNumpng_write_endEnum)
#define libpngEntryNumpng_read_end                     	((uint32_t)libpngEntryNumpng_read_endEnum)
#define libpngEntryNumpng_destroy_info_struct          	((uint32_t)libpngEntryNumpng_destroy_info_structEnum)
#define libpngEntryNumpng_destroy_read_struct          	((uint32_t)libpngEntryNumpng_destroy_read_structEnum)
#define libpngEntryNumpng_destroy_write_struct         	((uint32_t)libpngEntryNumpng_destroy_write_structEnum)
#define libpngEntryNumpng_set_crc_action               	((uint32_t)libpngEntryNumpng_set_crc_actionEnum)
#define libpngEntryNumpng_set_filter                   	((uint32_t)libpngEntryNumpng_set_filterEnum)
#define libpngEntryNumpng_set_filter_heuristics        	((uint32_t)libpngEntryNumpng_set_filter_heuristicsEnum)
#define libpngEntryNumpng_set_compression_level        	((uint32_t)libpngEntryNumpng_set_compression_levelEnum)
#define libpngEntryNumpng_set_compression_mem_level    	((uint32_t)libpngEntryNumpng_set_compression_mem_levelEnum)
#define libpngEntryNumpng_set_compression_strategy     	((uint32_t)libpngEntryNumpng_set_compression_strategyEnum)
#define libpngEntryNumpng_set_compression_window_bits  	((uint32_t)libpngEntryNumpng_set_compression_window_bitsEnum)
#define libpngEntryNumpng_set_compression_method       	((uint32_t)libpngEntryNumpng_set_compression_methodEnum)
#define libpngEntryNumpng_set_error_fn                 	((uint32_t)libpngEntryNumpng_set_error_fnEnum)
#define libpngEntryNumpng_get_error_ptr                	((uint32_t)libpngEntryNumpng_get_error_ptrEnum)
#define libpngEntryNumpng_set_write_fn                 	((uint32_t)libpngEntryNumpng_set_write_fnEnum)
#define libpngEntryNumpng_set_read_fn                  	((uint32_t)libpngEntryNumpng_set_read_fnEnum)
#define libpngEntryNumpng_get_io_ptr                   	((uint32_t)libpngEntryNumpng_get_io_ptrEnum)
#define libpngEntryNumpng_set_read_status_fn           	((uint32_t)libpngEntryNumpng_set_read_status_fnEnum)
#define libpngEntryNumpng_set_write_status_fn          	((uint32_t)libpngEntryNumpng_set_write_status_fnEnum)
#define libpngEntryNumpng_set_read_user_transform_fn   	((uint32_t)libpngEntryNumpng_set_read_user_transform_fnEnum)
#define libpngEntryNumpng_set_write_user_transform_fn  	((uint32_t)libpngEntryNumpng_set_write_user_transform_fnEnum)
#define libpngEntryNumpng_set_user_transform_info      	((uint32_t)libpngEntryNumpng_set_user_transform_infoEnum)
#define libpngEntryNumpng_get_user_transform_ptr       	((uint32_t)libpngEntryNumpng_get_user_transform_ptrEnum)
#define libpngEntryNumpng_set_read_user_chunk_fn       	((uint32_t)libpngEntryNumpng_set_read_user_chunk_fnEnum)
#define libpngEntryNumpng_get_user_chunk_ptr           	((uint32_t)libpngEntryNumpng_get_user_chunk_ptrEnum)
#define libpngEntryNumpng_set_progressive_read_fn      	((uint32_t)libpngEntryNumpng_set_progressive_read_fnEnum)
#define libpngEntryNumpng_get_progressive_ptr          	((uint32_t)libpngEntryNumpng_get_progressive_ptrEnum)
#define libpngEntryNumpng_process_data                 	((uint32_t)libpngEntryNumpng_process_dataEnum)
#define libpngEntryNumpng_progressive_combine_row      	((uint32_t)libpngEntryNumpng_progressive_combine_rowEnum)
#define libpngEntryNumpng_malloc                       	((uint32_t)libpngEntryNumpng_mallocEnum)
#define libpngEntryNumpng_free                         	((uint32_t)libpngEntryNumpng_freeEnum)
#define libpngEntryNumpng_free_data                    	((uint32_t)libpngEntryNumpng_free_dataEnum)
#define libpngEntryNumpng_data_freer                   	((uint32_t)libpngEntryNumpng_data_freerEnum)
#define libpngEntryNumpng_memcpy_check                 	((uint32_t)libpngEntryNumpng_memcpy_checkEnum)
#define libpngEntryNumpng_memset_check                 	((uint32_t)libpngEntryNumpng_memset_checkEnum)
#define libpngEntryNumpng_error                        	((uint32_t)libpngEntryNumpng_errorEnum)
#define libpngEntryNumpng_chunk_error                  	((uint32_t)libpngEntryNumpng_chunk_errorEnum)
#define libpngEntryNumpng_warning                      	((uint32_t)libpngEntryNumpng_warningEnum)
#define libpngEntryNumpng_chunk_warning                	((uint32_t)libpngEntryNumpng_chunk_warningEnum)
#define libpngEntryNumpng_get_valid                    	((uint32_t)libpngEntryNumpng_get_validEnum)
#define libpngEntryNumpng_get_rowbytes                 	((uint32_t)libpngEntryNumpng_get_rowbytesEnum)
#define libpngEntryNumpng_get_rows                     	((uint32_t)libpngEntryNumpng_get_rowsEnum)
#define libpngEntryNumpng_set_rows                     	((uint32_t)libpngEntryNumpng_set_rowsEnum)
#define libpngEntryNumpng_get_channels                 	((uint32_t)libpngEntryNumpng_get_channelsEnum)
#define libpngEntryNumpng_get_image_width              	((uint32_t)libpngEntryNumpng_get_image_widthEnum)
#define libpngEntryNumpng_get_image_height             	((uint32_t)libpngEntryNumpng_get_image_heightEnum)
#define libpngEntryNumpng_get_bit_depth                	((uint32_t)libpngEntryNumpng_get_bit_depthEnum)
#define libpngEntryNumpng_get_color_type               	((uint32_t)libpngEntryNumpng_get_color_typeEnum)
#define libpngEntryNumpng_get_filter_type              	((uint32_t)libpngEntryNumpng_get_filter_typeEnum)
#define libpngEntryNumpng_get_interlace_type           	((uint32_t)libpngEntryNumpng_get_interlace_typeEnum)
#define libpngEntryNumpng_get_compression_type         	((uint32_t)libpngEntryNumpng_get_compression_typeEnum)
#define libpngEntryNumpng_get_pixels_per_meter         	((uint32_t)libpngEntryNumpng_get_pixels_per_meterEnum)
#define libpngEntryNumpng_get_x_pixels_per_meter       	((uint32_t)libpngEntryNumpng_get_x_pixels_per_meterEnum)
#define libpngEntryNumpng_get_y_pixels_per_meter       	((uint32_t)libpngEntryNumpng_get_y_pixels_per_meterEnum)
#define libpngEntryNumpng_get_pixel_aspect_ratio       	((uint32_t)libpngEntryNumpng_get_pixel_aspect_ratioEnum)
#define libpngEntryNumpng_get_x_offset_pixels          	((uint32_t)libpngEntryNumpng_get_x_offset_pixelsEnum)
#define libpngEntryNumpng_get_y_offset_pixels          	((uint32_t)libpngEntryNumpng_get_y_offset_pixelsEnum)
#define libpngEntryNumpng_get_x_offset_microns         	((uint32_t)libpngEntryNumpng_get_x_offset_micronsEnum)
#define libpngEntryNumpng_get_y_offset_microns         	((uint32_t)libpngEntryNumpng_get_y_offset_micronsEnum)
#define libpngEntryNumpng_get_signature                	((uint32_t)libpngEntryNumpng_get_signatureEnum)
#define libpngEntryNumpng_get_bKGD                     	((uint32_t)libpngEntryNumpng_get_bKGDEnum)
#define libpngEntryNumpng_set_bKGD                     	((uint32_t)libpngEntryNumpng_set_bKGDEnum)
#define libpngEntryNumpng_get_cHRM                     	((uint32_t)libpngEntryNumpng_get_cHRMEnum)
#define libpngEntryNumpng_get_cHRM_fixed               	((uint32_t)libpngEntryNumpng_get_cHRM_fixedEnum)
#define libpngEntryNumpng_set_cHRM                     	((uint32_t)libpngEntryNumpng_set_cHRMEnum)
#define libpngEntryNumpng_set_cHRM_fixed               	((uint32_t)libpngEntryNumpng_set_cHRM_fixedEnum)
#define libpngEntryNumpng_get_gAMA                     	((uint32_t)libpngEntryNumpng_get_gAMAEnum)
#define libpngEntryNumpng_get_gAMA_fixed               	((uint32_t)libpngEntryNumpng_get_gAMA_fixedEnum)
#define libpngEntryNumpng_set_gAMA                     	((uint32_t)libpngEntryNumpng_set_gAMAEnum)
#define libpngEntryNumpng_set_gAMA_fixed               	((uint32_t)libpngEntryNumpng_set_gAMA_fixedEnum)
#define libpngEntryNumpng_get_hIST                     	((uint32_t)libpngEntryNumpng_get_hISTEnum)
#define libpngEntryNumpng_set_hIST                     	((uint32_t)libpngEntryNumpng_set_hISTEnum)
#define libpngEntryNumpng_get_IHDR                     	((uint32_t)libpngEntryNumpng_get_IHDREnum)
#define libpngEntryNumpng_set_IHDR                     	((uint32_t)libpngEntryNumpng_set_IHDREnum)
#define libpngEntryNumpng_get_oFFs                     	((uint32_t)libpngEntryNumpng_get_oFFsEnum)
#define libpngEntryNumpng_set_oFFs                     	((uint32_t)libpngEntryNumpng_set_oFFsEnum)
#define libpngEntryNumpng_get_pCAL                     	((uint32_t)libpngEntryNumpng_get_pCALEnum)
#define libpngEntryNumpng_set_pCAL                     	((uint32_t)libpngEntryNumpng_set_pCALEnum)
#define libpngEntryNumpng_get_pHYs                     	((uint32_t)libpngEntryNumpng_get_pHYsEnum)
#define libpngEntryNumpng_set_pHYs                     	((uint32_t)libpngEntryNumpng_set_pHYsEnum)
#define libpngEntryNumpng_get_PLTE                     	((uint32_t)libpngEntryNumpng_get_PLTEEnum)
#define libpngEntryNumpng_set_PLTE                     	((uint32_t)libpngEntryNumpng_set_PLTEEnum)
#define libpngEntryNumpng_get_sBIT                     	((uint32_t)libpngEntryNumpng_get_sBITEnum)
#define libpngEntryNumpng_set_sBIT                     	((uint32_t)libpngEntryNumpng_set_sBITEnum)
#define libpngEntryNumpng_get_sRGB                     	((uint32_t)libpngEntryNumpng_get_sRGBEnum)
#define libpngEntryNumpng_set_sRGB                     	((uint32_t)libpngEntryNumpng_set_sRGBEnum)
#define libpngEntryNumpng_set_sRGB_gAMA_and_cHRM       	((uint32_t)libpngEntryNumpng_set_sRGB_gAMA_and_cHRMEnum)
#define libpngEntryNumpng_get_iCCP                     	((uint32_t)libpngEntryNumpng_get_iCCPEnum)
#define libpngEntryNumpng_set_iCCP                     	((uint32_t)libpngEntryNumpng_set_iCCPEnum)
#define libpngEntryNumpng_get_sPLT                     	((uint32_t)libpngEntryNumpng_get_sPLTEnum)
#define libpngEntryNumpng_set_sPLT                     	((uint32_t)libpngEntryNumpng_set_sPLTEnum)
#define libpngEntryNumpng_get_text                     	((uint32_t)libpngEntryNumpng_get_textEnum)
#define libpngEntryNumpng_set_text                     	((uint32_t)libpngEntryNumpng_set_textEnum)
#define libpngEntryNumpng_get_tIME                     	((uint32_t)libpngEntryNumpng_get_tIMEEnum)
#define libpngEntryNumpng_set_tIME                     	((uint32_t)libpngEntryNumpng_set_tIMEEnum)
#define libpngEntryNumpng_get_tRNS                     	((uint32_t)libpngEntryNumpng_get_tRNSEnum)
#define libpngEntryNumpng_set_tRNS                     	((uint32_t)libpngEntryNumpng_set_tRNSEnum)
#define libpngEntryNumpng_get_sCAL                     	((uint32_t)libpngEntryNumpng_get_sCALEnum)
#define libpngEntryNumpng_set_sCAL                     	((uint32_t)libpngEntryNumpng_set_sCALEnum)
#define libpngEntryNumpng_set_keep_unknown_chunks      	((uint32_t)libpngEntryNumpng_set_keep_unknown_chunksEnum)
#define libpngEntryNumpng_set_unknown_chunks           	((uint32_t)libpngEntryNumpng_set_unknown_chunksEnum)
#define libpngEntryNumpng_set_unknown_chunk_location   	((uint32_t)libpngEntryNumpng_set_unknown_chunk_locationEnum)
#define libpngEntryNumpng_get_unknown_chunks           	((uint32_t)libpngEntryNumpng_get_unknown_chunksEnum)
#define libpngEntryNumpng_set_invalid                  	((uint32_t)libpngEntryNumpng_set_invalidEnum)
#define libpngEntryNumpng_read_png                     	((uint32_t)libpngEntryNumpng_read_pngEnum)
#define libpngEntryNumpng_write_png                    	((uint32_t)libpngEntryNumpng_write_pngEnum)
#define libpngEntryNumpng_get_copyright                	((uint32_t)libpngEntryNumpng_get_copyrightEnum)
#define libpngEntryNumpng_get_header_ver               	((uint32_t)libpngEntryNumpng_get_header_verEnum)
#define libpngEntryNumpng_get_header_version           	((uint32_t)libpngEntryNumpng_get_header_versionEnum)
#define libpngEntryNumpng_get_libpng_ver               	((uint32_t)libpngEntryNumpng_get_libpng_verEnum)
#define libpngEntryNumpng_mmx_support                  	((uint32_t)libpngEntryNumpng_mmx_supportEnum)
#define libpngEntryNumpng_read_init                    	((uint32_t)libpngEntryNumpng_read_initEnum)
#define libpngEntryNumpng_read_init_3                  	((uint32_t)libpngEntryNumpng_read_init_3Enum)
#define libpngEntryNumpng_read_init_2                  	((uint32_t)libpngEntryNumpng_read_init_2Enum)
#define libpngEntryNumpng_write_init                   	((uint32_t)libpngEntryNumpng_write_initEnum)
#define libpngEntryNumpng_write_init_3                 	((uint32_t)libpngEntryNumpng_write_init_3Enum)
#define libpngEntryNumpng_write_init_2                 	((uint32_t)libpngEntryNumpng_write_init_2Enum)
#endif // __LIBPNGENTRYNUMS_H__
