/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: ObexServiceLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __OBEXSERVICELIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __OBEXSERVICELIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum obexservicelibEntryNumTag {
	obexservicelibEntryNumObexEnableReceiveEnum = 0,
	obexservicelibEntryNumObexIsReceiveEnabledEnum,
};

#define obexservicelibEntryNumObexEnableReceive   	((uint32_t)obexservicelibEntryNumObexEnableReceiveEnum)
#define obexservicelibEntryNumObexIsReceiveEnabled	((uint32_t)obexservicelibEntryNumObexIsReceiveEnabledEnum)
#endif // __OBEXSERVICELIBENTRYNUMS_H__
