/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: PdiLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:33 2004
 *****************************************************************************/
#ifndef __PDILIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __PDILIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum pdilibEntryNumTag {
	pdilibEntryNumPdiLibOpenEnum = 0,
	pdilibEntryNumPdiLibCloseEnum,
	pdilibEntryNumPdiReaderNewEnum,
	pdilibEntryNumPdiReaderDeleteEnum,
	pdilibEntryNumPdiWriterNewEnum,
	pdilibEntryNumPdiWriterDeleteEnum,
	pdilibEntryNumPdiReadPropertyEnum,
	pdilibEntryNumPdiReadPropertyFieldEnum,
	pdilibEntryNumPdiReadPropertyNameEnum,
	pdilibEntryNumPdiReadParameterEnum,
	pdilibEntryNumPdiDefineResizingEnum,
	pdilibEntryNumPdiEnterObjectEnum,
	pdilibEntryNumPdiWriteBeginObjectEnum,
	pdilibEntryNumPdiWritePropertyEnum,
	pdilibEntryNumPdiWriteParameterEnum,
	pdilibEntryNumPdiWritePropertyValueEnum,
	pdilibEntryNumPdiWritePropertyFieldsEnum,
	pdilibEntryNumPdiWritePropertyBinaryValueEnum,
	pdilibEntryNumPdiSetEncodingEnum,
	pdilibEntryNumPdiSetCharsetEnum,
	pdilibEntryNumPdiWritePropertyStrEnum,
	pdilibEntryNumPdiWriteParameterStrEnum,
	pdilibEntryNumPdiDefineReaderDictionaryEnum,
	pdilibEntryNumPdiDefineWriterDictionaryEnum,
};

#define pdilibEntryNumPdiLibOpen                  	((uint32_t)pdilibEntryNumPdiLibOpenEnum)
#define pdilibEntryNumPdiLibClose                 	((uint32_t)pdilibEntryNumPdiLibCloseEnum)
#define pdilibEntryNumPdiReaderNew                	((uint32_t)pdilibEntryNumPdiReaderNewEnum)
#define pdilibEntryNumPdiReaderDelete             	((uint32_t)pdilibEntryNumPdiReaderDeleteEnum)
#define pdilibEntryNumPdiWriterNew                	((uint32_t)pdilibEntryNumPdiWriterNewEnum)
#define pdilibEntryNumPdiWriterDelete             	((uint32_t)pdilibEntryNumPdiWriterDeleteEnum)
#define pdilibEntryNumPdiReadProperty             	((uint32_t)pdilibEntryNumPdiReadPropertyEnum)
#define pdilibEntryNumPdiReadPropertyField        	((uint32_t)pdilibEntryNumPdiReadPropertyFieldEnum)
#define pdilibEntryNumPdiReadPropertyName         	((uint32_t)pdilibEntryNumPdiReadPropertyNameEnum)
#define pdilibEntryNumPdiReadParameter            	((uint32_t)pdilibEntryNumPdiReadParameterEnum)
#define pdilibEntryNumPdiDefineResizing           	((uint32_t)pdilibEntryNumPdiDefineResizingEnum)
#define pdilibEntryNumPdiEnterObject              	((uint32_t)pdilibEntryNumPdiEnterObjectEnum)
#define pdilibEntryNumPdiWriteBeginObject         	((uint32_t)pdilibEntryNumPdiWriteBeginObjectEnum)
#define pdilibEntryNumPdiWriteProperty            	((uint32_t)pdilibEntryNumPdiWritePropertyEnum)
#define pdilibEntryNumPdiWriteParameter           	((uint32_t)pdilibEntryNumPdiWriteParameterEnum)
#define pdilibEntryNumPdiWritePropertyValue       	((uint32_t)pdilibEntryNumPdiWritePropertyValueEnum)
#define pdilibEntryNumPdiWritePropertyFields      	((uint32_t)pdilibEntryNumPdiWritePropertyFieldsEnum)
#define pdilibEntryNumPdiWritePropertyBinaryValue 	((uint32_t)pdilibEntryNumPdiWritePropertyBinaryValueEnum)
#define pdilibEntryNumPdiSetEncoding              	((uint32_t)pdilibEntryNumPdiSetEncodingEnum)
#define pdilibEntryNumPdiSetCharset               	((uint32_t)pdilibEntryNumPdiSetCharsetEnum)
#define pdilibEntryNumPdiWritePropertyStr         	((uint32_t)pdilibEntryNumPdiWritePropertyStrEnum)
#define pdilibEntryNumPdiWriteParameterStr        	((uint32_t)pdilibEntryNumPdiWriteParameterStrEnum)
#define pdilibEntryNumPdiDefineReaderDictionary   	((uint32_t)pdilibEntryNumPdiDefineReaderDictionaryEnum)
#define pdilibEntryNumPdiDefineWriterDictionary   	((uint32_t)pdilibEntryNumPdiDefineWriterDictionaryEnum)
#endif // __PDILIBENTRYNUMS_H__
