/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: PINSLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:33 2004
 *****************************************************************************/
#ifndef __PINSLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __PINSLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum pinslibEntryNumTag {
	pinslibEntryNumPINGetInputAreaStateEnum = 0,
	pinslibEntryNumPINSetInputAreaStateEnum,
	pinslibEntryNumPINGetInputTriggerStateV50Enum,
	pinslibEntryNumPINSetInputTriggerStateV50Enum,
	pinslibEntryNumPINAltInputSystemEnabledEnum,
	pinslibEntryNumPINGetCurrentPinletNameEnum,
	pinslibEntryNumPINSwitchToPinletEnum,
	pinslibEntryNumPINCountPinletsEnum,
	pinslibEntryNumPINGetPinletInfoEnum,
	pinslibEntryNumPINSetInputModeEnum,
	pinslibEntryNumPINGetInputModeEnum,
	pinslibEntryNumPINClearPinletStateEnum,
	pinslibEntryNumPINShowReferenceDialogEnum,
	pinslibEntryNumPINFeedCharEnum,
	pinslibEntryNumPINFeedStringEnum,
	pinslibEntryNumPINSetDefaultPinletEnum,
	pinslibEntryNumPINGetDefaultPinletEnum,
	pinslibEntryNumGrfProcessStrokeEnum,
	pinslibEntryNumGrfFieldChangeEnum,
	pinslibEntryNumGrfGetStateEnum,
	pinslibEntryNumGrfSetStateEnum,
	pinslibEntryNumGrfFlushPointsEnum,
	pinslibEntryNumGrfAddPointEnum,
	pinslibEntryNumGrfInitStateEnum,
	pinslibEntryNumGrfCleanStateEnum,
	pinslibEntryNumGrfMatchEnum,
	pinslibEntryNumGrfGetMacroEnum,
	pinslibEntryNumGrfGetAndExpandMacroEnum,
	pinslibEntryNumGrfFilterPointsEnum,
	pinslibEntryNumGrfGetNumPointsEnum,
	pinslibEntryNumGrfGetPointEnum,
	pinslibEntryNumGrfFindBranchEnum,
	pinslibEntryNumGrfMatchGlyphEnum,
	pinslibEntryNumGrfGetGlyphMappingEnum,
	pinslibEntryNumGrfGetMacroNameEnum,
	pinslibEntryNumGrfDeleteMacroEnum,
	pinslibEntryNumGrfAddMacroEnum,
	pinslibEntryNumSysGraffitiReferenceDialogEnum,
	pinslibEntryNumEvtProcessSoftKeyStrokeEnum,
	pinslibEntryNumEvtGetPenBtnListEnum,
	pinslibEntryNumEvtGetSilkscreenAreaListEnum,
	pinslibEntryNumEvtEnableGraffitiEnum,
};

#define pinslibEntryNumPINGetInputAreaState       	((uint32_t)pinslibEntryNumPINGetInputAreaStateEnum)
#define pinslibEntryNumPINSetInputAreaState       	((uint32_t)pinslibEntryNumPINSetInputAreaStateEnum)
#define pinslibEntryNumPINGetInputTriggerStateV50 	((uint32_t)pinslibEntryNumPINGetInputTriggerStateV50Enum)
#define pinslibEntryNumPINSetInputTriggerStateV50 	((uint32_t)pinslibEntryNumPINSetInputTriggerStateV50Enum)
#define pinslibEntryNumPINAltInputSystemEnabled   	((uint32_t)pinslibEntryNumPINAltInputSystemEnabledEnum)
#define pinslibEntryNumPINGetCurrentPinletName    	((uint32_t)pinslibEntryNumPINGetCurrentPinletNameEnum)
#define pinslibEntryNumPINSwitchToPinlet          	((uint32_t)pinslibEntryNumPINSwitchToPinletEnum)
#define pinslibEntryNumPINCountPinlets            	((uint32_t)pinslibEntryNumPINCountPinletsEnum)
#define pinslibEntryNumPINGetPinletInfo           	((uint32_t)pinslibEntryNumPINGetPinletInfoEnum)
#define pinslibEntryNumPINSetInputMode            	((uint32_t)pinslibEntryNumPINSetInputModeEnum)
#define pinslibEntryNumPINGetInputMode            	((uint32_t)pinslibEntryNumPINGetInputModeEnum)
#define pinslibEntryNumPINClearPinletState        	((uint32_t)pinslibEntryNumPINClearPinletStateEnum)
#define pinslibEntryNumPINShowReferenceDialog     	((uint32_t)pinslibEntryNumPINShowReferenceDialogEnum)
#define pinslibEntryNumPINFeedChar                	((uint32_t)pinslibEntryNumPINFeedCharEnum)
#define pinslibEntryNumPINFeedString              	((uint32_t)pinslibEntryNumPINFeedStringEnum)
#define pinslibEntryNumPINSetDefaultPinlet        	((uint32_t)pinslibEntryNumPINSetDefaultPinletEnum)
#define pinslibEntryNumPINGetDefaultPinlet        	((uint32_t)pinslibEntryNumPINGetDefaultPinletEnum)
#define pinslibEntryNumGrfProcessStroke           	((uint32_t)pinslibEntryNumGrfProcessStrokeEnum)
#define pinslibEntryNumGrfFieldChange             	((uint32_t)pinslibEntryNumGrfFieldChangeEnum)
#define pinslibEntryNumGrfGetState                	((uint32_t)pinslibEntryNumGrfGetStateEnum)
#define pinslibEntryNumGrfSetState                	((uint32_t)pinslibEntryNumGrfSetStateEnum)
#define pinslibEntryNumGrfFlushPoints             	((uint32_t)pinslibEntryNumGrfFlushPointsEnum)
#define pinslibEntryNumGrfAddPoint                	((uint32_t)pinslibEntryNumGrfAddPointEnum)
#define pinslibEntryNumGrfInitState               	((uint32_t)pinslibEntryNumGrfInitStateEnum)
#define pinslibEntryNumGrfCleanState              	((uint32_t)pinslibEntryNumGrfCleanStateEnum)
#define pinslibEntryNumGrfMatch                   	((uint32_t)pinslibEntryNumGrfMatchEnum)
#define pinslibEntryNumGrfGetMacro                	((uint32_t)pinslibEntryNumGrfGetMacroEnum)
#define pinslibEntryNumGrfGetAndExpandMacro       	((uint32_t)pinslibEntryNumGrfGetAndExpandMacroEnum)
#define pinslibEntryNumGrfFilterPoints            	((uint32_t)pinslibEntryNumGrfFilterPointsEnum)
#define pinslibEntryNumGrfGetNumPoints            	((uint32_t)pinslibEntryNumGrfGetNumPointsEnum)
#define pinslibEntryNumGrfGetPoint                	((uint32_t)pinslibEntryNumGrfGetPointEnum)
#define pinslibEntryNumGrfFindBranch              	((uint32_t)pinslibEntryNumGrfFindBranchEnum)
#define pinslibEntryNumGrfMatchGlyph              	((uint32_t)pinslibEntryNumGrfMatchGlyphEnum)
#define pinslibEntryNumGrfGetGlyphMapping         	((uint32_t)pinslibEntryNumGrfGetGlyphMappingEnum)
#define pinslibEntryNumGrfGetMacroName            	((uint32_t)pinslibEntryNumGrfGetMacroNameEnum)
#define pinslibEntryNumGrfDeleteMacro             	((uint32_t)pinslibEntryNumGrfDeleteMacroEnum)
#define pinslibEntryNumGrfAddMacro                	((uint32_t)pinslibEntryNumGrfAddMacroEnum)
#define pinslibEntryNumSysGraffitiReferenceDialog 	((uint32_t)pinslibEntryNumSysGraffitiReferenceDialogEnum)
#define pinslibEntryNumEvtProcessSoftKeyStroke    	((uint32_t)pinslibEntryNumEvtProcessSoftKeyStrokeEnum)
#define pinslibEntryNumEvtGetPenBtnList           	((uint32_t)pinslibEntryNumEvtGetPenBtnListEnum)
#define pinslibEntryNumEvtGetSilkscreenAreaList   	((uint32_t)pinslibEntryNumEvtGetSilkscreenAreaListEnum)
#define pinslibEntryNumEvtEnableGraffiti          	((uint32_t)pinslibEntryNumEvtEnableGraffitiEnum)
#endif // __PINSLIBENTRYNUMS_H__
