/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: PreferencesEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:09:52 2004
 *****************************************************************************/
#ifndef __PREFERENCESENTRYNUMS_H__	// Avoid multiple inclusion
#define __PREFERENCESENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum preferencesEntryNumTag {
	preferencesEntryNumPrefPanelTitleGadgetHandlerEnum = 0,
};

#define preferencesEntryNumPrefPanelTitleGadgetHandler	((uint32_t)preferencesEntryNumPrefPanelTitleGadgetHandlerEnum)
#endif // __PREFERENCESENTRYNUMS_H__
