/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: SerialLinkMgrEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:34 2004
 *****************************************************************************/
#ifndef __SERIALLINKMGRENTRYNUMS_H__	// Avoid multiple inclusion
#define __SERIALLINKMGRENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum seriallinkmgrEntryNumTag {
	seriallinkmgrEntryNumSlkOpenEnum = 0,
	seriallinkmgrEntryNumSlkCloseEnum,
	seriallinkmgrEntryNumSlkOpenSocketEnum,
	seriallinkmgrEntryNumSlkCloseSocketEnum,
	seriallinkmgrEntryNumSlkSocketPortIDEnum,
	seriallinkmgrEntryNumSlkSocketSetTimeoutEnum,
	seriallinkmgrEntryNumSlkFlushSocketEnum,
	seriallinkmgrEntryNumSlkSetSocketListenerEnum,
	seriallinkmgrEntryNumSlkSendPacketEnum,
	seriallinkmgrEntryNumSlkReceivePacketEnum,
	seriallinkmgrEntryNumPrvSlkSetSocketCancelListenerEnum,
};

#define seriallinkmgrEntryNumSlkOpen                       	((uint32_t)seriallinkmgrEntryNumSlkOpenEnum)
#define seriallinkmgrEntryNumSlkClose                      	((uint32_t)seriallinkmgrEntryNumSlkCloseEnum)
#define seriallinkmgrEntryNumSlkOpenSocket                 	((uint32_t)seriallinkmgrEntryNumSlkOpenSocketEnum)
#define seriallinkmgrEntryNumSlkCloseSocket                	((uint32_t)seriallinkmgrEntryNumSlkCloseSocketEnum)
#define seriallinkmgrEntryNumSlkSocketPortID               	((uint32_t)seriallinkmgrEntryNumSlkSocketPortIDEnum)
#define seriallinkmgrEntryNumSlkSocketSetTimeout           	((uint32_t)seriallinkmgrEntryNumSlkSocketSetTimeoutEnum)
#define seriallinkmgrEntryNumSlkFlushSocket                	((uint32_t)seriallinkmgrEntryNumSlkFlushSocketEnum)
#define seriallinkmgrEntryNumSlkSetSocketListener          	((uint32_t)seriallinkmgrEntryNumSlkSetSocketListenerEnum)
#define seriallinkmgrEntryNumSlkSendPacket                 	((uint32_t)seriallinkmgrEntryNumSlkSendPacketEnum)
#define seriallinkmgrEntryNumSlkReceivePacket              	((uint32_t)seriallinkmgrEntryNumSlkReceivePacketEnum)
#define seriallinkmgrEntryNumPrvSlkSetSocketCancelListener 	((uint32_t)seriallinkmgrEntryNumPrvSlkSetSocketCancelListenerEnum)
#endif // __SERIALLINKMGRENTRYNUMS_H__
