/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: SerialMgrLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:34 2004
 *****************************************************************************/
#ifndef __SERIALMGRLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __SERIALMGRLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum serialmgrlibEntryNumTag {
	serialmgrlibEntryNumSrmOpenEnum = 0,
	serialmgrlibEntryNumSrmExtOpenEnum,
	serialmgrlibEntryNumSrmExtOpenBackgroundEnum,
	serialmgrlibEntryNumSrmOpenBackgroundEnum,
	serialmgrlibEntryNumSrmCloseEnum,
	serialmgrlibEntryNumSrmSleepEnum,
	serialmgrlibEntryNumSrmWakeEnum,
	serialmgrlibEntryNumSrmGetDeviceCountEnum,
	serialmgrlibEntryNumSrmGetDeviceInfoEnum,
	serialmgrlibEntryNumSrmGetStatusEnum,
	serialmgrlibEntryNumSrmClearErrEnum,
	serialmgrlibEntryNumSrmControlEnum,
	serialmgrlibEntryNumSrmCustomControlEnum,
	serialmgrlibEntryNumSrmSendEnum,
	serialmgrlibEntryNumSrmSendWaitEnum,
	serialmgrlibEntryNumSrmSendCheckEnum,
	serialmgrlibEntryNumSrmSendFlushEnum,
	serialmgrlibEntryNumSrmReceiveEnum,
	serialmgrlibEntryNumSrmReceiveWaitEnum,
	serialmgrlibEntryNumSrmReceiveCheckEnum,
	serialmgrlibEntryNumSrmReceiveFlushEnum,
	serialmgrlibEntryNumSrmSetReceiveBufferEnum,
	serialmgrlibEntryNumSrmReceiveWindowOpenEnum,
	serialmgrlibEntryNumSrmReceiveWindowCloseEnum,
	serialmgrlibEntryNumSrmSetWakeupHandlerEnum,
	serialmgrlibEntryNumSrmPrimeWakeupHandlerEnum,
};

#define serialmgrlibEntryNumSrmOpen               	((uint32_t)serialmgrlibEntryNumSrmOpenEnum)
#define serialmgrlibEntryNumSrmExtOpen            	((uint32_t)serialmgrlibEntryNumSrmExtOpenEnum)
#define serialmgrlibEntryNumSrmExtOpenBackground  	((uint32_t)serialmgrlibEntryNumSrmExtOpenBackgroundEnum)
#define serialmgrlibEntryNumSrmOpenBackground     	((uint32_t)serialmgrlibEntryNumSrmOpenBackgroundEnum)
#define serialmgrlibEntryNumSrmClose              	((uint32_t)serialmgrlibEntryNumSrmCloseEnum)
#define serialmgrlibEntryNumSrmSleep              	((uint32_t)serialmgrlibEntryNumSrmSleepEnum)
#define serialmgrlibEntryNumSrmWake               	((uint32_t)serialmgrlibEntryNumSrmWakeEnum)
#define serialmgrlibEntryNumSrmGetDeviceCount     	((uint32_t)serialmgrlibEntryNumSrmGetDeviceCountEnum)
#define serialmgrlibEntryNumSrmGetDeviceInfo      	((uint32_t)serialmgrlibEntryNumSrmGetDeviceInfoEnum)
#define serialmgrlibEntryNumSrmGetStatus          	((uint32_t)serialmgrlibEntryNumSrmGetStatusEnum)
#define serialmgrlibEntryNumSrmClearErr           	((uint32_t)serialmgrlibEntryNumSrmClearErrEnum)
#define serialmgrlibEntryNumSrmControl            	((uint32_t)serialmgrlibEntryNumSrmControlEnum)
#define serialmgrlibEntryNumSrmCustomControl      	((uint32_t)serialmgrlibEntryNumSrmCustomControlEnum)
#define serialmgrlibEntryNumSrmSend               	((uint32_t)serialmgrlibEntryNumSrmSendEnum)
#define serialmgrlibEntryNumSrmSendWait           	((uint32_t)serialmgrlibEntryNumSrmSendWaitEnum)
#define serialmgrlibEntryNumSrmSendCheck          	((uint32_t)serialmgrlibEntryNumSrmSendCheckEnum)
#define serialmgrlibEntryNumSrmSendFlush          	((uint32_t)serialmgrlibEntryNumSrmSendFlushEnum)
#define serialmgrlibEntryNumSrmReceive            	((uint32_t)serialmgrlibEntryNumSrmReceiveEnum)
#define serialmgrlibEntryNumSrmReceiveWait        	((uint32_t)serialmgrlibEntryNumSrmReceiveWaitEnum)
#define serialmgrlibEntryNumSrmReceiveCheck       	((uint32_t)serialmgrlibEntryNumSrmReceiveCheckEnum)
#define serialmgrlibEntryNumSrmReceiveFlush       	((uint32_t)serialmgrlibEntryNumSrmReceiveFlushEnum)
#define serialmgrlibEntryNumSrmSetReceiveBuffer   	((uint32_t)serialmgrlibEntryNumSrmSetReceiveBufferEnum)
#define serialmgrlibEntryNumSrmReceiveWindowOpen  	((uint32_t)serialmgrlibEntryNumSrmReceiveWindowOpenEnum)
#define serialmgrlibEntryNumSrmReceiveWindowClose 	((uint32_t)serialmgrlibEntryNumSrmReceiveWindowCloseEnum)
#define serialmgrlibEntryNumSrmSetWakeupHandler   	((uint32_t)serialmgrlibEntryNumSrmSetWakeupHandlerEnum)
#define serialmgrlibEntryNumSrmPrimeWakeupHandler 	((uint32_t)serialmgrlibEntryNumSrmPrimeWakeupHandlerEnum)
#endif // __SERIALMGRLIBENTRYNUMS_H__
