/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: ShortcutLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:34 2004
 *****************************************************************************/
#ifndef __SHORTCUTLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __SHORTCUTLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum shortcutlibEntryNumTag {
	shortcutlibEntryNumShortcutLibGetRawEnum = 0,
	shortcutlibEntryNumShortcutLibGetExpandedEnum,
	shortcutlibEntryNumShortcutLibGetNameByIndexEnum,
	shortcutlibEntryNumShortcutLibDeleteByIndexEnum,
	shortcutlibEntryNumShortcutLibAddEnum,
};

#define shortcutlibEntryNumShortcutLibGetRaw        	((uint32_t)shortcutlibEntryNumShortcutLibGetRawEnum)
#define shortcutlibEntryNumShortcutLibGetExpanded   	((uint32_t)shortcutlibEntryNumShortcutLibGetExpandedEnum)
#define shortcutlibEntryNumShortcutLibGetNameByIndex	((uint32_t)shortcutlibEntryNumShortcutLibGetNameByIndexEnum)
#define shortcutlibEntryNumShortcutLibDeleteByIndex 	((uint32_t)shortcutlibEntryNumShortcutLibDeleteByIndexEnum)
#define shortcutlibEntryNumShortcutLibAdd           	((uint32_t)shortcutlibEntryNumShortcutLibAddEnum)
#endif // __SHORTCUTLIBENTRYNUMS_H__
