/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: SignVfyEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:34 2004
 *****************************************************************************/
#ifndef __SIGNVFYENTRYNUMS_H__	// Avoid multiple inclusion
#define __SIGNVFYENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum signvfyEntryNumTag {
	signvfyEntryNumSignVerifySignatureByIndexEnum = 0,
	signvfyEntryNumSignVerifySignatureByIDEnum,
	signvfyEntryNumSignGetNumSignaturesEnum,
	signvfyEntryNumSignGetNumCertificatesEnum,
	signvfyEntryNumSignGetSignatureByIndexEnum,
	signvfyEntryNumSignGetCertificateByIndexEnum,
	signvfyEntryNumSignGetSignatureByIDEnum,
	signvfyEntryNumSignGetCertificateByIDEnum,
	signvfyEntryNumSignGetDigestEnum,
	signvfyEntryNumSignGetOverlayCertIdListEnum,
	signvfyEntryNumSignGetShLibCertIdListEnum,
};

#define signvfyEntryNumSignVerifySignatureByIndex 	((uint32_t)signvfyEntryNumSignVerifySignatureByIndexEnum)
#define signvfyEntryNumSignVerifySignatureByID    	((uint32_t)signvfyEntryNumSignVerifySignatureByIDEnum)
#define signvfyEntryNumSignGetNumSignatures       	((uint32_t)signvfyEntryNumSignGetNumSignaturesEnum)
#define signvfyEntryNumSignGetNumCertificates     	((uint32_t)signvfyEntryNumSignGetNumCertificatesEnum)
#define signvfyEntryNumSignGetSignatureByIndex    	((uint32_t)signvfyEntryNumSignGetSignatureByIndexEnum)
#define signvfyEntryNumSignGetCertificateByIndex  	((uint32_t)signvfyEntryNumSignGetCertificateByIndexEnum)
#define signvfyEntryNumSignGetSignatureByID       	((uint32_t)signvfyEntryNumSignGetSignatureByIDEnum)
#define signvfyEntryNumSignGetCertificateByID     	((uint32_t)signvfyEntryNumSignGetCertificateByIDEnum)
#define signvfyEntryNumSignGetDigest              	((uint32_t)signvfyEntryNumSignGetDigestEnum)
#define signvfyEntryNumSignGetOverlayCertIdList   	((uint32_t)signvfyEntryNumSignGetOverlayCertIdListEnum)
#define signvfyEntryNumSignGetShLibCertIdList     	((uint32_t)signvfyEntryNumSignGetShLibCertIdListEnum)
#endif // __SIGNVFYENTRYNUMS_H__
