/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: SocketLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:34 2004
 *****************************************************************************/
#ifndef __SOCKETLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __SOCKETLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum socketlibEntryNumTag {
	socketlibEntryNumacceptEnum = 0,
	socketlibEntryNumbindEnum,
	socketlibEntryNumconnectEnum,
	socketlibEntryNumgetpeernameEnum,
	socketlibEntryNumgetsocknameEnum,
	socketlibEntryNumgetsockoptEnum,
	socketlibEntryNumlistenEnum,
	socketlibEntryNumrecvEnum,
	socketlibEntryNumrecvfromEnum,
	socketlibEntryNumrecvmsgEnum,
	socketlibEntryNumsendEnum,
	socketlibEntryNumsendtoEnum,
	socketlibEntryNumsendmsgEnum,
	socketlibEntryNumsetsockoptEnum,
	socketlibEntryNumshutdownEnum,
	socketlibEntryNumsocketEnum,
	socketlibEntryNumselectEnum,
};

#define socketlibEntryNumaccept           	((uint32_t)socketlibEntryNumacceptEnum)
#define socketlibEntryNumbind             	((uint32_t)socketlibEntryNumbindEnum)
#define socketlibEntryNumconnect          	((uint32_t)socketlibEntryNumconnectEnum)
#define socketlibEntryNumgetpeername      	((uint32_t)socketlibEntryNumgetpeernameEnum)
#define socketlibEntryNumgetsockname      	((uint32_t)socketlibEntryNumgetsocknameEnum)
#define socketlibEntryNumgetsockopt       	((uint32_t)socketlibEntryNumgetsockoptEnum)
#define socketlibEntryNumlisten           	((uint32_t)socketlibEntryNumlistenEnum)
#define socketlibEntryNumrecv             	((uint32_t)socketlibEntryNumrecvEnum)
#define socketlibEntryNumrecvfrom         	((uint32_t)socketlibEntryNumrecvfromEnum)
#define socketlibEntryNumrecvmsg          	((uint32_t)socketlibEntryNumrecvmsgEnum)
#define socketlibEntryNumsend             	((uint32_t)socketlibEntryNumsendEnum)
#define socketlibEntryNumsendto           	((uint32_t)socketlibEntryNumsendtoEnum)
#define socketlibEntryNumsendmsg          	((uint32_t)socketlibEntryNumsendmsgEnum)
#define socketlibEntryNumsetsockopt       	((uint32_t)socketlibEntryNumsetsockoptEnum)
#define socketlibEntryNumshutdown         	((uint32_t)socketlibEntryNumshutdownEnum)
#define socketlibEntryNumsocket           	((uint32_t)socketlibEntryNumsocketEnum)
#define socketlibEntryNumselect           	((uint32_t)socketlibEntryNumselectEnum)
#endif // __SOCKETLIBENTRYNUMS_H__
