/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: SoundMgrEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:34 2004
 *****************************************************************************/
#ifndef __SOUNDMGRENTRYNUMS_H__	// Avoid multiple inclusion
#define __SOUNDMGRENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum soundmgrEntryNumTag {
	soundmgrEntryNumSndStreamCreateEnum = 0,
	soundmgrEntryNumSndStreamCreateExtendedEnum,
	soundmgrEntryNumSndStreamDeleteEnum,
	soundmgrEntryNumSndStreamDeviceControlEnum,
	soundmgrEntryNumSndStreamStartEnum,
	soundmgrEntryNumSndStreamStopEnum,
	soundmgrEntryNumSndStreamPauseEnum,
	soundmgrEntryNumSndStreamSetVolumeEnum,
	soundmgrEntryNumSndStreamGetVolumeEnum,
	soundmgrEntryNumSndStreamSetPanEnum,
	soundmgrEntryNumSndStreamGetPanEnum,
	soundmgrEntryNumSndDoCmdEnum,
	soundmgrEntryNumSndPlayResourceEnum,
	soundmgrEntryNumSndCreateMidiListEnum,
	soundmgrEntryNumSndSetDefaultVolumeEnum,
	soundmgrEntryNumSndGetDefaultVolumeEnum,
	soundmgrEntryNumSndPlaySystemSoundEnum,
	soundmgrEntryNumSndPlaySmfEnum,
	soundmgrEntryNumSndPlaySmfResourceEnum,
	soundmgrEntryNumSndPlaySmfResourceV50Enum,
	soundmgrEntryNumSndSetMasterVolumeEnum,
	soundmgrEntryNumSndGetMasterVolumeEnum,
	soundmgrEntryNumSndSetMasterMuteEnum,
	soundmgrEntryNumSndGetMasterMuteEnum,
};

#define soundmgrEntryNumSndStreamCreate         	((uint32_t)soundmgrEntryNumSndStreamCreateEnum)
#define soundmgrEntryNumSndStreamCreateExtended 	((uint32_t)soundmgrEntryNumSndStreamCreateExtendedEnum)
#define soundmgrEntryNumSndStreamDelete         	((uint32_t)soundmgrEntryNumSndStreamDeleteEnum)
#define soundmgrEntryNumSndStreamDeviceControl  	((uint32_t)soundmgrEntryNumSndStreamDeviceControlEnum)
#define soundmgrEntryNumSndStreamStart          	((uint32_t)soundmgrEntryNumSndStreamStartEnum)
#define soundmgrEntryNumSndStreamStop           	((uint32_t)soundmgrEntryNumSndStreamStopEnum)
#define soundmgrEntryNumSndStreamPause          	((uint32_t)soundmgrEntryNumSndStreamPauseEnum)
#define soundmgrEntryNumSndStreamSetVolume      	((uint32_t)soundmgrEntryNumSndStreamSetVolumeEnum)
#define soundmgrEntryNumSndStreamGetVolume      	((uint32_t)soundmgrEntryNumSndStreamGetVolumeEnum)
#define soundmgrEntryNumSndStreamSetPan         	((uint32_t)soundmgrEntryNumSndStreamSetPanEnum)
#define soundmgrEntryNumSndStreamGetPan         	((uint32_t)soundmgrEntryNumSndStreamGetPanEnum)
#define soundmgrEntryNumSndDoCmd                	((uint32_t)soundmgrEntryNumSndDoCmdEnum)
#define soundmgrEntryNumSndPlayResource         	((uint32_t)soundmgrEntryNumSndPlayResourceEnum)
#define soundmgrEntryNumSndCreateMidiList       	((uint32_t)soundmgrEntryNumSndCreateMidiListEnum)
#define soundmgrEntryNumSndSetDefaultVolume     	((uint32_t)soundmgrEntryNumSndSetDefaultVolumeEnum)
#define soundmgrEntryNumSndGetDefaultVolume     	((uint32_t)soundmgrEntryNumSndGetDefaultVolumeEnum)
#define soundmgrEntryNumSndPlaySystemSound      	((uint32_t)soundmgrEntryNumSndPlaySystemSoundEnum)
#define soundmgrEntryNumSndPlaySmf              	((uint32_t)soundmgrEntryNumSndPlaySmfEnum)
#define soundmgrEntryNumSndPlaySmfResource      	((uint32_t)soundmgrEntryNumSndPlaySmfResourceEnum)
#define soundmgrEntryNumSndPlaySmfResourceV50   	((uint32_t)soundmgrEntryNumSndPlaySmfResourceV50Enum)
#define soundmgrEntryNumSndSetMasterVolume      	((uint32_t)soundmgrEntryNumSndSetMasterVolumeEnum)
#define soundmgrEntryNumSndGetMasterVolume      	((uint32_t)soundmgrEntryNumSndGetMasterVolumeEnum)
#define soundmgrEntryNumSndSetMasterMute        	((uint32_t)soundmgrEntryNumSndSetMasterMuteEnum)
#define soundmgrEntryNumSndGetMasterMute        	((uint32_t)soundmgrEntryNumSndGetMasterMuteEnum)
#endif // __SOUNDMGRENTRYNUMS_H__
