/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: SSLLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __SSLLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __SSLLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum ssllibEntryNumTag {
	ssllibEntryNumSslLibOpenEnum = 0,
	ssllibEntryNumSslLibCloseEnum,
	ssllibEntryNumSslLibCreateEnum,
	ssllibEntryNumSslLibDestroyEnum,
	ssllibEntryNumSslLibSetLongEnum,
	ssllibEntryNumSslLibGetLongEnum,
	ssllibEntryNumSslLibSetPtrEnum,
	ssllibEntryNumSslLibGetPtrEnum,
	ssllibEntryNumSslContextCreateEnum,
	ssllibEntryNumSslContextDestroyEnum,
	ssllibEntryNumSslContextGetLongEnum,
	ssllibEntryNumSslContextSetLongEnum,
	ssllibEntryNumSslContextGetPtrEnum,
	ssllibEntryNumSslContextSetPtrEnum,
	ssllibEntryNumSslOpenEnum,
	ssllibEntryNumSslCloseEnum,
	ssllibEntryNumSslSendEnum,
	ssllibEntryNumSslReceiveEnum,
	ssllibEntryNumSslReadEnum,
	ssllibEntryNumSslWriteEnum,
	ssllibEntryNumSslPeekEnum,
	ssllibEntryNumSslConsumeEnum,
	ssllibEntryNumSslFlushEnum,
};

#define ssllibEntryNumSslLibOpen        	((uint32_t)ssllibEntryNumSslLibOpenEnum)
#define ssllibEntryNumSslLibClose       	((uint32_t)ssllibEntryNumSslLibCloseEnum)
#define ssllibEntryNumSslLibCreate      	((uint32_t)ssllibEntryNumSslLibCreateEnum)
#define ssllibEntryNumSslLibDestroy     	((uint32_t)ssllibEntryNumSslLibDestroyEnum)
#define ssllibEntryNumSslLibSetLong     	((uint32_t)ssllibEntryNumSslLibSetLongEnum)
#define ssllibEntryNumSslLibGetLong     	((uint32_t)ssllibEntryNumSslLibGetLongEnum)
#define ssllibEntryNumSslLibSetPtr      	((uint32_t)ssllibEntryNumSslLibSetPtrEnum)
#define ssllibEntryNumSslLibGetPtr      	((uint32_t)ssllibEntryNumSslLibGetPtrEnum)
#define ssllibEntryNumSslContextCreate  	((uint32_t)ssllibEntryNumSslContextCreateEnum)
#define ssllibEntryNumSslContextDestroy 	((uint32_t)ssllibEntryNumSslContextDestroyEnum)
#define ssllibEntryNumSslContextGetLong 	((uint32_t)ssllibEntryNumSslContextGetLongEnum)
#define ssllibEntryNumSslContextSetLong 	((uint32_t)ssllibEntryNumSslContextSetLongEnum)
#define ssllibEntryNumSslContextGetPtr  	((uint32_t)ssllibEntryNumSslContextGetPtrEnum)
#define ssllibEntryNumSslContextSetPtr  	((uint32_t)ssllibEntryNumSslContextSetPtrEnum)
#define ssllibEntryNumSslOpen           	((uint32_t)ssllibEntryNumSslOpenEnum)
#define ssllibEntryNumSslClose          	((uint32_t)ssllibEntryNumSslCloseEnum)
#define ssllibEntryNumSslSend           	((uint32_t)ssllibEntryNumSslSendEnum)
#define ssllibEntryNumSslReceive        	((uint32_t)ssllibEntryNumSslReceiveEnum)
#define ssllibEntryNumSslRead           	((uint32_t)ssllibEntryNumSslReadEnum)
#define ssllibEntryNumSslWrite          	((uint32_t)ssllibEntryNumSslWriteEnum)
#define ssllibEntryNumSslPeek           	((uint32_t)ssllibEntryNumSslPeekEnum)
#define ssllibEntryNumSslConsume        	((uint32_t)ssllibEntryNumSslConsumeEnum)
#define ssllibEntryNumSslFlush          	((uint32_t)ssllibEntryNumSslFlushEnum)
#endif // __SSLLIBENTRYNUMS_H__
