/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: TelephonyLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __TELEPHONYLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __TELEPHONYLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum telephonylibEntryNumTag {
	telephonylibEntryNumTelOpenEnum = 0,
	telephonylibEntryNumTelOpenPhoneProfileEnum,
	telephonylibEntryNumTelCloseEnum,
	telephonylibEntryNumTelCancelEnum,
	telephonylibEntryNumTelTestPhoneDriverEnum,
	telephonylibEntryNumTelEvtGetEventEnum,
	telephonylibEntryNumTelEvtGetTelephonyEventEnum,
	telephonylibEntryNumTelCncOpenEnum,
	telephonylibEntryNumTelCncCloseEnum,
	telephonylibEntryNumTelCncGetStatusEnum,
	telephonylibEntryNumTelNwkGetOperatorsEnum,
	telephonylibEntryNumTelNwkGetOperatorEnum,
	telephonylibEntryNumTelNwkSetOperatorEnum,
	telephonylibEntryNumTelNwkGetPreferredOperatorsEnum,
	telephonylibEntryNumTelNwkAddPreferredOperatorEnum,
	telephonylibEntryNumTelNwkDeletePreferredOperatorEnum,
	telephonylibEntryNumTelNwkGetRegistrationModeEnum,
	telephonylibEntryNumTelNwkSetRegistrationEnum,
	telephonylibEntryNumTelNwkGetTypeEnum,
	telephonylibEntryNumTelNwkGetStatusEnum,
	telephonylibEntryNumTelNwkGetProviderIdEnum,
	telephonylibEntryNumTelNwkGetLocationEnum,
	telephonylibEntryNumTelNwkGetSignalLevelEnum,
	telephonylibEntryNumTelNwkCheckUssdEnum,
	telephonylibEntryNumTelNwkSendUssdEnum,
	telephonylibEntryNumTelNwkReceiveUssdEnum,
	telephonylibEntryNumTelNwkCancelUssdEnum,
	telephonylibEntryNumTelStyGetAuthenticationStatusEnum,
	telephonylibEntryNumTelStyEnterAuthenticationEnum,
	telephonylibEntryNumTelStyGetFacilitiesEnum,
	telephonylibEntryNumTelStyGetFacilityEnum,
	telephonylibEntryNumTelStyLockFacilityEnum,
	telephonylibEntryNumTelStyUnlockFacilityEnum,
	telephonylibEntryNumTelStyChangeFacilityPasswordEnum,
	telephonylibEntryNumTelPowGetBatteryChargeLevelEnum,
	telephonylibEntryNumTelPowGetBatteryConnectionStatusEnum,
	telephonylibEntryNumTelPowSetPhoneFunctionalityEnum,
	telephonylibEntryNumTelCfgGetSmsCenterEnum,
	telephonylibEntryNumTelCfgSetSmsCenterEnum,
	telephonylibEntryNumTelCfgGetPhoneNumberEnum,
	telephonylibEntryNumTelCfgSetPhoneNumberEnum,
	telephonylibEntryNumTelCfgGetVoiceMailNumberEnum,
	telephonylibEntryNumTelCfgSetVoiceMailNumberEnum,
	telephonylibEntryNumTelCfgGetLoudspeakerVolumeLevelRangeEnum,
	telephonylibEntryNumTelCfgGetLoudspeakerVolumeLevelEnum,
	telephonylibEntryNumTelCfgSetLoudspeakerVolumeLevelEnum,
	telephonylibEntryNumTelCfgGetRingerSoundLevelRangeEnum,
	telephonylibEntryNumTelCfgGetRingerSoundLevelEnum,
	telephonylibEntryNumTelCfgSetRingerSoundLevelEnum,
	telephonylibEntryNumTelCfgGetVibratorModeEnum,
	telephonylibEntryNumTelCfgSetVibratorModeEnum,
	telephonylibEntryNumTelCfgGetAlertSoundModeEnum,
	telephonylibEntryNumTelCfgSetAlertSoundModeEnum,
	telephonylibEntryNumTelCfgGetCallForwardingEnum,
	telephonylibEntryNumTelCfgSetCallForwardingEnum,
	telephonylibEntryNumTelCfgGetCallIdRestrictionStatusEnum,
	telephonylibEntryNumTelCfgSetCallIdRestrictionStatusEnum,
	telephonylibEntryNumTelSmsSendMessageEnum,
	telephonylibEntryNumTelSmsReadMessagesEnum,
	telephonylibEntryNumTelSmsReadMessageEnum,
	telephonylibEntryNumTelSmsDeleteMessageEnum,
	telephonylibEntryNumTelSmsGetUniquePartIdEnum,
	telephonylibEntryNumTelSmsGetDataMaxSizeEnum,
	telephonylibEntryNumTelSmsGetStoragesEnum,
	telephonylibEntryNumTelSmsGetStorageEnum,
	telephonylibEntryNumTelSmsSetStorageEnum,
	telephonylibEntryNumTelEmcDialEnum,
	telephonylibEntryNumTelSpcGetCallsEnum,
	telephonylibEntryNumTelSpcGetCallEnum,
	telephonylibEntryNumTelSpcInitiateCallEnum,
	telephonylibEntryNumTelSpcAcceptCallEnum,
	telephonylibEntryNumTelSpcReleaseCallEnum,
	telephonylibEntryNumTelSpcHoldActiveCallsEnum,
	telephonylibEntryNumTelSpcAddHeldCallEnum,
	telephonylibEntryNumTelSpcPrivateCallEnum,
	telephonylibEntryNumTelSpcPlayToneEnum,
	telephonylibEntryNumTelSpcGetToneDurationRangeEnum,
	telephonylibEntryNumTelSpcGetToneDurationEnum,
	telephonylibEntryNumTelSpcSetToneDurationEnum,
	telephonylibEntryNumTelPhbGetPhonebooksEnum,
	telephonylibEntryNumTelPhbGetPhonebookEnum,
	telephonylibEntryNumTelPhbSetPhonebookEnum,
	telephonylibEntryNumTelPhbGetEntriesEnum,
	telephonylibEntryNumTelPhbGetEntryEnum,
	telephonylibEntryNumTelPhbAddEntryEnum,
	telephonylibEntryNumTelPhbDeleteEntryEnum,
	telephonylibEntryNumTelSndGetMuteStatusEnum,
	telephonylibEntryNumTelSndSetMuteStatusEnum,
	telephonylibEntryNumTelInfGetIdentificationEnum,
	telephonylibEntryNumTelInfGetCallsDurationEnum,
	telephonylibEntryNumTelInfResetCallsDurationEnum,
	telephonylibEntryNumTelInfGetCallsListEnum,
	telephonylibEntryNumTelInfResetCallsListEnum,
	telephonylibEntryNumTelIsServiceAvailableEnum,
	telephonylibEntryNumTelIsFunctionSupportedEnum,
	telephonylibEntryNumTelOemCallEnum,
	telephonylibEntryNumTelUiManageErrorEnum,
	telephonylibEntryNumTelGprsGetAvailableContextIdEnum,
	telephonylibEntryNumTelGprsSetContextEnum,
	telephonylibEntryNumTelGprsGetContextEnum,
	telephonylibEntryNumTelGprsGetDefinedCidsEnum,
	telephonylibEntryNumTelGprsSetAttachEnum,
	telephonylibEntryNumTelGprsGetAttachEnum,
	telephonylibEntryNumTelGprsSetPdpActivationEnum,
	telephonylibEntryNumTelGprsGetPdpActivationEnum,
	telephonylibEntryNumTelGprsGetPdpAddressEnum,
	telephonylibEntryNumTelGprsSetNwkRegistrationEnum,
	telephonylibEntryNumTelGprsGetNwkRegistrationEnum,
	telephonylibEntryNumTelGprsSetSmsServiceEnum,
	telephonylibEntryNumTelGprsGetSmsServiceEnum,
	telephonylibEntryNumTelGprsSetQosRequestedEnum,
	telephonylibEntryNumTelGprsGetQosRequestedEnum,
	telephonylibEntryNumTelGprsSetQosMinimumEnum,
	telephonylibEntryNumTelGprsGetQosMinimumEnum,
	telephonylibEntryNumTelGprsGetQosCurrentEnum,
	telephonylibEntryNumTelGprsSetEventReportingEnum,
	telephonylibEntryNumTelGprsGetEventReportingEnum,
	telephonylibEntryNumTelGprsGetDataCounterEnum,
	telephonylibEntryNumTelCatSetConfigEnum,
	telephonylibEntryNumTelCatGetConfigEnum,
	telephonylibEntryNumTelCardGetFileEnum,
	telephonylibEntryNumTelCatTerminateEnum,
	telephonylibEntryNumTelCatGetCmdParametersEnum,
	telephonylibEntryNumTelCatSetCmdResponseEnum,
	telephonylibEntryNumTelCatMenuSelectionEnum,
	telephonylibEntryNumTelCatCallActionEnum,
	telephonylibEntryNumTelCatNotifyCardOfEventEnum,
	telephonylibEntryNumTelMuxEnableEnum,
	telephonylibEntryNumTelMuxChanAllocateEnum,
	telephonylibEntryNumTelMuxChanFreeEnum,
	telephonylibEntryNumTelMuxChanSetIdEnum,
};

#define telephonylibEntryNumTelOpen                               	((uint32_t)telephonylibEntryNumTelOpenEnum)
#define telephonylibEntryNumTelOpenPhoneProfile                   	((uint32_t)telephonylibEntryNumTelOpenPhoneProfileEnum)
#define telephonylibEntryNumTelClose                              	((uint32_t)telephonylibEntryNumTelCloseEnum)
#define telephonylibEntryNumTelCancel                             	((uint32_t)telephonylibEntryNumTelCancelEnum)
#define telephonylibEntryNumTelTestPhoneDriver                    	((uint32_t)telephonylibEntryNumTelTestPhoneDriverEnum)
#define telephonylibEntryNumTelEvtGetEvent                        	((uint32_t)telephonylibEntryNumTelEvtGetEventEnum)
#define telephonylibEntryNumTelEvtGetTelephonyEvent               	((uint32_t)telephonylibEntryNumTelEvtGetTelephonyEventEnum)
#define telephonylibEntryNumTelCncOpen                            	((uint32_t)telephonylibEntryNumTelCncOpenEnum)
#define telephonylibEntryNumTelCncClose                           	((uint32_t)telephonylibEntryNumTelCncCloseEnum)
#define telephonylibEntryNumTelCncGetStatus                       	((uint32_t)telephonylibEntryNumTelCncGetStatusEnum)
#define telephonylibEntryNumTelNwkGetOperators                    	((uint32_t)telephonylibEntryNumTelNwkGetOperatorsEnum)
#define telephonylibEntryNumTelNwkGetOperator                     	((uint32_t)telephonylibEntryNumTelNwkGetOperatorEnum)
#define telephonylibEntryNumTelNwkSetOperator                     	((uint32_t)telephonylibEntryNumTelNwkSetOperatorEnum)
#define telephonylibEntryNumTelNwkGetPreferredOperators           	((uint32_t)telephonylibEntryNumTelNwkGetPreferredOperatorsEnum)
#define telephonylibEntryNumTelNwkAddPreferredOperator            	((uint32_t)telephonylibEntryNumTelNwkAddPreferredOperatorEnum)
#define telephonylibEntryNumTelNwkDeletePreferredOperator         	((uint32_t)telephonylibEntryNumTelNwkDeletePreferredOperatorEnum)
#define telephonylibEntryNumTelNwkGetRegistrationMode             	((uint32_t)telephonylibEntryNumTelNwkGetRegistrationModeEnum)
#define telephonylibEntryNumTelNwkSetRegistration                 	((uint32_t)telephonylibEntryNumTelNwkSetRegistrationEnum)
#define telephonylibEntryNumTelNwkGetType                         	((uint32_t)telephonylibEntryNumTelNwkGetTypeEnum)
#define telephonylibEntryNumTelNwkGetStatus                       	((uint32_t)telephonylibEntryNumTelNwkGetStatusEnum)
#define telephonylibEntryNumTelNwkGetProviderId                   	((uint32_t)telephonylibEntryNumTelNwkGetProviderIdEnum)
#define telephonylibEntryNumTelNwkGetLocation                     	((uint32_t)telephonylibEntryNumTelNwkGetLocationEnum)
#define telephonylibEntryNumTelNwkGetSignalLevel                  	((uint32_t)telephonylibEntryNumTelNwkGetSignalLevelEnum)
#define telephonylibEntryNumTelNwkCheckUssd                       	((uint32_t)telephonylibEntryNumTelNwkCheckUssdEnum)
#define telephonylibEntryNumTelNwkSendUssd                        	((uint32_t)telephonylibEntryNumTelNwkSendUssdEnum)
#define telephonylibEntryNumTelNwkReceiveUssd                     	((uint32_t)telephonylibEntryNumTelNwkReceiveUssdEnum)
#define telephonylibEntryNumTelNwkCancelUssd                      	((uint32_t)telephonylibEntryNumTelNwkCancelUssdEnum)
#define telephonylibEntryNumTelStyGetAuthenticationStatus         	((uint32_t)telephonylibEntryNumTelStyGetAuthenticationStatusEnum)
#define telephonylibEntryNumTelStyEnterAuthentication             	((uint32_t)telephonylibEntryNumTelStyEnterAuthenticationEnum)
#define telephonylibEntryNumTelStyGetFacilities                   	((uint32_t)telephonylibEntryNumTelStyGetFacilitiesEnum)
#define telephonylibEntryNumTelStyGetFacility                     	((uint32_t)telephonylibEntryNumTelStyGetFacilityEnum)
#define telephonylibEntryNumTelStyLockFacility                    	((uint32_t)telephonylibEntryNumTelStyLockFacilityEnum)
#define telephonylibEntryNumTelStyUnlockFacility                  	((uint32_t)telephonylibEntryNumTelStyUnlockFacilityEnum)
#define telephonylibEntryNumTelStyChangeFacilityPassword          	((uint32_t)telephonylibEntryNumTelStyChangeFacilityPasswordEnum)
#define telephonylibEntryNumTelPowGetBatteryChargeLevel           	((uint32_t)telephonylibEntryNumTelPowGetBatteryChargeLevelEnum)
#define telephonylibEntryNumTelPowGetBatteryConnectionStatus      	((uint32_t)telephonylibEntryNumTelPowGetBatteryConnectionStatusEnum)
#define telephonylibEntryNumTelPowSetPhoneFunctionality           	((uint32_t)telephonylibEntryNumTelPowSetPhoneFunctionalityEnum)
#define telephonylibEntryNumTelCfgGetSmsCenter                    	((uint32_t)telephonylibEntryNumTelCfgGetSmsCenterEnum)
#define telephonylibEntryNumTelCfgSetSmsCenter                    	((uint32_t)telephonylibEntryNumTelCfgSetSmsCenterEnum)
#define telephonylibEntryNumTelCfgGetPhoneNumber                  	((uint32_t)telephonylibEntryNumTelCfgGetPhoneNumberEnum)
#define telephonylibEntryNumTelCfgSetPhoneNumber                  	((uint32_t)telephonylibEntryNumTelCfgSetPhoneNumberEnum)
#define telephonylibEntryNumTelCfgGetVoiceMailNumber              	((uint32_t)telephonylibEntryNumTelCfgGetVoiceMailNumberEnum)
#define telephonylibEntryNumTelCfgSetVoiceMailNumber              	((uint32_t)telephonylibEntryNumTelCfgSetVoiceMailNumberEnum)
#define telephonylibEntryNumTelCfgGetLoudspeakerVolumeLevelRange  	((uint32_t)telephonylibEntryNumTelCfgGetLoudspeakerVolumeLevelRangeEnum)
#define telephonylibEntryNumTelCfgGetLoudspeakerVolumeLevel       	((uint32_t)telephonylibEntryNumTelCfgGetLoudspeakerVolumeLevelEnum)
#define telephonylibEntryNumTelCfgSetLoudspeakerVolumeLevel       	((uint32_t)telephonylibEntryNumTelCfgSetLoudspeakerVolumeLevelEnum)
#define telephonylibEntryNumTelCfgGetRingerSoundLevelRange        	((uint32_t)telephonylibEntryNumTelCfgGetRingerSoundLevelRangeEnum)
#define telephonylibEntryNumTelCfgGetRingerSoundLevel             	((uint32_t)telephonylibEntryNumTelCfgGetRingerSoundLevelEnum)
#define telephonylibEntryNumTelCfgSetRingerSoundLevel             	((uint32_t)telephonylibEntryNumTelCfgSetRingerSoundLevelEnum)
#define telephonylibEntryNumTelCfgGetVibratorMode                 	((uint32_t)telephonylibEntryNumTelCfgGetVibratorModeEnum)
#define telephonylibEntryNumTelCfgSetVibratorMode                 	((uint32_t)telephonylibEntryNumTelCfgSetVibratorModeEnum)
#define telephonylibEntryNumTelCfgGetAlertSoundMode               	((uint32_t)telephonylibEntryNumTelCfgGetAlertSoundModeEnum)
#define telephonylibEntryNumTelCfgSetAlertSoundMode               	((uint32_t)telephonylibEntryNumTelCfgSetAlertSoundModeEnum)
#define telephonylibEntryNumTelCfgGetCallForwarding               	((uint32_t)telephonylibEntryNumTelCfgGetCallForwardingEnum)
#define telephonylibEntryNumTelCfgSetCallForwarding               	((uint32_t)telephonylibEntryNumTelCfgSetCallForwardingEnum)
#define telephonylibEntryNumTelCfgGetCallIdRestrictionStatus      	((uint32_t)telephonylibEntryNumTelCfgGetCallIdRestrictionStatusEnum)
#define telephonylibEntryNumTelCfgSetCallIdRestrictionStatus      	((uint32_t)telephonylibEntryNumTelCfgSetCallIdRestrictionStatusEnum)
#define telephonylibEntryNumTelSmsSendMessage                     	((uint32_t)telephonylibEntryNumTelSmsSendMessageEnum)
#define telephonylibEntryNumTelSmsReadMessages                    	((uint32_t)telephonylibEntryNumTelSmsReadMessagesEnum)
#define telephonylibEntryNumTelSmsReadMessage                     	((uint32_t)telephonylibEntryNumTelSmsReadMessageEnum)
#define telephonylibEntryNumTelSmsDeleteMessage                   	((uint32_t)telephonylibEntryNumTelSmsDeleteMessageEnum)
#define telephonylibEntryNumTelSmsGetUniquePartId                 	((uint32_t)telephonylibEntryNumTelSmsGetUniquePartIdEnum)
#define telephonylibEntryNumTelSmsGetDataMaxSize                  	((uint32_t)telephonylibEntryNumTelSmsGetDataMaxSizeEnum)
#define telephonylibEntryNumTelSmsGetStorages                     	((uint32_t)telephonylibEntryNumTelSmsGetStoragesEnum)
#define telephonylibEntryNumTelSmsGetStorage                      	((uint32_t)telephonylibEntryNumTelSmsGetStorageEnum)
#define telephonylibEntryNumTelSmsSetStorage                      	((uint32_t)telephonylibEntryNumTelSmsSetStorageEnum)
#define telephonylibEntryNumTelEmcDial                            	((uint32_t)telephonylibEntryNumTelEmcDialEnum)
#define telephonylibEntryNumTelSpcGetCalls                        	((uint32_t)telephonylibEntryNumTelSpcGetCallsEnum)
#define telephonylibEntryNumTelSpcGetCall                         	((uint32_t)telephonylibEntryNumTelSpcGetCallEnum)
#define telephonylibEntryNumTelSpcInitiateCall                    	((uint32_t)telephonylibEntryNumTelSpcInitiateCallEnum)
#define telephonylibEntryNumTelSpcAcceptCall                      	((uint32_t)telephonylibEntryNumTelSpcAcceptCallEnum)
#define telephonylibEntryNumTelSpcReleaseCall                     	((uint32_t)telephonylibEntryNumTelSpcReleaseCallEnum)
#define telephonylibEntryNumTelSpcHoldActiveCalls                 	((uint32_t)telephonylibEntryNumTelSpcHoldActiveCallsEnum)
#define telephonylibEntryNumTelSpcAddHeldCall                     	((uint32_t)telephonylibEntryNumTelSpcAddHeldCallEnum)
#define telephonylibEntryNumTelSpcPrivateCall                     	((uint32_t)telephonylibEntryNumTelSpcPrivateCallEnum)
#define telephonylibEntryNumTelSpcPlayTone                        	((uint32_t)telephonylibEntryNumTelSpcPlayToneEnum)
#define telephonylibEntryNumTelSpcGetToneDurationRange            	((uint32_t)telephonylibEntryNumTelSpcGetToneDurationRangeEnum)
#define telephonylibEntryNumTelSpcGetToneDuration                 	((uint32_t)telephonylibEntryNumTelSpcGetToneDurationEnum)
#define telephonylibEntryNumTelSpcSetToneDuration                 	((uint32_t)telephonylibEntryNumTelSpcSetToneDurationEnum)
#define telephonylibEntryNumTelPhbGetPhonebooks                   	((uint32_t)telephonylibEntryNumTelPhbGetPhonebooksEnum)
#define telephonylibEntryNumTelPhbGetPhonebook                    	((uint32_t)telephonylibEntryNumTelPhbGetPhonebookEnum)
#define telephonylibEntryNumTelPhbSetPhonebook                    	((uint32_t)telephonylibEntryNumTelPhbSetPhonebookEnum)
#define telephonylibEntryNumTelPhbGetEntries                      	((uint32_t)telephonylibEntryNumTelPhbGetEntriesEnum)
#define telephonylibEntryNumTelPhbGetEntry                        	((uint32_t)telephonylibEntryNumTelPhbGetEntryEnum)
#define telephonylibEntryNumTelPhbAddEntry                        	((uint32_t)telephonylibEntryNumTelPhbAddEntryEnum)
#define telephonylibEntryNumTelPhbDeleteEntry                     	((uint32_t)telephonylibEntryNumTelPhbDeleteEntryEnum)
#define telephonylibEntryNumTelSndGetMuteStatus                   	((uint32_t)telephonylibEntryNumTelSndGetMuteStatusEnum)
#define telephonylibEntryNumTelSndSetMuteStatus                   	((uint32_t)telephonylibEntryNumTelSndSetMuteStatusEnum)
#define telephonylibEntryNumTelInfGetIdentification               	((uint32_t)telephonylibEntryNumTelInfGetIdentificationEnum)
#define telephonylibEntryNumTelInfGetCallsDuration                	((uint32_t)telephonylibEntryNumTelInfGetCallsDurationEnum)
#define telephonylibEntryNumTelInfResetCallsDuration              	((uint32_t)telephonylibEntryNumTelInfResetCallsDurationEnum)
#define telephonylibEntryNumTelInfGetCallsList                    	((uint32_t)telephonylibEntryNumTelInfGetCallsListEnum)
#define telephonylibEntryNumTelInfResetCallsList                  	((uint32_t)telephonylibEntryNumTelInfResetCallsListEnum)
#define telephonylibEntryNumTelIsServiceAvailable                 	((uint32_t)telephonylibEntryNumTelIsServiceAvailableEnum)
#define telephonylibEntryNumTelIsFunctionSupported                	((uint32_t)telephonylibEntryNumTelIsFunctionSupportedEnum)
#define telephonylibEntryNumTelOemCall                            	((uint32_t)telephonylibEntryNumTelOemCallEnum)
#define telephonylibEntryNumTelUiManageError                      	((uint32_t)telephonylibEntryNumTelUiManageErrorEnum)
#define telephonylibEntryNumTelGprsGetAvailableContextId          	((uint32_t)telephonylibEntryNumTelGprsGetAvailableContextIdEnum)
#define telephonylibEntryNumTelGprsSetContext                     	((uint32_t)telephonylibEntryNumTelGprsSetContextEnum)
#define telephonylibEntryNumTelGprsGetContext                     	((uint32_t)telephonylibEntryNumTelGprsGetContextEnum)
#define telephonylibEntryNumTelGprsGetDefinedCids                 	((uint32_t)telephonylibEntryNumTelGprsGetDefinedCidsEnum)
#define telephonylibEntryNumTelGprsSetAttach                      	((uint32_t)telephonylibEntryNumTelGprsSetAttachEnum)
#define telephonylibEntryNumTelGprsGetAttach                      	((uint32_t)telephonylibEntryNumTelGprsGetAttachEnum)
#define telephonylibEntryNumTelGprsSetPdpActivation               	((uint32_t)telephonylibEntryNumTelGprsSetPdpActivationEnum)
#define telephonylibEntryNumTelGprsGetPdpActivation               	((uint32_t)telephonylibEntryNumTelGprsGetPdpActivationEnum)
#define telephonylibEntryNumTelGprsGetPdpAddress                  	((uint32_t)telephonylibEntryNumTelGprsGetPdpAddressEnum)
#define telephonylibEntryNumTelGprsSetNwkRegistration             	((uint32_t)telephonylibEntryNumTelGprsSetNwkRegistrationEnum)
#define telephonylibEntryNumTelGprsGetNwkRegistration             	((uint32_t)telephonylibEntryNumTelGprsGetNwkRegistrationEnum)
#define telephonylibEntryNumTelGprsSetSmsService                  	((uint32_t)telephonylibEntryNumTelGprsSetSmsServiceEnum)
#define telephonylibEntryNumTelGprsGetSmsService                  	((uint32_t)telephonylibEntryNumTelGprsGetSmsServiceEnum)
#define telephonylibEntryNumTelGprsSetQosRequested                	((uint32_t)telephonylibEntryNumTelGprsSetQosRequestedEnum)
#define telephonylibEntryNumTelGprsGetQosRequested                	((uint32_t)telephonylibEntryNumTelGprsGetQosRequestedEnum)
#define telephonylibEntryNumTelGprsSetQosMinimum                  	((uint32_t)telephonylibEntryNumTelGprsSetQosMinimumEnum)
#define telephonylibEntryNumTelGprsGetQosMinimum                  	((uint32_t)telephonylibEntryNumTelGprsGetQosMinimumEnum)
#define telephonylibEntryNumTelGprsGetQosCurrent                  	((uint32_t)telephonylibEntryNumTelGprsGetQosCurrentEnum)
#define telephonylibEntryNumTelGprsSetEventReporting              	((uint32_t)telephonylibEntryNumTelGprsSetEventReportingEnum)
#define telephonylibEntryNumTelGprsGetEventReporting              	((uint32_t)telephonylibEntryNumTelGprsGetEventReportingEnum)
#define telephonylibEntryNumTelGprsGetDataCounter                 	((uint32_t)telephonylibEntryNumTelGprsGetDataCounterEnum)
#define telephonylibEntryNumTelCatSetConfig                       	((uint32_t)telephonylibEntryNumTelCatSetConfigEnum)
#define telephonylibEntryNumTelCatGetConfig                       	((uint32_t)telephonylibEntryNumTelCatGetConfigEnum)
#define telephonylibEntryNumTelCardGetFile                        	((uint32_t)telephonylibEntryNumTelCardGetFileEnum)
#define telephonylibEntryNumTelCatTerminate                       	((uint32_t)telephonylibEntryNumTelCatTerminateEnum)
#define telephonylibEntryNumTelCatGetCmdParameters                	((uint32_t)telephonylibEntryNumTelCatGetCmdParametersEnum)
#define telephonylibEntryNumTelCatSetCmdResponse                  	((uint32_t)telephonylibEntryNumTelCatSetCmdResponseEnum)
#define telephonylibEntryNumTelCatMenuSelection                   	((uint32_t)telephonylibEntryNumTelCatMenuSelectionEnum)
#define telephonylibEntryNumTelCatCallAction                      	((uint32_t)telephonylibEntryNumTelCatCallActionEnum)
#define telephonylibEntryNumTelCatNotifyCardOfEvent               	((uint32_t)telephonylibEntryNumTelCatNotifyCardOfEventEnum)
#define telephonylibEntryNumTelMuxEnable                          	((uint32_t)telephonylibEntryNumTelMuxEnableEnum)
#define telephonylibEntryNumTelMuxChanAllocate                    	((uint32_t)telephonylibEntryNumTelMuxChanAllocateEnum)
#define telephonylibEntryNumTelMuxChanFree                        	((uint32_t)telephonylibEntryNumTelMuxChanFreeEnum)
#define telephonylibEntryNumTelMuxChanSetId                       	((uint32_t)telephonylibEntryNumTelMuxChanSetIdEnum)
#endif // __TELEPHONYLIBENTRYNUMS_H__
