/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: TraceLibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __TRACELIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __TRACELIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum tracelibEntryNumTag {
	tracelibEntryNumTmOutputVTEnum = 0,
	tracelibEntryNumTmOutputVTLEnum,
	tracelibEntryNumTmOutputTEnum,
	tracelibEntryNumTmOutputTLEnum,
	tracelibEntryNumTmOutputBEnum,
};

#define tracelibEntryNumTmOutputVT      	((uint32_t)tracelibEntryNumTmOutputVTEnum)
#define tracelibEntryNumTmOutputVTL     	((uint32_t)tracelibEntryNumTmOutputVTLEnum)
#define tracelibEntryNumTmOutputT       	((uint32_t)tracelibEntryNumTmOutputTEnum)
#define tracelibEntryNumTmOutputTL      	((uint32_t)tracelibEntryNumTmOutputTLEnum)
#define tracelibEntryNumTmOutputB       	((uint32_t)tracelibEntryNumTmOutputBEnum)
#endif // __TRACELIBENTRYNUMS_H__
