/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: UDAMgrEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:33 2004
 *****************************************************************************/
#ifndef __UDAMGRENTRYNUMS_H__	// Avoid multiple inclusion
#define __UDAMGRENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum udamgrEntryNumTag {
	udamgrEntryNumUDAControlEnum = 0,
	udamgrEntryNumUDAExchangeReaderNewEnum,
	udamgrEntryNumUDAExchangeWriterNewEnum,
	udamgrEntryNumUDAMemoryReaderNewEnum,
	udamgrEntryNumUDAFoldFilterNewEnum,
	udamgrEntryNumUDAUnfoldFilterNewEnum,
	udamgrEntryNumUDAQPEncoderFilterNewEnum,
	udamgrEntryNumUDAQPDecoderFilterNewEnum,
	udamgrEntryNumUDAB64DecoderFilterNewEnum,
	udamgrEntryNumUDAB64EncoderFilterNewEnum,
	udamgrEntryNumUDAEscapeFilterNewEnum,
	udamgrEntryNumUDAUnEscapeFilterNewEnum,
	udamgrEntryNumUDAPartFilterNewEnum,
	udamgrEntryNumUDAMemoryReaderNewTo68KEnum,
	udamgrEntryNumUDAExchangeReaderNewTo68KEnum,
	udamgrEntryNumUDAExchangeWriterNewTo68KEnum,
	udamgrEntryNumUDAReaderToARMEnum,
	udamgrEntryNumUDAReaderTo68KEnum,
	udamgrEntryNumUDAWriterToARMEnum,
	udamgrEntryNumUDAWriterTo68KEnum,
	udamgrEntryNumUDAMemHandleReaderNewEnum,
	udamgrEntryNumUDAMemHandleWriterNewEnum,
	udamgrEntryNumUDAFileStreamReaderNewEnum,
	udamgrEntryNumUDAFileStreamWriterNewEnum,
	udamgrEntryNumUDAMemHandleReaderNewTo68KEnum,
	udamgrEntryNumUDAFileStreamReaderNewTo68KEnum,
	udamgrEntryNumUDAMemHandleWriterNewTo68KEnum,
	udamgrEntryNumUDAFileStreamWriterNewTo68KEnum,
};

#define udamgrEntryNumUDAControl                  	((uint32_t)udamgrEntryNumUDAControlEnum)
#define udamgrEntryNumUDAExchangeReaderNew        	((uint32_t)udamgrEntryNumUDAExchangeReaderNewEnum)
#define udamgrEntryNumUDAExchangeWriterNew        	((uint32_t)udamgrEntryNumUDAExchangeWriterNewEnum)
#define udamgrEntryNumUDAMemoryReaderNew          	((uint32_t)udamgrEntryNumUDAMemoryReaderNewEnum)
#define udamgrEntryNumUDAFoldFilterNew            	((uint32_t)udamgrEntryNumUDAFoldFilterNewEnum)
#define udamgrEntryNumUDAUnfoldFilterNew          	((uint32_t)udamgrEntryNumUDAUnfoldFilterNewEnum)
#define udamgrEntryNumUDAQPEncoderFilterNew       	((uint32_t)udamgrEntryNumUDAQPEncoderFilterNewEnum)
#define udamgrEntryNumUDAQPDecoderFilterNew       	((uint32_t)udamgrEntryNumUDAQPDecoderFilterNewEnum)
#define udamgrEntryNumUDAB64DecoderFilterNew      	((uint32_t)udamgrEntryNumUDAB64DecoderFilterNewEnum)
#define udamgrEntryNumUDAB64EncoderFilterNew      	((uint32_t)udamgrEntryNumUDAB64EncoderFilterNewEnum)
#define udamgrEntryNumUDAEscapeFilterNew          	((uint32_t)udamgrEntryNumUDAEscapeFilterNewEnum)
#define udamgrEntryNumUDAUnEscapeFilterNew        	((uint32_t)udamgrEntryNumUDAUnEscapeFilterNewEnum)
#define udamgrEntryNumUDAPartFilterNew            	((uint32_t)udamgrEntryNumUDAPartFilterNewEnum)
#define udamgrEntryNumUDAMemoryReaderNewTo68K     	((uint32_t)udamgrEntryNumUDAMemoryReaderNewTo68KEnum)
#define udamgrEntryNumUDAExchangeReaderNewTo68K   	((uint32_t)udamgrEntryNumUDAExchangeReaderNewTo68KEnum)
#define udamgrEntryNumUDAExchangeWriterNewTo68K   	((uint32_t)udamgrEntryNumUDAExchangeWriterNewTo68KEnum)
#define udamgrEntryNumUDAReaderToARM              	((uint32_t)udamgrEntryNumUDAReaderToARMEnum)
#define udamgrEntryNumUDAReaderTo68K              	((uint32_t)udamgrEntryNumUDAReaderTo68KEnum)
#define udamgrEntryNumUDAWriterToARM              	((uint32_t)udamgrEntryNumUDAWriterToARMEnum)
#define udamgrEntryNumUDAWriterTo68K              	((uint32_t)udamgrEntryNumUDAWriterTo68KEnum)
#define udamgrEntryNumUDAMemHandleReaderNew       	((uint32_t)udamgrEntryNumUDAMemHandleReaderNewEnum)
#define udamgrEntryNumUDAMemHandleWriterNew       	((uint32_t)udamgrEntryNumUDAMemHandleWriterNewEnum)
#define udamgrEntryNumUDAFileStreamReaderNew      	((uint32_t)udamgrEntryNumUDAFileStreamReaderNewEnum)
#define udamgrEntryNumUDAFileStreamWriterNew      	((uint32_t)udamgrEntryNumUDAFileStreamWriterNewEnum)
#define udamgrEntryNumUDAMemHandleReaderNewTo68K  	((uint32_t)udamgrEntryNumUDAMemHandleReaderNewTo68KEnum)
#define udamgrEntryNumUDAFileStreamReaderNewTo68K 	((uint32_t)udamgrEntryNumUDAFileStreamReaderNewTo68KEnum)
#define udamgrEntryNumUDAMemHandleWriterNewTo68K  	((uint32_t)udamgrEntryNumUDAMemHandleWriterNewTo68KEnum)
#define udamgrEntryNumUDAFileStreamWriterNewTo68K 	((uint32_t)udamgrEntryNumUDAFileStreamWriterNewTo68KEnum)
#endif // __UDAMGRENTRYNUMS_H__
