/******************************************************************************
 *
 *	Copyright (c) 2004 PalmSource, Inc. or its subsidiaries.
 *	All rights reserved.
 *
 *	File: zlibEntryNums.h
 *
 *	Description:
 *		This file is automatically generated by the
 *		PalmSource Shared Library Generator.
 *
 *	History:
 *		Generated on: Tue Aug 31 14:15:35 2004
 *****************************************************************************/
#ifndef __ZLIBENTRYNUMS_H__	// Avoid multiple inclusion
#define __ZLIBENTRYNUMS_H__

// System header file
#include <PalmTypes.h>

enum zlibEntryNumTag {
	zlibEntryNumdeflateInit_Enum = 0,
	zlibEntryNumdeflateInit2_Enum,
	zlibEntryNumdeflateParamsEnum,
	zlibEntryNumdeflateEnum,
	zlibEntryNumdeflateEndEnum,
	zlibEntryNumdeflateResetEnum,
	zlibEntryNuminflateInit_Enum,
	zlibEntryNuminflateInit2_Enum,
	zlibEntryNumcrc32Enum,
	zlibEntryNuminflateEndEnum,
	zlibEntryNuminflateResetEnum,
	zlibEntryNuminflateEnum,
	zlibEntryNumzlibVersionEnum,
	zlibEntryNumdeflateSetDictionaryEnum,
	zlibEntryNumdeflateCopyEnum,
	zlibEntryNuminflateSetDictionaryEnum,
	zlibEntryNuminflateSyncEnum,
	zlibEntryNumcompressEnum,
	zlibEntryNumcompress2Enum,
	zlibEntryNumuncompressEnum,
	zlibEntryNumadler32Enum,
};

#define zlibEntryNumdeflateInit_         	((uint32_t)zlibEntryNumdeflateInit_Enum)
#define zlibEntryNumdeflateInit2_        	((uint32_t)zlibEntryNumdeflateInit2_Enum)
#define zlibEntryNumdeflateParams        	((uint32_t)zlibEntryNumdeflateParamsEnum)
#define zlibEntryNumdeflate              	((uint32_t)zlibEntryNumdeflateEnum)
#define zlibEntryNumdeflateEnd           	((uint32_t)zlibEntryNumdeflateEndEnum)
#define zlibEntryNumdeflateReset         	((uint32_t)zlibEntryNumdeflateResetEnum)
#define zlibEntryNuminflateInit_         	((uint32_t)zlibEntryNuminflateInit_Enum)
#define zlibEntryNuminflateInit2_        	((uint32_t)zlibEntryNuminflateInit2_Enum)
#define zlibEntryNumcrc32                	((uint32_t)zlibEntryNumcrc32Enum)
#define zlibEntryNuminflateEnd           	((uint32_t)zlibEntryNuminflateEndEnum)
#define zlibEntryNuminflateReset         	((uint32_t)zlibEntryNuminflateResetEnum)
#define zlibEntryNuminflate              	((uint32_t)zlibEntryNuminflateEnum)
#define zlibEntryNumzlibVersion          	((uint32_t)zlibEntryNumzlibVersionEnum)
#define zlibEntryNumdeflateSetDictionary 	((uint32_t)zlibEntryNumdeflateSetDictionaryEnum)
#define zlibEntryNumdeflateCopy          	((uint32_t)zlibEntryNumdeflateCopyEnum)
#define zlibEntryNuminflateSetDictionary 	((uint32_t)zlibEntryNuminflateSetDictionaryEnum)
#define zlibEntryNuminflateSync          	((uint32_t)zlibEntryNuminflateSyncEnum)
#define zlibEntryNumcompress             	((uint32_t)zlibEntryNumcompressEnum)
#define zlibEntryNumcompress2            	((uint32_t)zlibEntryNumcompress2Enum)
#define zlibEntryNumuncompress           	((uint32_t)zlibEntryNumuncompressEnum)
#define zlibEntryNumadler32              	((uint32_t)zlibEntryNumadler32Enum)
#endif // __ZLIBENTRYNUMS_H__
