#ifndef APPRESOURCES_H
#define APPRESOURCES_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 9:10:35 PM on Sunday, August 03, 2003
//
//	Generated for file: Schemer.xrd
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Schemer"
//
//	Palm App Version:		"1.0a1"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainNewButton                             1001
#define MainDeleteButton                          1002
#define MainRowsList                              1003
#define MainDatePushButton                        1004
#define MainRandomPushButton                      1005
#define MainGroupID                               1

//	Resource: tFRM 2000
#define AboutForm                                 2000
#define AboutTitleLabel                           2002
#define AboutText1Label                           2003
#define AboutText2Label                           2004
#define AboutOKButton                             2005


//	Resource: Talt 1000
#define DeleteAlert                               1000
#define DeleteYes                                 0
#define DeleteNo                                  1

//	Resource: Talt 1100
#define NoRowsAlert                               1100
#define NoRowsOK                                  0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutSchemer                   1000


//	Resource: tSTR 1200
#define HelpID1200String                          1200


#endif // APPRESOURCES_H
