#ifndef GPSINFO_RSRC_H
#define GPSINFO_RSRC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 1:25:06 PM on Tuesday, December 07, 2004
//
//	Generated for file: GPSInfo.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"GPSInfo"
//
//	Palm App Version:		"1.2"


//	Resource: tFRM 1020
#define AboutForm                                 1020
#define AboutOKButton                             1021
#define AboutBitmapBitMap                         1200
#define AboutApplicationTitleLabel                1022
#define AboutVersionLabel                         1023
#define AboutCopyrightLabel                       1024

//	Resource: tFRM 1010
#define SatStatusForm                             1010
#define SatStatusModeList                         1011
#define SatStatusModePopTrigger                   1012

//	Resource: tFRM 1000
#define SatDataForm                               1000
#define SatDataModeList                           1001
#define SatDataModePopTrigger                     1002


//	Resource: MBAR 4000
#define MainMenuBar                               4000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAbout                              1000


//	Resource: tSTR 3000
#define diffCharString                            3000

//	Resource: tSTR 3002
#define d2DiffFixString                           3002

//	Resource: tSTR 3005
#define lostSatRecepString                        3005

//	Resource: tSTR 3003
#define d3FixString                               3003

//	Resource: tSTR 3006
#define neswString                                3006

//	Resource: tSTR 3012
#define elevString                                3012

//	Resource: tSTR 3013
#define snrString                                 3013

//	Resource: tSTR 3016
#define amString                                  3016

//	Resource: tSTR 3007
#define rString                                   3007

//	Resource: tSTR 3009
#define dString                                   3009

//	Resource: tSTR 3004
#define d2FixString                               3004

//	Resource: tSTR 3014
#define svidString                                3014

//	Resource: tSTR 3001
#define d3DiffFixString                           3001

//	Resource: tSTR 3011
#define azimString                                3011

//	Resource: tSTR 3010
#define eString                                   3010

//	Resource: tSTR 3015
#define pmString                                  3015

//	Resource: tSTR 3008
#define uString                                   3008

//	Resource: tSTR 3017
#define GPSIsOffString                            3017

//	Resource: tSTR 3018
#define simulatingGPSString                       3018


//	Resource: PICT 1200
#define AboutBitmapBitmap                         1200

//	Resource: PICT 1400
#define HDSmallIconBitmap                         1400

//	Resource: PICT 1300
#define NDSmallIconBitmap                         1300

//	Resource: PICT 1100
#define HDLargeIconBitmap                         1100

//	Resource: PICT 1000
#define NDLargeIconBitmap                         1000


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000


#endif // GPSINFO_RSRC_H
