//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 10:33:05 AM on Wednesday, April 16, 2003
//
//	Generated for file: D:\Godzilla\Software\PerForce\Professional_Services\Fossil\WristPDA_HAL_Apps_ROM\Apps\Watch\Rsc\Watch.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: tSTR 1
#define WatchAppSignatureString                   1	// "Wrist_PDA_Watch_App"


//	Resource: PICT 1000
#define LargeIconBitmap                           1000

//	Resource: PICT 1001
#define SmallIconBitmap                           1001

//	Resource: PICT 2600
#define Squashed0Bitmap                           2600

//	Resource: PICT 3110
#define BigSansColonBitmap                        3110

//	Resource: PICT 3109
#define BigSans9Bitmap                            3109

//	Resource: PICT 3108
#define BigSans8Bitmap                            3108

//	Resource: PICT 3107
#define BigSans7Bitmap                            3107

//	Resource: PICT 3105
#define BigSans5Bitmap                            3105

//	Resource: PICT 3106
#define BigSans6Bitmap                            3106

//	Resource: PICT 3103
#define BigSans3Bitmap                            3103

//	Resource: PICT 3104
#define BigSans4Bitmap                            3104

//	Resource: PICT 3101
#define BigSans1Bitmap                            3101

//	Resource: PICT 3102
#define BigSans2Bitmap                            3102

//	Resource: PICT 2710
#define Script2ColonBitmap                        2710

//	Resource: PICT 2708
#define Script28Bitmap                            2708

//	Resource: PICT 2702
#define Script22Bitmap                            2702

//	Resource: PICT 2703
#define Script23Bitmap                            2703

//	Resource: PICT 2704
#define Script24Bitmap                            2704

//	Resource: PICT 2705
#define Script25Bitmap                            2705

//	Resource: PICT 2706
#define Script26Bitmap                            2706

//	Resource: PICT 2707
#define Script27Bitmap                            2707

//	Resource: PICT 2709
#define Script29Bitmap                            2709

//	Resource: PICT 2700
#define Script20Bitmap                            2700

//	Resource: PICT 2701
#define Script21Bitmap                            2701

//	Resource: PICT 3100
#define BigSans0Bitmap                            3100

//	Resource: PICT 2000
#define Script10Bitmap                            2000

//	Resource: PICT 2001
#define Script11Bitmap                            2001

//	Resource: PICT 2002
#define Script12Bitmap                            2002

//	Resource: PICT 2003
#define Script13Bitmap                            2003

//	Resource: PICT 2004
#define Script14Bitmap                            2004

//	Resource: PICT 2005
#define Script15Bitmap                            2005

//	Resource: PICT 2006
#define Script16Bitmap                            2006

//	Resource: PICT 2007
#define Script17Bitmap                            2007

//	Resource: PICT 2008
#define Script18Bitmap                            2008

//	Resource: PICT 2009
#define Script19Bitmap                            2009

//	Resource: PICT 2010
#define Script1ColonBitmap                        2010

//	Resource: PICT 2800
#define Starck0Bitmap                             2800

//	Resource: PICT 2801
#define Starck1Bitmap                             2801

//	Resource: PICT 2802
#define Starck2Bitmap                             2802

//	Resource: PICT 2803
#define Starck3Bitmap                             2803

//	Resource: PICT 2804
#define Starck4Bitmap                             2804

//	Resource: PICT 2805
#define Starck5Bitmap                             2805

//	Resource: PICT 2806
#define Starck6Bitmap                             2806

//	Resource: PICT 2807
#define Starck7Bitmap                             2807

//	Resource: PICT 2808
#define Starck8Bitmap                             2808

//	Resource: PICT 2809
#define Starck9Bitmap                             2809

//	Resource: PICT 2810
#define StarckColonBitmap                         2810

//	Resource: PICT 2601
#define Squashed1Bitmap                           2601

//	Resource: PICT 2602
#define Squashed2Bitmap                           2602

//	Resource: PICT 2603
#define Squashed3Bitmap                           2603

//	Resource: PICT 2604
#define Squashed4Bitmap                           2604

//	Resource: PICT 2605
#define Squashed5Bitmap                           2605

//	Resource: PICT 2606
#define Squashed6Bitmap                           2606

//	Resource: PICT 2607
#define Squashed7Bitmap                           2607

//	Resource: PICT 2608
#define Squashed8Bitmap                           2608

//	Resource: PICT 2609
#define Squashed9Bitmap                           2609

//	Resource: PICT 2610
#define SquashedColonBitmap                       2610


//	Resource: taif 1000
#define LargeiconAppIconFamily                    1000

//	Resource: taif 1001
#define SmalliconAppIconFamily                    1001

