#ifndef PWRMGREXAMPLE_RSRC_H
#define PWRMGREXAMPLE_RSRC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 2:04:47 PM on Tuesday, December 07, 2004
//
//	Generated for file: PwrMgrExample.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"PwrMgr"
//
//	Palm App Version:		"1.1"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainInfoField                             1003
#define MainTitleLabel                            1004
#define MainDisablePushButton                     1001
#define MainEnablePushButton                      1002

//	Resource: tFRM 1100
#define AboutForm                                 1100
#define AboutOKButton                             1103
#define AboutSleepBitMap                          1200
#define AboutNameLabel                            1102
#define AboutCopyrightLabel                       1104
#define AboutVersionStringLabel                   1105


//	Resource: MBAR 1000
#define MainMenuBar                               1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAbout                              1000


//	Resource: PICT 1200
#define SleepBitmap                               1200

//	Resource: PICT 21100
#define SmallIconColorBitmap                      21100

//	Resource: PICT 1100
#define SmallIconBWBitmap                         1100

//	Resource: PICT 21000
#define LargeIconColorBitmap                      21000

//	Resource: PICT 1000
#define LargeIconBWBitmap                         1000


//	Resource: tbmf 1200
#define SleepBitmapFamily                         1200


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000


#endif // PWRMGREXAMPLE_RSRC_H
