//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 4:17:53 PM on Thursday, May 08, 2003
//
//	Generated for file: C:\os6projects\Aardvark\Rsc\resource.frk\AppResources.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Aardvark"
//
//	Palm App Version:		"1.0a1"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainAddButton                             1002	//(Left Origin = 1, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainLookupField                           1003	//(Left Origin = 87, Top Origin = 147, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainGSIGraffitiShift                      1005	//(Left Origin = 150, Top Origin = 150)
#define MainFindLabel                             1004	//(Left Origin = 46, Top Origin = 147, Usable = 1, Font = Bold)
#define MainItemsList                             1001	//(Left Origin = 6, Top Origin = 22, Width = 148, Usable = 1, Font = Standard, Visible Items = 10)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1100, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 59, Top Origin = 139, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 54, Top Origin = 26, Usable = 1, Font = Bold 12)
#define AboutText1Label                           1103	//(Left Origin = 35, Top Origin = 48, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 51, Top Origin = 115, Usable = 1, Font = Bold)


//	Resource: Talt 1000
#define PlaceholderAlert                          1000
#define PlaceholderOK                             0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutAardvark                  1000

//	Resource: MENU 10000
#define EditMenu                                  10000
#define EditUndo                                  10000	//  Command Key: U
#define EditCut                                   10001	//  Command Key: X
#define EditCopy                                  10002	//  Command Key: C
#define EditPaste                                 10003	//  Command Key: P
#define EditSelectAll                             10004	//  Command Key: S
#define EditKeyboard                              10006	//  Command Key: K
#define EditGraffitiHelp                          10007	//  Command Key: G


//	Resource: tSTR 1100
#define HelpID1100String                          1100	// "The name Aardvark signifies nothing: I just wanted my test apps to appear at the top of the Launcher list. I think the next app will be called Antelope..."


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

