//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 2:01:26 AM on Friday, January 1, 1904
//
//	Generated for file: PfutzHd:Projects:TornadoSDIO:test:SdioExample:Rsc:SdioExampleRsc.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"SdioExample"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainSdHwrTypeField                        1020
#define MainInsertTestCardLabel                   1001
#define MainWrongCardLabel                        1002
#define MainAutoOffLabel                          1007
#define MainLEDGreenPushButton                    1003
#define MainLEDOffPushButton                      1004
#define MainFunc1OFFPushButton                    1005
#define MainLEDRedPushButton                      1006
#define MainSleepWithCardOffPushButton            1009
#define MainSleepWithCardOnPushButton             1011
#define MainGroupID                               2
#define MainGroupID2                              1

//	Resource: tFRM 1100
#define AboutForm                                 1100
#define AboutAboutDoneButton                      1101
#define AboutAboutTextLabel                       1102


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1200
#define SlotDriverMissingAlert                    1200
#define SlotDriverMissingOK                       0

//	Resource: Talt 1300
#define GenericAlert                              1300
#define GenericOK                                 0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAbout                          1000

//	Resource: MENU 1100
#define DbgTraceMenu                              1100
#define DbgTraceAll                               1100
#define DbgTraceMost                              1101
#define DbgTraceCommandsOnly                      1102
#define DbgTraceNone                              1103

