//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 1:24:13 PM on Saturday, May 07, 2005
//
//	Generated for file: EDKDemo.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"EDK Demo"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainLedControlCheckbox                    1006	//(Left Origin = 104, Top Origin = 52, Width = 40, Height = 11, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainTemperatureField                      1005	//(Left Origin = 107, Top Origin = 36, Width = 32, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 8, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTemperatureLabel                      1002	//(Left Origin = 13, Top Origin = 36, Usable = 1, Font = Bold)
#define MainApplicationNameLabel                  1003	//(Left Origin = 1, Top Origin = 19, Usable = 1, Font = Bold 12)
#define MainCompanyNameLabel                      1004	//(Left Origin = 80, Top Origin = 22, Usable = 1, Font = Standard)
#define MainLEDControlLabel                       1007	//(Left Origin = 23, Top Origin = 51, Usable = 1, Font = Bold)
#define MainCardContentsTable                     1001	//(Left Origin = 4, Top Origin = 70, Width = 143, Height = 86, Editable = 0, Rows = 8)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1000, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutCompanyNameLabel                     1101	//(Left Origin = 51, Top Origin = 38, Usable = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 32, Top Origin = 23, Usable = 1, Font = Bold 12)
#define AboutText1Label                           1103	//(Left Origin = 24, Top Origin = 56, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define WaitForm                                  1200	//(Left Origin = 30, Top Origin = 60, Width = 96, Height = 31, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define WaitUnnamed1201Label                      1201	//(Left Origin = 18, Top Origin = 8, Usable = 1, Font = Bold 12)


//	Resource: Talt 1100
#define UnsupportedAlert                          1100
#define UnsupportedOK                             0

//	Resource: Talt 1200
#define UnimplementedAlert                        1200
#define UnimplementedOK                           0

//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1300
#define NoCardInsertedAlert                       1300
#define NoCardInsertedOK                          0

//	Resource: Talt 1400
#define UnrecognizedCardAlert                     1400
#define UnrecognizedCardOK                        0

//	Resource: Talt 1500
#define FuncNotAvailableAlert                     1500
#define FuncNotAvailableOK                        0

//	Resource: Talt 1600
#define SDIOErrorAlert                            1600
#define SDIOErrorOK                               0

//	Resource: Talt 1700
#define InternalErrorAlert                        1700
#define InternalErrorOK                           0

//	Resource: Talt 1800
#define ErrorErasingFlashAlert                    1800
#define ErrorErasingFlashOK                       0

//	Resource: Talt 1900
#define NoFlashImageAlert                         1900
#define NoFlashImageOK                            0

//	Resource: Talt 2000
#define ErrorProgrammingFlashAlert                2000
#define ErrorProgrammingFlashOK                   0

//	Resource: Talt 2100
#define SuccessProgrammingFlashAlert              2100
#define SuccessProgrammingFlashOK                 0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutEDKDemo                          1100
#define HelpSpecial                               1101

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsProgramFlashImage                  1000
#define OptionsSDIOTraceMost                      1001
#define OptionsSDIOTraceAll                       1002
#define OptionsSDIOTraceNone                      1003


//	Resource: tSTR 1000
#define EDKFuncTestHelpString                     1000	// "This applic"

//	Resource: tSTR 1100
#define HelpID1100String                          1100	// ""


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

