//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 1:35:13 PM on Saturday, May 07, 2005
//
//	Generated for file: SDDbgTrace.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"SD Dbg Trace"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainSDIOTraceLabel                        1002
#define MainApplicationNameLabel                  1003
#define MainCompanyNameLabel                      1004
#define MainTraceOptionsList                      1005
#define MainSDIOTracePopTrigger                   1001

//	Resource: tFRM 1100
#define AboutForm                                 1100
#define AboutOKButton                             1105
#define AboutCompanyNameLabel                     1101
#define AboutTitleLabel                           1102
#define AboutText1Label                           1103
#define AboutText2Label                           1104


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define UnsupportedAlert                          1100
#define UnsupportedOK                             0

//	Resource: Talt 1200
#define UnimplementedAlert                        1200
#define UnimplementedOK                           0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutSDIOTrace                 1000


//	Resource: tSTR 1000
#define SDDbgTraceHelpString                      1000


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

