/******************************************************************************
 *
 * Copyright (c) 2000-2003 PalmSource, Inc. All rights reserved.
 *
 * File: BtChatRsc.h
 *
 * Release: Palm OS 6.0
 *
 * Description: Resource constants for BtChat sample.
 *****************************************************************************/


//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 10:01:17 AM on Monday, November 11, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Bt Chat"
//
//	Palm App Version:		"2.0"

#ifndef _BTCHATRSC_H_
#define _BTCHATRSC_H_

//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainStopButton                            1003	//(Left Origin = 129, Top Origin = 17, Width = 27, Height = 10, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStartButton                           1004	//(Left Origin = 57, Top Origin = 29, Width = 36, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSendButton                            1007	//(Left Origin = 93, Top Origin = 17, Width = 30, Height = 10, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSentenceField                         1001	//(Left Origin = 4, Top Origin = 28, Width = 156, Height = 28, Usable = 0, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 125, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainConversationField                     1002	//(Left Origin = 0, Top Origin = 68, Width = 150, Height = 92, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4096, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define MainSentenceLabel                         1005	//(Left Origin = 4, Top Origin = 16, Usable = 0, Font = Bold)
#define MainUnnamed1006Label                      1006	//(Left Origin = 4, Top Origin = 56, Usable = 1, Font = Bold)
#define MainConversationScrollBar                 1008	//(Left Origin = 152, Top Origin = 68, Width = 7, Height = 92, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 8)


//	Resource: Talt 1001
#define MissingBtComponentsAlert                  1001
#define MissingBtComponentsOK                     0

//	Resource: Talt 1003
#define AcceptChatQuestionAlert                   1003
#define AcceptChatQuestionYes                     0
#define AcceptChatQuestionNo                      1

//	Resource: Talt 1004
#define ChatDeclinedAlert                         1004
#define ChatDeclinedOK                            0

//	Resource: Talt 1005
#define NoChatServiceAlert                        1005
#define NoChatServiceOK                           0

//	Resource: Talt 1006
#define NoConnectionAlert                         1006
#define NoConnectionOK                            0

//	Resource: Talt 1007
#define BtNotAvailableAlert                       1007
#define BtNotAvailableOK                          0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsStartanewchat                  1000	//  Command Key: S
#define MainOptionsStopchatting                   1001	//  Command Key: T
#define MainOptionsAboutBtChat                    1003


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001


//	Resource: tSTR 20010
#define ChatServiceInfoNameString				20010

//	Resource: tSTR 20020
#define ChatServerServiceDescriptionString			20020

#endif // _BTCHATRSC_H_

