#ifndef GCDRAWRESOURCES_H
#define GCDRAWRESOURCES_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 11:45:17 AM on Friday, August 08, 2003
//
//	Generated for file: GraphicsApp.xrd
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"GraphicsApp"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainFormForm                              1000
#define MainFormLogoButton		           		  1002
#define MainFormRotateButton	              	  1003

#define AboutDialog								  1100

//	Resource: Talt 1200
#define AboutAlert                                1200
#define AboutOK                                   0

//	Resource: Talt 1201
#define NoLogoAlert                               1201
#define NoLogoOK                                  0


//	Resource: MBAR 1000
#define MainMenuBar		                          1000


//	Resource: MENU 1101
#define MainOptionsMenu 	                      1101
#define MainOptionsMenuDetails                    1101
#define MainOptionsMenuAboutGcDraw                1102


//	Resource: PICT 1057
#define PSLogoBitmap                              1057


#endif // GCDRAWRESOURCES_H
