//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 17:32:29  on Thursday 13 December 2001
//
//	Generated for file: D:\MotownCafe\Apps\SdkExamples\BtLibTest\Rsc\BtLibTest.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:		"BtLibTest"
//
//	Palm App Version:		"1.0"

#ifndef BTLIBTESTRSC_H
#define BTLIBTESTRSC_H

//	Resource: tFRM 1000
#define MainForm							1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainLogField						1003	//(Left Origin = 0, Top Origin = 16, Width = 150, Height = 144, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4096, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define MainAddrLabel						1001	//(Left Origin = 72, Top Origin = 2, Usable = 1, Font = Standard)
#define MainBdAddrList						1002	//(Left Origin = 60, Top Origin = 1, Width = 100, Usable = 0, Font = Standard, Visible Items = 0)
#define MainLogScrollBar					1008	//(Left Origin = 152, Top Origin = 16, Width = 7, Height = 144, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 13)

//	Resource: tFRM 1200
#define InputForm							1200	//(Left Origin = 2, Top Origin = 70, Width = 156, Height = 88, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define InputOkButton						1203	//(Left Origin = 7, Top Origin = 71, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InputCancelButton					1204	//(Left Origin = 51, Top Origin = 71, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InputDataField						1201	//(Left Origin = 5, Top Origin = 28, Width = 145, Height = 34, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 99, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define InputUnnamed1202Label				1202	//(Left Origin = 4, Top Origin = 15, Usable = 1, Font = Standard)

//	Resource: tFRM 1300
#define AccessForm							1300
#define AccessUnnamedLabel					1301
#define AccessOkButton						1302
#define AccessCancelButton					1303
#define AccessNotConnectableRadio			1304
#define AccessConnectableRadio				1305
#define AccessDiscoverableConnectableRadio	1306

//	Resource: Talt 1001
#define MissingBtComponentsAlert			1001
#define MissingBtComponentsOK				0


//	Resource: MBAR 1000
#define MainFormMenuBar						1000


//	Resource: MENU 1000
#define MainLibMenu							1000
#define MainLibOpen							1000
#define MainLibClose						1002
#define MainLibAbout						1004

//	Resource: MENU 1100
#define MainMEMenu							1100
#define MainMEGetRole						1100
#define MainMEGetDeviceName					1101
#define MainMEInquiry						1102
#define MainMECancelInquiry					1103
#define MainMEConnectACL					1104
#define MainMEDisconnectACL					1105
#define MainMEAuthenticateLink				1106
#define MainMEToggleEncryption				1107
#define MainMEDiscoverMulti					1108
#define MainMEAccessibility					1109

//	Resource: MENU 1200
#define L2CAPMenu							1200
#define L2CAPListen							1200
#define L2CAPStopListening					1201
#define L2CAPConnect						1202
#define L2CAPDisconnect						1203
#define L2CAPSend							1204

//	Resource: MENU 1300
#define RFCOMMMenu							1300
#define RFCOMMListen						1300
#define RFCOMMStopListening					1301
#define RFCOMMConnect						1302
#define RFCOMMDisconnect					1303
#define RFCOMMSend							1304
#define RFCOMMAdvanceCredit					1305

//	Resource: MENU 1400
#define SCOMenu								1400
#define SCOListen							1400
#define SCOStopListening					1401
#define SCOConnect							1402
#define SCODisconnect						1403
#define SCOSend								1404

//	Resource: MENU 1500
#define BNEPMenu							1500
#define BNEPListen							1500
#define BNEPStopListening					1501
#define BNEPConnect							1502
#define BNEPDisconnect						1503
#define BNEPSend							1504

//	Resource: PICT 1002
#define SmallIconMonoBitmap					1002

//	Resource: PICT 1000
#define LargeIconMonoBitmap					1000


//	Resource: taif 1001
#define SmallAppIconsAppIconFamily			1001

//	Resource: taif 1000
#define LargeAppIconsAppIconFamily			1000

#endif // BTLIBTESTRSC_H
