#ifndef APPRESOURCES_H
#define APPRESOURCES_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 3:13:35 PM on Friday, August 01, 2003
//
//	Generated for file: GcFonts.xrd
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"GcFonts"
//
//	Palm App Version:		"1.0a1"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainFontLabel                             1001
#define MainFaceLabel                             1005
#define MainTextLabel                             1006
#define MainCanvasGadget                          1007
#define MainSizePushButton                        1002
#define MainShearPushButton                       1003
#define MainAnglePushButton                       1004
#define MainAmountFeedbackSliderControl           1008
#define MainAmountLabel                           1009
#define MainSampleField                           1010
#define MainGSIGraffitiShift                      1012
#define MainFamilyPopTrigger                      1011
#define MainFacePopTrigger                        1013
#define MainFamilyList                            1014
#define MainFaceList                              1015
#define MainValueField                            1016
#define MainGroupID                               1

//	Resource: tFRM 2000
#define AboutForm                                 2000
#define AboutTitleLabel                           2002
#define AboutText1Label                           2003
#define AboutText2Label                           2004
#define AboutOKButton                             2005


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutGcFonts                   1000

//	Resource: MENU 10000
#define EditMenu                                  10000
#define EditUndo                                  10000
#define EditCut                                   10001
#define EditCopy                                  10002
#define EditPaste                                 10003
#define EditSelectAll                             10004
#define EditKeyboard                              10006
#define EditGraffitiHelp                          10007


//	Resource: tSTR 1200
#define HelpID1200String                          1200


#endif // APPRESOURCES_H
