//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 9:50:07 AM on Tuesday, February 10, 2004
//
//	Generated for file: D:\PDA\ique3600\Garmin\PINMgrExample.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"PINMgr"
//
//	Palm App Version:		"1.1"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainGlobeBitMap                           1200	//(Left Origin = 46, Top Origin = 50, Bitmap Resource ID = 1200, Usable = 1)
#define MainAreaStateField                        1002	//(Left Origin = 0, Top Origin = 140, Width = 80, Height = 20, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTriggerStateField                     1004	//(Left Origin = 80, Top Origin = 140, Width = 80, Height = 20, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainOpenPushButton                        1003	//(Left Origin = 4, Top Origin = 20, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainClosePushButton                       1005	//(Left Origin = 41, Top Origin = 20, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainEnablePushButton                      1006	//(Left Origin = 84, Top Origin = 20, Width = 36, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainDisablePushButton                     1007	//(Left Origin = 121, Top Origin = 20, Width = 36, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainGroupID                               1
#define MainGroupID2                              2

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1103	//(Left Origin = 60, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutGlobeBitMap                          1200	//(Left Origin = 46, Top Origin = 14, Bitmap Resource ID = 1200, Usable = 1)
#define AboutUnnamed1102Label                     1102	//(Left Origin = 9, Top Origin = 79, Usable = 1, Font = Bold)
#define AboutUnnamed1104Label                     1104	//(Left Origin = 9, Top Origin = 103, Usable = 1, Font = Standard)


//	Resource: MBAR 1000
#define MainMenuBar                               1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsFont                               1000
#define OptionsAbout                              1001


//	Resource: PICT 1200
#define GlobeBitmap                               1200

//	Resource: PICT 1100
#define NDBigIconBitmap                           1100

//	Resource: PICT 1000
#define HDBigIconBitmap                           1000

//	Resource: PICT 1300
#define DDGlobeBitmap                             1300

//	Resource: PICT 1400
#define NDSmallIconBitmap                         1400

//	Resource: PICT 1500
#define DDSmallIconBitmap                         1500


//	Resource: tbmf 1200
#define GlobeBitmapFamily                         1200


//	Resource: taif 1000
#define BigIconAppIconFamily                      1000

//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

