//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 5:29:05 PM on Friday, December 17, 2004
//
//	Generated for file: C:\Dev\Projects\WristPDA_EFIGS\WristPDA_HAL_Apps_ROM\Apps\JotCtrl\Rsc\JotCtrl.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"JotCtrl"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainDoneButton                            1003	//(Left Origin = 59, Top Origin = 142, Width = 36, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainEnableJotCheckbox                     1002	//(Left Origin = 5, Top Origin = 19, Width = 120, Height = 14, Usable = 1, Selected = 1, Group ID = 0, Font = Bold 12)
#define MainEnableWritingCheckbox                 1004	//(Left Origin = 5, Top Origin = 36, Width = 120, Height = 14, Usable = 1, Selected = 1, Group ID = 0, Font = Bold 12)
#define MainEnableInkingCheckbox                  1005	//(Left Origin = 5, Top Origin = 53, Width = 120, Height = 14, Usable = 1, Selected = 1, Group ID = 0, Font = Bold 12)
#define MainEnableModeMarkCheckbox                1006	//(Left Origin = 5, Top Origin = 70, Width = 120, Height = 14, Usable = 1, Selected = 1, Group ID = 0, Font = Bold 12)
#define MainDescriptionField                      1001	//(Left Origin = 7, Top Origin = 102, Width = 146, Height = 40, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 1024, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1007Label                      1007	//(Left Origin = 7, Top Origin = 88, Usable = 1, Font = Bold 12)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 139, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 62, Top Origin = 19, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 12, Top Origin = 58, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 38, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define JotCtrlMainMenuBar                        1000


//	Resource: MENU 1000
#define AboutMenu                                 1000
#define AboutAboutJotCtrl                         1000


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

