//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 3:37:34 PM on Saturday, January 25, 2003
//
//	Generated for file: N:\Godzilla\Deliverable\Apps\Memo\Rsc\MemoEdit.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1100
#define MemoEditViewForm                          1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)
#define MemoEditViewDoneButton                    1105	//(Left Origin = 1, Top Origin = 143, Width = 30, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MemoEditViewDetailsButton                 1108	//(Left Origin = 40, Top Origin = 143, Width = 42, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MemoEditViewMemoFieldField                1109	//(Left Origin = 1, Top Origin = 19, Width = 158, Height = 121, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4096, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define MemoEditViewFossilLaragerFontGadget       1170	//(Left Origin = 0, Top Origin = 1, Width = 2, Height = 3, Usable = 0)
#define MemoEditViewGraffitiShiftIndicatorGraffitiShift 1111	//(Left Origin = 102, Top Origin = 147)
#define MemoEditViewCategoriesListList            1104	//(Left Origin = 66, Top Origin = 2, Width = 92, Usable = 0, Font = Standard, Visible Items = 0)
#define MemoEditViewPageUpRepeating               1113	//(Left Origin = 124, Top Origin = 147, Width = 16, Height = 12, Usable = 1, Anchor Left = 0, Frame = 0, Non-bold Frame = 0, Font = Symbol 7)
#define MemoEditViewPageDownRepeating             1114	//(Left Origin = 142, Top Origin = 146, Width = 16, Height = 12, Usable = 1, Anchor Left = 0, Frame = 0, Non-bold Frame = 0, Font = Symbol 7)
#define MemoEditViewCategorySelTrigger            1103	//(Left Origin = 159, Top Origin = 2, Width = 0, Height = 11, Usable = 1, Anchor Left = 0, Font = Standard)


//	Resource: tSTR 1112
#define MemotitlestringString                     1112	// "Memo ^0 of ^1"

