#ifndef QUEAPILIBEXAMPLE_H
#define QUEAPILIBEXAMPLE_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 8:27:44 AM on Tuesday, December 07, 2004
//
//	Generated for file: QueAPILibExample.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"QueAPILib Example"
//
//	Palm App Version:		"1.1"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainRouteToShowMapButton                  1001	//(Left Origin = 83, Top Origin = 65, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCreatePointButton                     1002	//(Left Origin = 3, Top Origin = 17, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainClearRouteToButton                    1003	//(Left Origin = 83, Top Origin = 81, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSelectPointMapButton                  1004	//(Left Origin = 83, Top Origin = 17, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSelectPointFindButton                 1005	//(Left Origin = 3, Top Origin = 33, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainRouteToPointButton                    1006	//(Left Origin = 3, Top Origin = 65, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainShowDetailsButton                     1009	//(Left Origin = 3, Top Origin = 49, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSetRouteToButton                      1013	//(Left Origin = 3, Top Origin = 81, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainShowOnMapButton                       1014	//(Left Origin = 83, Top Origin = 49, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCreateButton                          1019	//(Left Origin = 3, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSelectButton                          1020	//(Left Origin = 45, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCreateSelectButton                    1021	//(Left Origin = 87, Top Origin = 146, Width = 70, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainShowInfoButton                        1022	//(Left Origin = 83, Top Origin = 33, Width = 74, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStreetField                           1010	//(Left Origin = 43, Top Origin = 106, Width = 115, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCityField                             1012	//(Left Origin = 29, Top Origin = 119, Width = 129, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainStateField                            1016	//(Left Origin = 38, Top Origin = 132, Width = 21, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainZipField                              1018	//(Left Origin = 85, Top Origin = 132, Width = 73, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1007Label                      1007	//(Left Origin = 60, Top Origin = 95, Usable = 1, Font = Bold)
#define MainUnnamed1008Label                      1008	//(Left Origin = 2, Top Origin = 106, Usable = 1, Font = Bold)
#define MainUnnamed1011Label                      1011	//(Left Origin = 2, Top Origin = 119, Usable = 1, Font = Bold)
#define MainUnnamed1015Label                      1015	//(Left Origin = 2, Top Origin = 132, Usable = 1, Font = Bold)
#define MainUnnamed1017Label                      1017	//(Left Origin = 63, Top Origin = 132, Usable = 1, Font = Bold)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 93, Width = 156, Height = 65, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1103	//(Left Origin = 60, Top Origin = 46, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1102Label                     1102	//(Left Origin = 9, Top Origin = 17, Usable = 1, Font = Bold)


//	Resource: Talt 1100
#define InformationAlert                          1100
#define InformationOK                             0


//	Resource: MBAR 1000
#define MainMenuBar                               1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAbout                              1000


//	Resource: tSTR 3006
#define neswString                                3006	// "NESW"


//	Resource: PICT 1100
#define NDBigIconBitmap                           1100

//	Resource: PICT 1000
#define HDBigIconBitmap                           1000

//	Resource: PICT 1400
#define NDSmallIconBitmap                         1400

//	Resource: PICT 1500
#define DDSmallIconBitmap                         1500


//	Resource: taif 1000
#define BigIconAppIconFamily                      1000

//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001


#endif // QUEAPILIBEXAMPLE_H
